### ISSUE TITLE
Viva Wallet, Payment Failed,3d secure looks mess.

### ISSUE THREAD

**Issue by EuroStreet** [VivaPayments/API#1173] opened 2019-10-25 09:09 UTC
Hello, I set up the viva wallet on our website, I followed all the instructions, and it looks perfectly fine.
However, when I go to make the Payment, it keeps getting ''Failed''.
I also contacted the Viva Wallet support, and they send me here.
My shop is also Activated on the Viva Wallet account.
I'm using open cart 2.3.2, and installed the plugin of the Viva Wallet that you had in instructions.
Pictures:
![image](https://user-images.githubusercontent.com/56961296/67551936-a4ed5500-f712-11e9-8ef3-6b92fe5fb92b.png)

![image](https://user-images.githubusercontent.com/56961296/67558746-37e0bc00-f720-11e9-87e5-a197e54d516b.png)
And after it just fails the payment, and return to our website on the failure payment url.

**Comment by EuroStreet** [comment] 2019-10-25 09:10
![image](https://user-images.githubusercontent.com/56961296/67558828-69598780-f720-11e9-9f58-7f2721fcdd24.png)
and this is how it looks after the redirection from our checkout

**Comment by EuroStreet** [comment] 2019-10-26 10:27
Any help please @VivaWalletSupport

**Comment by matthewrgourd** [comment] 2019-11-01 10:32
Duplicate of https://github.com/VivaPayments/API/issues/1169

**Closed by matthewrgourd** 2019-11-01 10:32 UTC
Labels: e-commerce plugin
