### ISSUE TITLE
module errors

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1788] opened 2020-07-20 16:39 UTC
Hi @matthewrgourd I have some problems with this merchant **Fused Technology**,
´´I tried to make a purchase with a mastercard and it was a mistake.  When you finish a purchase to pay, it takes you out of the web to your page which generates distrust in the customer. Another mistake that appears is that the customer pays but we do not see it as a normal validated order, it stays in the cart and we have to accept it manually, so I see the amount that the customer is charged is correct in the case of the capture 56.30 but in the cart there are some shipping costs of 6.50 that do not have to be charged because it is free shipping and having 2 different amounts I think it is a failure for which there is no validated order´´
![viva1](https://user-images.githubusercontent.com/56823712/87962975-51990f00-cab8-11ea-8255-c671d0dc2ab9.JPG)
![carrito](https://user-images.githubusercontent.com/56823712/87962990-55c52c80-cab8-11ea-8216-79a777084130.JPG)
![carrito2](https://user-images.githubusercontent.com/56823712/87962998-58278680-cab8-11ea-958c-ff6bf2ec0640.JPG)

Thx in advance

**Comment by matthewrgourd** [comment] 2020-07-21 08:31
Hi @Alvaroalconada I've checked and the plugin seems to be working fine. This is a PrestaShop website, is that correct? Please let me know the version of PrestaShop that the merchant is using so I can investigate a bit more. Regarding shipping costs etc. these are handled by PrestaShop, as far as I'm aware. The error sounds like a misconfiguration of the platform? As regards being redirected from the site, that is unavoidable as the plugin is a redirect plugin not a native one. Unfortunately we do not have a native plugin available for PrestaShop, only for WooCommerce. I suggest the merchant considers moving to WooCommerce for an improved user experience and compatibility with our [native checkout](https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/).

**Comment by Alvaroalconada** [comment] 2020-07-22 11:04
@matthewrgourd the version is prestashop is 1.6.1 and the customer tells me that the orders remain in the cart and the process not finished.

**Comment by matthewrgourd** [comment] 2020-07-22 13:12
Hi @Alvaroalconada, thanks for confirming. Settings are correct for PrestaShop v1.6. As I say, I tested and the redirect / shopping cart is working fine. I just looked at the sales transactions for the merchant's account and he's had 54 successful payments with zero failures since 20th July? I suggest the problem is maybe with one or two customers who have incompatible cards (no 3DS available).

**Comment by Alvaroalconada** [comment] 2020-07-22 16:28
@matthewrgourd Ok, it seems that everything is ok. Could you show me how can my merchant makes a full or partial refund from prestashop?

**Comment by matthewrgourd** [comment] 2020-07-23 07:18
Hi @Alvaroalconada we cannot help with PrestaShop queries, only those related to the plugin. FYI, there is no "refund from Viva Wallet" option. This feature is provided only with our WooCommerce plugin. For PrestaShop queries, please get the merchant to check the [documentation](http://doc.prestashop.com/pages/viewpage.action?pageId=20578582).

**Comment by Alvaroalconada** [comment] 2020-12-04 06:40
@matthewrgourd This merchant told me yesterday the next:
We have been several days with many more complaints than normal of failure to pay and customers who have paid previously with the payment platform so I'm more fly, puts them all the time failed transaction, always send me the same image, the same thing to update something.
![vapeototal](https://user-images.githubusercontent.com/56823712/101130544-efbee900-3603-11eb-8814-f6f774ddeba6.png)

**Comment by matthewrgourd** [comment] 2020-12-04 06:45
Hi @Alvaroalconada please confirm the merchant name and website address for the issue above. Thank you.

**Comment by Alvaroalconada** [comment] 2020-12-04 06:48
@matthewrgourd Fused Technology SL https://www.vapeototal.net/

**Comment by matthewrgourd** [comment] 2020-12-04 07:23
Hi @Alvaroalconada, I've checked and there is no problem with payments through Viva Wallet. Please advise the merchant I just made 4 test purchases with a card with no funds so they will have 4 orders for €41.11 in PrestaShop which they should ignore. However, the merchant has not configured their source code correctly as stated in our [plugin installation guide](https://developer.vivawallet.com/e-commerce-plugins/prestashop1.5-1.6/). Please get them to update their PrestaShop "Source code" value to **5959** in their module settings. This will mean that customer are directed to the success / failure pages on the merchant's website correctly after making payment.

**Comment by Alvaroalconada** [comment] 2020-12-04 08:38
Hi @matthewrgourd Is there any possibility that you can change this number over there? because merchant tells me that doesn´t get to keep in touch with his tecnical person for doing it...

**Comment by matthewrgourd** [comment] 2020-12-04 11:52
Hi @Alvaroalconada, we can't do that for the merchant I'm afraid. He will have to get hold of the technical person originally responsible for the installation.

**Comment by Alvaroalconada** [comment] 2020-12-09 08:59
Hi @matt merchant tells me the next:

We´ve put code that you told me the other day and now system gives all the time payment error.

Order is entered but people cannot pay and the payment tab does not show the payment platform or transaction identifier.

Now doesn´t work with any card. One entered well but comes out duplicated in the prestashop and others keep jumping on payment errors.

We just have change the code and it's all fucked up

**Comment by matthewrgourd** [comment] 2020-12-09 09:14
Hi @Alvaroalconada, so that I can check further, please get them to send a screenshot of their settings for the Viva Wallet payment module from PrestShop. They will need to blur out any confidential info.

**Comment by Alvaroalconada** [comment] 2020-12-09 09:21
@matthewrgourd ok, when I have, I´ll send you by mail

**Comment by matthewrgourd** [comment] 2020-12-09 09:21
Hi @Alvaroalconada, actually, ignore that last request. I just tested their checkout at https://www.vapeototal.net/ and everything is working fine. Please advise them that there is nothing further to do...

**Closed by matthewrgourd** 2020-12-09 09:21 UTC
Labels: e-commerce plugin

**Comment by Alvaroalconada** [comment] 2020-12-09 09:25
@matthewrgourd really? is very strange...

**Comment by matthewrgourd** [comment] 2020-12-09 09:27
@Alvaroalconada, please speak to me on Teams if you want any further information.

**Comment by Alvaroalconada** [comment] 2020-12-10 07:23
Good morning Matt! merchant tells me the next:

I have a customer so i see it is mastercard
 You have an order but it does not appear in the loan or in my customer area of viva wallet
 And on top of that, they have been charged twice
You can confirm me as soon as possible if you can find it
 And why doesn't it show up on my live account

![MicrosoftTeams-image (41)](https://user-images.githubusercontent.com/56823712/101734573-cb11b800-3ac0-11eb-972a-80f720f79619.png)

**Comment by matthewrgourd** [comment] 2020-12-10 07:50
Hi @Alvaroalconada are you referring to the same merchant at https://www.vapeototal.net/? I already advised that the plugin is working correctly. I will check their account but really this is an account query the merchant should speak to our live chat about or you could speak to our Operations Team about the transactions on their behalf. It's definitely not a technical problem and I do not provide after-sales support I'm afraid. Did you find out if they were enrolled with Mastercard. At the moment it looks like that hasn't happened yet. I can check for you, but again, this is something the Operations Team would normally look into.

**Comment by Alvaroalconada** [comment] 2020-12-10 12:12
@matthewrgourd Can you show me how to put his account in demo for making some test payments? because fucking error is still currently

**Comment by matthewrgourd** [comment] 2020-12-10 12:21
Hi @Alvaroalconada, this will just confuse matters. His checkout is working fine but there's a problem with the card number ending "5545". He has made 5 transactions for €55.50 recently and all have failed with the reason "Mastercard Do Not Honour". He should speak to his card issuer or test with a different card.
