### ISSUE TITLE
Antonio Navarro

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1905] opened 2020-10-07 09:32 UTC
Hi @matthewrgourd this merchant **** doesn´t know if the next fields are filling up corretly. He is using Woocommerce. Could you check it?
![Issue Antonio Navarro](https://user-images.githubusercontent.com/56823712/95313617-9dc24700-0890-11eb-979b-964aee6de5d4.png)

**Comment by matthewrgourd** [comment] 2020-10-07 09:57
Duplicate of #1904

**Comment by matthewrgourd** [comment] 2020-10-07 09:59
Duplicate of #1904

**Comment by Alvaroalconada** [comment] 2020-10-07 10:31
@matthewrgourd he did it and appear the next screenshot, Which would be to do it now?
![MicrosoftTeams-image (17)](https://user-images.githubusercontent.com/56823712/95319924-f4cc1a00-0898-11eb-9134-734d475c3b04.png)

**Comment by matthewrgourd** [comment] 2020-10-07 10:40
That's fine, the plugin is set up correctly now.

**Comment by Alvaroalconada** [comment] 2020-10-07 10:43
Perfect! I´ll inform him,very kind like always Sir

**Comment by Alvaroalconada** [comment] 2020-10-07 15:49
@matthewrgourd appearing trx failed. Do you know what is the reason?
![MicrosoftTeams-image (18)](https://user-images.githubusercontent.com/56823712/95355139-7f2a7300-08c5-11eb-8788-f47929e59b8f.png)

**Comment by matthewrgourd** [comment] 2020-10-07 15:59
Hi @Alvaroalconada, I'm not sure what the issue is. Can I get another screenshot of the module settings from within PrestaShop?

**Comment by matthewrgourd** [comment] 2020-10-08 14:18
Hi @Alvaroalconada, yes, that's the one. Settings look fine now so I'm not sure what the problem is.

**Comment by matthewrgourd** [comment] 2020-10-08 14:19
Is this still an issue?

**Comment by Alvaroalconada** [comment] 2020-10-08 15:10
yes, continue the problem. Maybe will be the issue here:
![MicrosoftTeams-image (20)](https://user-images.githubusercontent.com/56823712/95477936-30dea800-0989-11eb-80dd-05ca9580ef10.png)

**Comment by matthewrgourd** [comment] 2020-10-09 08:04
Hi @Alvaroalconada, can you confirm again which version of PrestaShop the merchant is using?

**Comment by Alvaroalconada** [comment] 2020-10-09 10:10
Hi @matthewrgourd! here you have 
![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/56823712/95571224-61295380-0a28-11eb-816e-ae3e4a6986a7.png)

**Comment by matthewrgourd** [comment] 2020-10-09 10:46
@Alvaroalconada, ok, settings are correct. Could you get him to enable on his site at https://cesdesalud.es/ so I can test? It's currently showing other providers at checkout but not us.

**Comment by matthewrgourd** [comment] 2020-10-13 09:40
Hi @Alvaroalconada is this still an issue? If not, please close.

**Comment by Alvaroalconada** [comment] 2020-10-13 12:06
Hi @matthewrgourd I´m waiting an answer from merchant

**Closed** 2020-10-13 14:59 UTC
Labels: e-commerce plugin
