### ISSUE TITLE
Wordpress/plugin issue

### ISSUE THREAD

**Issue by juicefordays** [VivaPayments/API#667] opened 2018-12-17 14:53 UTC
Hello,

I am using Wordpress for my backend and woo commerce for the shopping cart. When a payment is processed through my website and has not been approved yet, on Wordpress it says ‘pending payment’. When the payment is then approved by VivaWallet’ it should automatically communicate with Wordpress to change the status to ‘processing payment’, this is not happening. 

Can someone help me with how to update the settings? I use PayPal and they automatically communicate with Wordpress when the pending payment becomes approved, The status is changed to ''processing''

Thanks

**Comment by juicefordays** [comment] 2018-12-17 14:56
![image from ios](https://user-images.githubusercontent.com/45943392/50094806-ef0ccc80-020b-11e9-9cea-d7d8a6de7897.jpg)

**Comment by VivaWalletSupport** [comment] 2018-12-17 15:19
Hello, could you post a screenshot of the plugin settings (mask the API Key) and a screenshot of the payment source you have setup in your Viva account?

**Comment by VivaWalletSupport** [comment] 2018-12-17 15:34
I cannot see what the problem is over the phone, I would need the 2 screenshots asked for in my previous post and I would need to know what plugin is used to connect with Viva payments.

**Comment by lakelandcbd** [comment] 2019-01-03 16:12
Hey Guys, we are having this issue also, did you get a resolution?

**Comment by VivaWalletSupport** [comment] 2019-01-03 17:04
@lakelandcbd good evening, as the merchant did not post the requested information I suppose they solved the problem by themselves. In case you use the supported plugin to connect, post the screenshots as asked before. If you use a 3rd party plugin to connect, contact the developer.

**Comment by juicefordays** [comment] 2019-01-04 13:55
Hi Tom
This email was going into our junk there is still problem.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by VivaWalletSupport** [comment] 2019-01-04 14:05
Hello, in that case I would suggest to post the 2 screenshots that I asked for and to monitor this thread with your browser.

**Comment by juicefordays** [comment] 2019-01-04 14:52
By payment you meant "the pluging we are using"?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by VivaWalletSupport** [comment] 2019-01-04 15:09
-screenshot of the plugin settings (mask the API Key) -> payment plugin used in your store
-screenshot of the payment source you have setup in your Viva account -> viva account settings

Vivawallet setup:
https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

**Comment by juicefordays** [comment] 2019-01-04 15:11
Sorry I wanted to what you meant by payment source.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by VivaWalletSupport** [comment] 2019-01-04 15:15
Please take a moment to read the readme.txt (Vivawallet setup) at the link I sent you before:
https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

**Comment by juicefordays** [comment] 2019-01-04 17:36
I Read that but not sure what you mean by that. First part I did (PFA)

[Image]


[Image]




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by VivaWalletSupport** [comment] 2019-01-05 06:41
Please do not post comments with images or any other attachments through email, post them by visiting this thread as now they are not visible. In case you have any specific part with setting up a payment source in your viva account, please let me know.

**Comment by juicefordays** [comment] 2019-01-05 12:11
Hi Tom,


Is there any way we can talk. You can call me on 07411766635 or give me your number I can reach you on. I am not clear what you are asking me to do.

Looking forward to hearing from you.


Regards


Evan

________________________________

**Comment by VivaWalletSupport** [comment] 2019-01-05 13:12
That is not possible, post your screenshots at https://github.com/VivaPayments/API/issues/667 do not use your email to reply with images (as you can see your previous post does not show any image).

Example screenshot plugin settings:
https://user-images.githubusercontent.com/22427823/47774613-32f85080-dcf6-11e8-991d-30a677579bd4.png

Example payment source settings:
https://user-images.githubusercontent.com/22427823/47774537-f593c300-dcf5-11e8-975c-ba7e93a4b397.png

**Comment by juicefordays** [comment] 2019-01-08 08:32
Hi Not yet.Just figured out we have a github account. We were not not aware of this.We were thinking we were getting emails.

**Comment by juicefordays** [comment] 2019-01-08 08:34
Whe are the options to upload pic.

**Comment by VivaWalletSupport** [comment] 2019-01-08 08:52
http://prntscr.com/m4d24k

**Comment by juicefordays** [comment] 2019-01-08 16:15
Try to drop screen shot but it is not working. 

Please assist me in getting this resolved. 

If it is easier can you do a screen share?

Thanks

**Comment by juicefordays** [comment] 2019-01-08 16:16
![plugin viva wallet screen shot](https://user-images.githubusercontent.com/45943392/50843535-c8503a80-1360-11e9-9d84-bc56bb3c6cce.png)

**Comment by juicefordays** [comment] 2019-01-08 16:20
Ok managed to work it out. This is my Vivawallet plugin.

**Comment by juicefordays** [comment] 2019-01-08 16:21
![gateway 1 vivawallet](https://user-images.githubusercontent.com/45943392/50843834-6512d800-1361-11e9-986f-909c39473b24.png)

![gateway 2 vivawallet](https://user-images.githubusercontent.com/45943392/50843842-68a65f00-1361-11e9-8127-4b90b6cce2b2.png)

**Comment by juicefordays** [comment] 2019-01-08 16:21
Payment Gateway screen shot attached.

**Comment by VivaWalletSupport** [comment] 2019-01-08 17:17
Please also post a screenshot of the payment source (with the code 7501) that you created in your viva account.

**Comment by VivaWalletSupport** [comment] 2019-01-09 06:18
For an example what I need please see following: http://prntscr.com/m4r5pj

**Comment by juicefordays** [comment] 2019-01-11 12:53
![payment gateway 211](https://user-images.githubusercontent.com/45943392/51034826-e5bf1780-159f-11e9-9c84-19641f1fcc81.png)

**Comment by VivaWalletSupport** [comment] 2019-01-11 13:08
Thank you, correct the Domain Name in this payment source to juicefordays.co.uk (as your site does not use www), let me know in case you have any other problem afterwards or close this issue.

**Comment by juicefordays** [comment] 2019-01-12 12:06
![screenshot_1000](https://user-images.githubusercontent.com/45943392/51072993-870ea200-1662-11e9-9e0c-9bee4ae84b99.png)

**Comment by juicefordays** [comment] 2019-01-12 12:08
I get that error message

**Comment by VivaWalletSupport** [comment] 2019-01-12 12:18
As mentioned before use **juicefordays.co.uk**, not www.juicefordays.co.uk and not https://juicefordays.co.uk

**Comment by VivaWalletSupport** [comment] 2019-01-12 12:42
Can you send a screenshot of the source listings like:
http://prntscr.com/m681u8

**Comment by juicefordays** [comment] 2019-01-12 12:46
how do i get to that screen

**Comment by VivaWalletSupport** [comment] 2019-01-12 16:01
Just made a test order in your store (order 29909), please check the order status. Try also an order yourself to verify the working.

**Comment by juicefordays** [comment] 2019-01-12 19:18
your order came through fine.We will try out few more over the weekend

**Closed** 2019-06-17 15:30 UTC
