### ISSUE TITLE
Help finalising Vivawallet into Shopify.. "Could not create order. Generic Error" 

### ISSUE THREAD

**Issue by Origin19** [VivaPayments/API#1771] opened 2020-07-08 09:07 UTC
Hi good morning. 

I have been sent a merchant Id and store token which has been copied over fine but when I go to make a payment on the website it directs me to https://checkout.vivawallet.com/shopifyplugin and the page says "Error
Could not create order. Generic Error." 

Could anybody assist me please?  

Many regards.

**Comment by matthewrgourd** [comment] 2020-07-09 16:18
Hi @Origin19, please double-check that you're entering your [Merchant ID](https://developer.vivawallet.com/e-commerce-plugins/merchant-id) and Store Token (emailed to you) correctly (step 11 in our [Setup instructions](https://developer.vivawallet.com/e-commerce-plugins/shopify/#setup-instructions).)

**Comment by Origin19** [comment] 2020-07-10 00:28
Everything has been copied over correctly from what they have sent me. Does my payment source settings have any effect on this? As in, have I set it up right when adding my website in the website/app section? Reaally struggling to get my head round it as its the last thing obviously before I can go live!

**Comment by matthewrgourd** [comment] 2020-07-10 09:27
Hi @Origin19 sorry you're still experiencing difficulties. Could you share your shop URL and Viva Wallet account name so I can check further?

**Comment by Origin19** [comment] 2020-07-10 12:41
Thanks for getting back. The website is www.herbalorigin.co.uk and the account name is HERBALORIGIN LIMITED

Regards.

**Comment by matthewrgourd** [comment] 2020-07-10 14:04
Did you complete [this form](https://forms.office.com/FormsPro/Pages/ResponsePage.aspx?id=11xgZwUpeU2CVq4fVCDCd_r-QSHD_PtMuAvap6OPapdUNkVITTFMNzMyWFdYSUJWNUw4MkxGSlhXRi4u) to request your store token? What URL did you provide for 'Shopify store URL'? If it's https://herbalorigin.co.uk/, which seems to be password protected, we would have asked you to publish it first?

**Comment by Origin19** [comment] 2020-07-10 14:11
Yes I have, I also have emails from viva wallet giving me domain approval for this site after presenting them with passwords and the relevant information.

**Comment by Origin19** [comment] 2020-07-10 14:13
They sent me a token straight after the approval just to add. Regards

**Comment by matthewrgourd** [comment] 2020-07-10 14:16
Hi @Origin19 please email me your token so I can confirm that it's the correct one. My email is mgourd@vivawallet.com. Thanks!

**Comment by Origin19** [comment] 2020-07-10 14:17
Sent!

**Comment by matthewrgourd** [comment] 2020-07-10 14:52
Closing as solved by email...

**Closed by matthewrgourd** 2020-07-10 14:52 UTC
Labels: shopify
