### ISSUE TITLE
Payment Icons are missing from shopify footer

### ISSUE THREAD

**Issue by jonsvarn** [VivaPayments/API#2218] opened 2022-07-04 08:30 UTC
After switching to the new viva payments plugin the payment icons of the selected payment providers are missing from the footer.

**Comment by can3ry** [comment] 2022-07-05 10:29
Hello @jonsvarn 

We appreciate your message and that you reached out to us directly.

Could you give us some more details about the payment icons? Do you mean the logos of card schemes? 

Please also share your merchant id and screenshots related to the payment icons area.

Kind regards,
Viva Wallet Development Team

**Comment by jonsvarn** [comment] 2022-07-05 10:37
Yes the i mean the logos.
I have switched to the new plugin in 4 shops so far. And the chosen payment providers logos on the footers are missing from all of them. With other shop which uses mollie as a payment gateway the logos are appearing as normal.
As you can see on the shop using viva wallet the only logo visible is from paypal (which is also active as a payment gateway)
![Screenshot 2022-07-05 at 1 32 55 PM](https://user-images.githubusercontent.com/108658231/177309582-2f0112d2-d51c-42b6-94a9-fb9be65f775b.png)
![Screenshot 2022-07-05 at 1 32 15 PM](https://user-images.githubusercontent.com/108658231/177309591-208d5ff1-0a8d-4813-bba8-5428140dc34e.png)
.

**Comment by can3ry** [comment] 2022-07-05 11:25
Hi @jonsvarn 

Would you mind sharing a full screenshot and a domain name please?

I've checked old and new integrations from Shopify and the logos seem okay.

<img width="652" alt="payment-method-select" src="https://user-images.githubusercontent.com/51880555/177315651-dde83ee3-b4e2-4504-8c47-ce1a2b6e1f86.png">

Thanks

Kind regards,
Viva Wallet Development Team

**Comment by can3ry** [comment] 2022-07-08 13:16
Hello @jonsvarn 

Thanks for the further details.

If you replace **shop.enabled_payment_types** with **enabled_payment_types** in the for loop, it would work. Please see the example below

```html
        <div class="footer__payment">
          <span class="visually-hidden">{{ 'sections.footer.payment' | t }}</span>
          <ul class="list list-payment" role="list">
            {% assign enabled_payment_types = 'visa,master,american_express,discover,diners_club,maestro,paypal,apple_pay,google_pay,ideal,jcb,klarna,sofort' | remove: ' ' | split: ',' %}
            {%- for type in enabled_payment_types -%}
              <li class="list-payment__item">
                {{ type | payment_type_svg_tag: class: 'icon icon--full-color' }}
              </li>
            {%- endfor -%}
          </ul>
        </div> 
```
<img width="963" alt="payment-methods" src="https://user-images.githubusercontent.com/51880555/177998509-f7acfb3b-47e1-4863-a286-50e08730be32.png">

In the meantime, I'll make the engineering team aware of this issue.

I presume this will solve your problem. So I am closing this ticket for now. Please do not hesitate to open it again if you have any questions.

Kind Regards
Viva Wallet Development Team

**Comment by jonsvarn** [comment] 2022-09-13 07:19
Hi, I was wondering if you were able to fix the issue with the payment icons. 

I have managed to place the icons manually to 3 shops but unfortunately i cant do this for every shop.

For instance i have a shop with the (paid) theme "Expanse" and (paid) theme "Testament" and the integration which shows automatically the payment icons does not work for viva payments. For other providers like paypal gateway or other providers works fine.

Can you please help me out and let me know how can i get support from viva on this.

Thanks in advance

**Comment by jonsvarn** [comment] 2022-09-15 12:45
@can3ry 
> Hi, I was wondering if you were able to fix the issue with the payment icons.
> 
> I have managed to place the icons manually to 3 shops but unfortunately i cant do this for every shop.
> 
> For instance i have a shop with the (paid) theme "Expanse" and (paid) theme "Testament" and the integration which shows automatically the payment icons does not work for viva payments. For other providers like paypal gateway or other providers works fine.
> 
> Can you please help me out and let me know how can i get support from viva on this.
> 
> Thanks in advance

**Comment by VivaWalletCustomerSupport** [comment] 2022-09-16 07:23
Hello @jonsvarn,

Thank you for your reply. So far we have not made any changes. Your suggestion is still under review for future implementations.

In any case, stay tuned for updates and changes.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by jonsvarn** [comment] 2022-09-19 09:05
@VivaWalletCustomerSupport  It's surprising that you closed this issue as "completed" again.
This issue is not a suggestion. It has to do with a core function of shopify. Most of the payment providers like mollie or paypal or stripe etc. depending on which payement services you wish to activate (mastercard, visa, amex etc.) display the icons of the activated services automatically on the footer of your shopify store. 
Once more this request is not a suggestion. This was functioning as usua without the need to edit the footer.liquid code and  since the viva plugin changed last june/july it just stopped working.
Please fix it or at least help us out with some personalized support  (code snippet)so that i can copy paste it to my store and make sure that will work without further customization.

**Comment by jonsvarn** [comment] 2022-09-21 06:27
@VivaWalletCustomerSupport  Hi i just tested as advised and removed the paypal gateway and i left only viva as an active payment gateway. Unfortunately there are no icons displayed on the footer. I am using Expanse theme (version 3.0.1) and i tested this with two more Shopify themes (Refresh & Dawn) and no payment icons are displayed. (The "display payment icons" option was activated on the themes i tested out) . So dont know what to do next. Contact shopify? Or do you want to take a look at it?

**Comment by VivaWalletCustomerSupport** [comment] 2022-09-21 08:19
Hello @jonsvarn,

As a first step try contacting Shopify to confirm or not where the issue is coming from, if this does not fix it we will review it again. Thanks in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment] 2022-09-21 09:28
@jonsvarn 

You can also check the links below as well to confirm what we mentioned for your own convenience.

- [Shopify help center](https://help.shopify.com/en/manual/online-store/themes/themes-by-shopify/vintage-themes/customizing-vintage-themes/add-credit-card-icons)
- [Shopify community](https://community.shopify.com/c/technical-q-a/payment-icons-in-footer-section-disappeared/td-p/1631393)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment] 2022-09-22 12:44
Hello @jonsvarn,

I just wanted to follow up on the reply I sent yesterday. I was simply wondering if you managed to contact Shopify. Are there any other questions, I may help you with?

In any case this conversation will remain active for at least 24 hours, so that you can come back if you wish.

I hope this information helps, however, should you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by jonsvarn** [comment] 2022-09-22 15:49
Hi @VivaWalletCustomerSupport  
Yes i have contacted shopify yesterday and they will investigate the issue and come back to me.
Thanks

**Comment by VivaWalletCustomerSupport** [comment] 2022-09-23 07:39
Good morning @jonsvarn,

Thank you for letting us know. Kindly keep us posted on any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment] 2022-09-28 12:37
Hello @jonsvarn,

I hope you are well and you are having a good week. Are there any updates on this? I will leave this communication active for 24 hours more for getting back to us.

Needless to say that should you have any other inquiries we are always here for you.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by jonsvarn** [comment] 2022-09-28 14:00
Hi @VivaWalletCustomerSupport 
Shopify tested the theme i am using along with a shopify theme and they were able to reproduce the same issue.
They will connect me with the developer team so that they can check whether they are receiving the necessary data from the gateway through Shopify in order to display the icons. And then i will get back to you. Please leave this open. Thanx

**Comment by VivaWalletCustomerSupport** [comment] 2022-09-30 14:21
Hello @jonsvarn,

Thank you for letting us know. Please keep us posted either way.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment] 2022-10-12 07:38
Hello @jonsvarn,

I hope you're doing well. Are there any updates on this? I will leave this communication active for 24 hours more for getting back to us if need be.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment] 2022-10-12 13:25
Welcome back @jonsvarn,

Thank you for letting us know. There is no need to forward us their official statement. I will close this case since the issue is not on our end. 

Of course, if we can be involved in any way you can let us know by mentioning us. 

I hope that the information I provided was useful and clarified the situation. Should you have any other questions, feel free to contact us again, as we are always here for you remaining at your disposal.

Kind regards,
Viva Wallet E-commerce Support Team

**Closed by VivaWalletCustomerSupport** 2022-10-12 13:25 UTC
