### ISSUE TITLE
Checkout issue 

### ISSUE THREAD

**Issue by Giourikch** [VivaPayments/API#1533] opened 2020-04-02 08:59 UTC
Hello. i have this problem while i put my card details in checkout and i get a message that Google is confirming the card. in the next step, instead of continuing with the payment, he returns me to the cart. Why is this happening; thanks

**Comment by matthewrgourd** [comment] 2020-04-02 10:26
Hi @Giourikch sorry to hear this. What is your website address and which of our [e-commerce plugins](https://developer.vivawallet.com/e-commerce-plugins/) are you using?

**Comment by Giourikch** [comment] 2020-04-02 10:30
Www.plussizexxxl.gr


Στις Πέμ, 2 Απρ 2020, 1:26 μ.μ. ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment] 2020-04-02 10:35
Hi @Giourikch, thanks. So I gather your website is on Wordpress and you're using WooCommerce. Can I check that you downloaded our official plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ ?

**Comment by Giourikch** [comment] 2020-04-02 11:35
Yes, it's the same.

Στις Πέμ, 2 Απρ 2020, 1:36 μ.μ. ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by Giourikch** [comment] 2020-04-03 09:18
Hello,

Something new about the problem I mentioned
Thank you

Στις Πέμ, 2 Απρ 2020, 1:36 μ.μ. ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment] 2020-04-03 09:54
Hi @Giourikch sorry, I can't see what you're referring to. Please respond to my last question (did you download our official plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ ?)

**Comment by Giourikch** [comment] 2020-04-03 10:01
Yes, it's the same.

Στις Παρ, 3 Απρ 2020, 12:54 μ.μ. ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by Giourikch** [comment] 2020-04-03 15:00
Can someone answer me?

Στις Παρ, 3 Απρ 2020, 12:54 μ.μ. ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment] 2020-04-03 15:04
Hi @Giourikch let me test

**Comment by matthewrgourd** [comment] 2020-04-03 15:07
Hi @Giourikch I see what you're saying. Not sure immediately what the problem is. Can you email me your Merchant ID so I can check your account? Reference this issue (#1533). Thanks!

**Comment by Giourikch** [comment] 2020-04-03 17:57
Στις Παρ, 3 Απρ 2020, 6:07 μ.μ. ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment] 2020-04-08 11:32
Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment] 2020-04-20 10:07
No reply so I'm closing the issue. Please respond with screenshots if this is still a problem. Thanks!

**Closed by matthewrgourd** 2020-04-20 10:07 UTC
Labels: e-commerce plugin
