### ISSUE TITLE
Bug ordini fantasma e login MAGENTO 2

### ISSUE THREAD

**Issue by Giacomo420** [VivaPayments/API#1874] opened 2020-09-24 09:40 UTC
Buongiorno,
Vi segnalo questi due bug che impediscono di lavorare correttamente e di far concludere le vendite. 
1. Quando un cliente arriva al checkout, è sufficiente che apra la pagina di redirect di Vivawallet per far registrare l'ordine, anche se in realtà non sono stati inseriti i dati della carta e l'ordine non è stato completato. 
Allo stesso tempo, anche se l'ordine viene completato nel backend rimane "Pending Payment" e non è possibile trasformarlo in "Processing" e poi "Complete", ne aggiungerlo alle vendite totali, nonostante venga fatturato e inserita la spedizione.

2. Problema più grave: quando un cliente prova ad effettuare il login, sia normalmente che dal check out, gli viene impedito e la pagina si ricarica. Specialmente nel secondo caso, una volta inseriti gli articoli nel carrello, effettuando l'accesso per completare l'ordine, la pagina si ricarica e il carrello si svuota, dando inizio ad un loop infinito. Si effettua l'accesso e il carrello si svuota, ergo l'ordine in questo modo non può essere completato nemmeno facendo miracoli.

Abbiamo urgente bisogno del vostro supporto perché tali problemi ci impediscono di vendere e quindi di lavorare
Grazie

**Comment by matthewrgourd** [comment] 2020-09-24 15:00
Hi @James420, am I correct in assuming you're using our plugin for Magento 2? Could I have the website address, please? If you see any orders in pending it means no payment has been taken. So the customer has abandoned the checkout process without submitting any card details.

**Comment by matthewrgourd** [comment] 2020-09-25 07:34
Hi @Giacomo420, I'm waiting for your reply to my query above. I need to check whether you're using our plugin for Magento 2? Also, what is your website address, please, so I can investigate further? Thanks!

**Comment by Giacomo420** [comment] 2020-09-25 07:48
Hi, yes i'm using the version Magento 2.3.4
www.hemport.it
I know what "Pending" means but what I'm saying is that it is a problem because the System read like the order was complete, so it change the quantity or products ecc.

**Comment by matthewrgourd** [comment] 2020-09-25 08:12
Hi @james420 @Giacomo420, could you send me a screenshot of your payment module settings in Magento? Blur out your merchant ID and API key. Thanks.

**Comment by matthewrgourd** [comment] 2020-09-25 09:08
Hi there, if you're unable to provide the screenshot, please check the following are enabled within the payment module:
```
MerchantID – your Viva Wallet Merchant ID
API Key – your Viva Wallet API Key
Source Code – 2992
OrderCode URL – https://www.vivapayments.com/api/orders
Gateway URL – https://www.vivapayments.com/web/newtransaction.aspx
Transaction URL – https://www.vivapayments.com/api/transactions
```

**Comment by Giacomo420** [comment] 2020-09-25 09:55
![Screenshot_20200924_174534_com android chrome](https://user-images.githubusercontent.com/71820345/94253695-f6572300-ff25-11ea-84bb-87bf7d9fafdd.jpg)

**Comment by matthewrgourd** [comment] 2020-09-25 11:05
Hi @Giacomo420 , thanks for sending that through. The settings look fine except the "Installments" field should be blank. Can you try again after removing the values?

**Comment by Giacomo420** [comment] 2020-09-25 11:43
Ok thanks now i try.. But this will solve the problem of log in or the other? Thanks

**Comment by matthewrgourd** [comment] 2020-09-25 12:32
Hi @Giacomo420, the problem I'm experiencing when I test is I can't see a payment link at all. I think maybe the best thing to do is disable / delete the plugin and reinstall from the below:

[magento23_vivawallet.zip](https://github.com/VivaPayments/API/files/5282740/magento23_vivawallet.zip)

I'm afraid I don't know what else to suggest. Let me know how you get on.

**Comment by Giacomo420** [comment] 2020-09-25 12:42
Excuse me in what sense do you not see it?
 The link is there, but to get there you need to have items in your cart, log in, enter your shipping details and then you get to the page where you can choose the payment option.
The problem is precisely that once logged in, the cart empties and you have to repeat all over again, in loop.

**Comment by Giacomo420** [comment] 2020-09-25 12:42
Comunque contatto il mio sviluppatore per reinstallarlo, grazie

**Comment by matthewrgourd** [comment] 2020-09-25 12:45
I added items to the cart but there was never an option to pay. I'm using Chrome.

**Comment by Giacomo420** [comment] 2020-09-25 13:24
This is precisely the problem! After placing the products in the cart, clicking "checkout" asks you to log in and then should lead you to enter the shipping and payment details. Instead the cart empties and you have to do it all over again! To enter the shipping and payment data you won't even get there!

**Comment by Giacomo420** [comment] 2020-09-25 13:27
And the problem is only from Chrome.
From Safari and Mozilla it works

**Comment by Giacomo420** [comment] 2020-09-25 13:41
But also from safari and Mozilla, if you complete the order correctly, from the backend is impossible to complete it. It remains on "Pending Payment" and you can't change it.

**Comment by matthewrgourd** [comment] 2020-09-25 13:54
Hi @Giacomo420 I've advised you to reinstall using the provided ZIP. Have you done that yet so we can retest?

**Comment by Giacomo420** [comment] 2020-09-25 14:03
No, because it seems to me that you have not fully understood what the problem is

**Comment by matthewrgourd** [comment] 2020-09-25 14:09
Hi @Giacomo420 it isn't working. I can confirm that. So please try what I suggest.

**Comment by Giacomo420** [comment] 2020-09-25 14:14
Ok, thanks. I don't if i can do it or i have to wait my developer

**Comment by Giacomo420** [comment] 2020-09-25 14:15
Ok thanks. If it is just download the zip and put it on the site I can try to do it, instead I have to wait my developer

**Comment by matthewrgourd** [comment] 2020-09-25 14:20
Yes, just remove our existing plugin and replace with this:

https://github.com/VivaPayments/API/files/5282740/magento23_vivawallet.zip

Same settings as before:
```
MerchantID – [your Viva Wallet Merchant ID]
API Key – [your Viva Wallet API Key]
Source Code – 2992
OrderCode URL – https://www.vivapayments.com/api/orders
Gateway URL – https://www.vivapayments.com/web/newtransaction.aspx
Transaction URL – https://www.vivapayments.com/api/transactions
Installments – [leave blank]
```

I'm sorry for the issues you've been experiencing. It may be that the previous plugin file was corrupted.

**Comment by Giacomo420** [comment] 2020-09-25 14:30
I don't know how to do it. I'm waiting that my developer reply to me

**Comment by Giacomo420** [comment] 2020-09-28 09:15
Good morning. The problem from Chrome was fixed with the new version installed. Thank you.
However, the other problem remains: when a customer enters your redirect page, the order arrives automatically on magento even if it has not been completed. It then remains blocked with the item "Pending Payment" which cannot be changed and at the same time the system erroneously changes the quantities of goods.
At the same time when someone places an order for real, it is not possible to change the "Pending Payment" option to the possible highs (Pending, Processing or Complete) and this is a problem because even if the order was placed correctly it is not You can add it to your total magento sales.

**Comment by Giacomo420** [comment] 2020-09-28 09:17
Excuse me for the last part of the message, *even if the ordsr was placed correctly, you can't add it on your total magento sales.

**Comment by Giacomo420** [comment] 2020-09-28 13:51
Hi, the problem from Chrome is back. How can i do?

**Comment by matthewrgourd** [comment] 2020-09-29 08:55
Hi @Giacomo420, I'm trying to place an order from Chrome now. I'll get back to you soon.

**Comment by matthewrgourd** [comment] 2020-09-29 09:06
Hi @Giacomo420, I just tried to buy something (with a card with no funds) and the plugin seems to be working correctly. Not exactly sure what your issue is. Can you try to explain further?

**Comment by Giacomo420** [comment] 2020-09-29 09:11
Good morning, yes now it seems to work. Yesterday there was the same problem of some days ago from Chrome

**Comment by Giacomo420** [comment] 2020-09-29 09:11
The other problem that I'm trying to explain from one week is simply, when a customer enters your redirect page, the order arrives automatically on magento even if it has not been completed. It then remains blocked with the item "Pending Payment" which cannot be changed and at the same time the system erroneously changes the quantities of goods.
At the same time when someone places an order for real, it is not possible to change the "Pending Payment" option to the possible highs (Pending, Processing or Complete) and this is a problem because even if the order was placed correctly it is not You can add it to your total magento sales.

**Comment by Giacomo420** [comment] 2020-09-29 09:15
This is for example a
![Screenshot_20200929_111317](https://user-images.githubusercontent.com/71820345/94539023-02542500-0245-11eb-8678-0260b973d6a8.jpg)
n order that we received and that was paid correctly. But from the backend i can't change this voice with processing (waiting to be ship) and then complete.

**Comment by matthewrgourd** [comment] 2020-09-29 09:21
Hi @Giacomo420, can you see one now for the order that I tried to place with a card with no funds? The amount was for 15.35. The **Pending payment** status will automatically change to **Cancelled** within 24 hours. You don't need to do anything with it manually.

**Comment by Giacomo420** [comment] 2020-09-29 09:56
Yes, for that one it works.
I'm talking about orders that were complete and paid!
The one that i send you on the photo was paid more than one week ago, but it remains on pending.

**Comment by matthewrgourd** [comment] 2020-09-29 10:16
Hi @Giacomo420 I can certainly check that one for you. Could I have the amount and customer name please? Also the date of the order...

**Comment by matthewrgourd** [comment] 2020-09-29 11:47
Hi @Giacomo420 unfortunately the screenshot doesn't show me any info. Please let me have some minimal order details so I can check. I need date and amount. This will enable me to troubleshoot. Please send details as soon as possible. I have another customer with a Magento plugin issue and yours may well be the same. Thanks and apologies for any inconvenience caused.

**Comment by Giacomo420** [comment] 2020-09-29 11:51
The order was made on 25 September. But what i'm saying again and again is that this problem happens with all orders correctly completed! 
If know i received an order correctly, it remains on pending payment even if i have received the payment. I don't know how to explain it anymore.

**Comment by Giacomo420** [comment] 2020-09-29 11:51
The order was made on 25 September. But what i'm saying again and again is that this problem happens with all orders correctly completed!
If now i received an order correctly, it remains on pending payment even if i have received the payment. I don't know how to explain it anymore.

**Comment by Giacomo420** [comment] 2020-09-29 11:53
The amount was 7,98 euros. But it happens with other amounts higher or smaller too.
It happened two week ago, like one week ago and like now if an order arrive.

**Comment by matthewrgourd** [comment] 2020-09-29 12:27
Hi @Giacomo420, you're correct when you say an order is always created, even if payment details aren't entered. We have no control over that, I'm afraid. It is the same for all e-commerce platforms. I can see one successful payment against your Viva Wallet account on 25 Sep for the amount of 7.98. This should have gone into "Completed" or "Processing" status when you received it. Obviously let me know if that is not the case. There are no other transactions showing on your account except the failed one from my test today. Every other example you mention is an abandoned cart which automatically creates an order in Magento with "Pending payment" status. I'm afraid this is the expected behaviour for Magento and cannot be changed. It is nothing to do with our plugin which is working correctly. I hope that clarifies things. Thanks.

**Comment by Giacomo420** [comment] 2020-09-29 12:55
It is what I'm saying!

**Comment by Giacomo420** [comment] 2020-09-29 12:56
That order is still pending payment, also another that was paid too.

**Comment by matthewrgourd** [comment] 2020-09-29 13:00
Hi @Giacomo420, not exactly, because there are no other successful transactions in our database apart from the one I mentioned for 7.98. So any 'orders' you see are abandoned carts which I've already explained cannot be anything other than pending payments in Magento (outside our control). They should end up cancelled automatically after 24 hours but I'm not 100% clear on the functionality. However, going back to the transaction for 7.98, that one you should be able to manually change to Completed as it is a paid order. Can you not do that?

**Comment by matthewrgourd** [comment] 2020-09-29 13:04
Correction: you have had two successful payments into your Viva Wallet account. The other one was for 2.50 on 15 Sep. Again, you should be able to change the status to Completed, I think.

**Comment by Giacomo420** [comment] 2020-09-29 13:19
If I could do it I would not be here .. I don't know how many times I am repeating the same thing: it is not possible to change the status of the order. It can only be canceled.
This happens both if the order has been completed and if it has been abandoned.

**Comment by Giacomo420** [comment] 2020-09-29 13:22
Again, this happens with any order, whether it has been paid for or has been abandoned.
Forget which specifics were paid and which were not. It happens with everyone.

**Comment by matthewrgourd** [comment] 2020-09-29 13:26
@Giacomo420, I'm sorry, but in order to be 100% sure, I needed the two examples of successful transactions against your Viva Wallet account. And you've now confirmed the related Magento orders exhibit the same behaviour as the abandoned carts. Thanks very much for that! I will pass on to our plugin developer and get back to you whenever I have an update.

**Comment by matthewrgourd** [comment] 2020-09-29 15:14
Hi @Giacomo420, plugin developer advises that you need to change the plugin configuration in Magento. The **New Order Status** setting should be amended to "Completed" or "Processing" depending on your preference. This will ensure that the order status isn't "Pending payment" for successful transactions. Hope this helps...

**Comment by Giacomo420** [comment] 2020-09-30 08:50
Good morning, just one question. If I change the plug in configuration, also the unsuccessful transactions will be marked complete or processing?
Some days ago i also try to change pending payments with "select an option" from the plug in configuration, but nothing change.

**Comment by Giacomo420** [comment] 2020-09-30 08:51
Tryed*

**Comment by matthewrgourd** [comment] 2020-09-30 09:51
Hi @Giacomo420 if you change the suggested setting the unsuccessful transactions (abandoned carts) will stay in **Pending payment** status until they're automatically cancelled after 24 hours. It is only the successful payments that will get marked as **Completed** or **Processing**.

**Comment by Giacomo420** [comment] 2020-10-05 08:34
Good morning, the problem is still there, i tried to modify the configuration but the problem remains

**Comment by Giacomo420** [comment] 2020-10-05 08:38
We have also discovered another problem:
If you have to pay on your gateway with a postepay card, that is a card from the visa or mastercard circuit of the Italian Post Office, there is only one way to approve the payment.
Let me explain: this type of card uses 3D secure and therefore to confirm the payment you must enter a code received by phone or approve the operation from the account app.
The problem is that on your gateway the only option that can be used is that of approval in the app which, in addition to being more inconvenient to use, also alienates many customers, since not everyone has the app installed on their mobile phone.
Let me know how we can resolve this..

**Comment by matthewrgourd** [comment] 2020-10-05 08:43
Hi @Giacomo420, (replying to your first query) you say it's still not working, but how many orders have you had in the last 5 days? What status are they showing in in Magento?

(Replying to your second query), there shouldn't be any issue receiving payment from the card you mention. 3DS works in whatever way is required by the issuer.

**Comment by Giacomo420** [comment] 2020-10-05 09:02
Past orders have remained pending. Those abandoned are not canceled. So I can say it doesn't work.

**Comment by Giacomo420** [comment] 2020-10-05 09:04
I didn't say there are reception problems. I said that there is no possibility to confirm payment via sms, only via the post office app.

**Comment by Giacomo420** [comment] 2020-10-05 09:05
The 3d secure of the circuit in question on your gateway is only possible via the app.

**Comment by matthewrgourd** [comment] 2020-10-05 09:07
Hi @Giacomo420 we don't handle the 3DS. This is done by the card issuer. So whatever method they use, this is what will be provided to the customer. As regarding the pending status, in that case, looks like maybe you have to manually change to cancelled. But you will know when a successful order comes through (with a payment) as it will come through as "Completed".

**Closed** 2020-10-08 14:14 UTC
Labels: e-commerce plugin
