### ISSUE TITLE
problem with woocommerce integration

### ISSUE THREAD

**Issue by jonijust** [VivaPayments/API#2051] opened 2020-12-09 17:06 UTC
Client id

5768095e-8f21-4c8d-8938-8e67e38ac673
--

source

8249

www.justcanapa.it
![vivawallet](https://user-images.githubusercontent.com/75747566/101661934-2acc7c80-3a49-11eb-97bf-0e43acc3a380.jpg)

Having problem with the woocommerce integration after i submit the payment i have no feedback and the page it's look like payment processing (see screenshot)

--

**Comment by matthewrgourd** [comment] 2020-12-09 17:19
Hi @jonijust, this is a plugin or theme issue. Conflicts caused by third-party plugins are a common cause of payment gateways not working. Try to disable all plugins except for WooCommerce and Viva Wallet. Third-party themes can also cause this, so another test is to swap to a different theme temporarily in case this makes a difference. Let me know how you get on...

**Comment by matthewrgourd** [comment] 2020-12-17 14:08
Closing as no reply.

**Closed by matthewrgourd** 2020-12-17 14:08 UTC
Labels: e-commerce plugin
