### ISSUE TITLE
Payments denied for 30% of my customers

### ISSUE THREAD

**Issue by AndreaVacca** [VivaPayments/API#1528] opened 2020-03-31 16:48 UTC
Vivawallet reject 30% of payments by my customers that complete a form and confirm a payment in my ecommerce. What is the problem? 

Check what is the problem please. Do a technical analysis please.

My data:
Viva wallet profile intestate to Weweed di Andrea Vacca,
Website E-commerce: www.Prodotti-cannabis.it (we use woocommerce)
Mail account viva wallet: Andrea.weweed@gmail.com
Let me Know please.

Best regarsds

**Comment by matthewrgourd** [comment] 2020-04-01 08:04
Hi @AndreaVacca, I've checked your account and the only 'rejections' I can see are from card issuers when customers' cards have insufficient funds. More than likely you are referring to payment failures with an error code returned by the issuer not by us. See below link to possible error codes returned by issuer:

https://developer.vivawallet.com/api-reference-guide/error-codes/#rejection-reasons

Hope this helps!

**Comment by AndreaVacca** [comment] 2020-04-01 17:18
Hello,

I've read your answer, but what you say does not correspond to many of the
cases reported by our customers.

It may be true that a part of costumers who are denied the payments does
not have enough money in the card and does not know it.

Bat we know for sure that many of our customers have money in their card
and their payments are still refused. Sometimes  happens that the screen
turns completely white and does not let complete the payment. This also
happens with customers who have activated the 3d secure procedure.
Attached a photo sent by one of our customers.

Can you specifically identify all the problems that have occurred and solve
them?  It's unlikely that all problems arise from the lack of money in
credit cards.

Please check again and let me know.

Thank you


Best regards






Il giorno mer 1 apr 2020 alle ore 10:05 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment] 2020-04-02 09:26
Hi @AndreaVacca if you give me specific dates and times of some failed transactions I can certainly check for you. However, our e-commerce plugin is guaranteed to be working properly if your customers have reached the 3DS popup.

**Comment by AndreaVacca** [comment] 2020-04-02 10:46
ok, thank you, what specific error data do you need to do a check? what
data do you refer to?

thank you

Il giorno gio 2 apr 2020 alle ore 11:26 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by AndreaVacca** [comment] 2020-04-06 09:19
Hello,
help us urgently!
In the last 24 hours ten payment went wrong or was refused by your
platform because
of your mistake!

This is the list of failed transactions in the last 23h, we are loosing a
lot of money. You absolutely must thoroughly check our account and remedy
the problem!

#2194 Salvatore Rindone 2 ore fa
#2193 Alessandro Mirabile 6 ore fa

#2192 Alessandro Mirabile 6 ore fa
#2183 Paola Chiaramonte 13 ore fa

#2176 ludovico dallai 15 ore fa

#2174 Salvatore Rindone 17 ore fa

#2173 STEFANO SCOMA 19 ore fa

#2171 STEFANO SCOMA 19 ore fa

#2170 Stefano Martinucci 20 ore fa
#2167 Salvatore Rindone 21 ore fa

Stefano Scoma, for example, he saw his payment denied twice. He says that
after entering the credit card details and confirming them, your page does
not load.
The screen stays as it is, and nothing else happens. It is no possible for
the customer to go ahead and he doesn't receive confirmation of payment.
And the payment is not processed by your platform. We lose the order and
are forced to cancel it.

We've lost more than 100 orders in less than a month since we started using
your platform. We need a fast solution!

Other customers complain that the message to enter the OTP code in the 3d
secure procedure arrives after hours.This is ridiculous and outrageous!
If it's your responsibility you must also check this aspect.

We trust in your will to resolve the problem as soon as possible.  Do a
thorough check please!
I thank you and whish you all the best in your work.

Weweed - Prodotti-cannabis.it

Il giorno gio 2 apr 2020 alle ore 11:26 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment] 2020-04-08 11:30
Hi @AndreaVacca I've already checked your account multiple times and the type of failures I'm seeing are all card issuer related. I can see plenty of successful transactions and everything seems to be working fine. I'm closing this issue now...

**Comment by AndreaVacca** [comment] 2020-04-09 15:42
I'm sorry but some of the customers who have had problems have for sure
money in their cards.
There are definitely some other problems. I report some examples below and
in the attached images:


#2296 Liridon Ramadani Apr 8, 2020
#2291 Liridon Ramadani Apr 8, 2020

This customer, yesterday, time: 20.08 and 20.09  and other two times try to
place an order that has been repeatedly rejected by viva wallet, as if he
had no money in the card. But he has the money in the card and in fact on
the fifth attempt he is accepted the payment. What do all these failures in
previous payments depend on? We have shown that the customer has the money
because he was able to pay then the error does not depend on him.
In the attached image you see an error given by your platform when the
customer sends his card data. The card is enabled for online payments and
has money inside. But your platform does not load and transaction failed.

We can list many other errors like these. What do they depend on? You have
to solve them as soon as possible.
Confident of your interventio I wish you good work




[image: image.png]


Il giorno mer 8 apr 2020 alle ore 13:30 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment] 2020-04-15 10:49
Hi @AndreaVacca sorry not to come back to you before. I closed the other ticket so that there isn't a duplicate. I appreciate that what you're telling me may well need investigating. Can you try to resend the screenshots you tried sending before as I couldn't see them? Maybe send direct to my email if you have a problem again on GitHub being able to do this.

**Comment by matthewrgourd** [comment] 2020-04-21 15:30
Hi @AndreaVacca I've checked a few of those transactions and it would appear that they're not registered in your list of sales transactions. The most likely reason for this is the customers failed their 3DS which is not handled by Viva Wallet but the card issuer. You will always have a few of these. Other than that, your account looks healthy with hundreds of successful transactions. I can confirm that there is no outstanding problem. Please close this issue when you have a spare moment. Thanks!

**Closed** 2020-04-22 13:27 UTC
Labels: e-commerce plugin
