### ISSUE TITLE
OpenCart transaction failed with CC test card + default Greece characters

### ISSUE THREAD

**Issue by mediageni** [VivaPayments/API#2055] opened 2020-12-11 10:42 UTC
Hi we're having troubles testing the CC checkout.
https://developer.vivawallet.com/getting-started/#test-card

Issue 1
When trying to checkout with the Test Card 5511070000000020
We also get an error
https://domain.com/index.php?route=extension/payment/vivawallet/callback&fail&t=XXXXX&s=XXXXX&lang=en-US&eventId=10014&eci=3

The transaction failed or has been cancelled!
Please wait...
If you are not automatically re-directed in 10 seconds, please click here.

Issue 2
By default it sometimes shows characters from Greece.
Περιγραφή χρέωσης
https://www.vivapayments.com/web/newtransaction.aspx

**Comment by matthewrgourd** [comment] 2020-12-11 11:18
Hi @mediageni, sorry to hear this. 

Regarding 1, I believe for our [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) to work correctly, you need to have an actual live domain configured in the [payment source](https://developer.vivawallet.com/online-checkouts/create-a-payment-source-redirect-checkout/) used to receive transactions.

Regarding 2, we seem to have an intermittent issue at the moment with our redirect checkout defaulting to the Greek language (EL). Is that what you're finding?

Thanks.

**Comment by mediageni** [comment] 2020-12-11 11:25
Thanks for the reply

1) Actually we have already an Edit Payment Source: Website/Mobile App configured. However, we are using the TEST creditcard. Is the problem caused by the Test Creditcard?  

2) Yes, default it's greek.

**Comment by matthewrgourd** [comment] 2020-12-11 11:54
Hi @mediageni, what domain are you testing on? Can I have your Merchant ID, VAT number or Company Registration so I can find you on our systems.

**Comment by mediageni** [comment] 2020-12-11 11:58
https://dutchnaturalhealing.theshopbuilders.com
Account ID 2041810572
The site ID is 1899 (sourcename DutchNaturalHealing.com TESTOMGEVING)
Pater Zen Producties B.V.

**Comment by matthewrgourd** [comment] 2020-12-11 12:05
Hi @mediageni, thanks for confirming those details which I'm hiding from GitHub now for security reasons. Are you using Zen Cart for dutchnaturalhealing.theshopbuilders.com ? Have you installed our [Zen Cart redirect plugin](https://developer.vivawallet.com/e-commerce-plugins/zencart/)?

**Comment by mediageni** [comment] 2020-12-11 12:23
Hi Matthew, ok glad you hide this info :)

We are using OpenCart 3.0
https://developer.vivawallet.com/e-commerce-plugins/opencart3/ on our
Staging site https://dutchnaturalhealing.theshopbuilders.com/ (this will
become https://dutchnaturalhealing.com/ in januari.


   - Success URL –
   index.php?route=extension/payment/vivawallet/callback&success
   - Failure URL –
   index.php?route=extension/payment/vivawallet/callback&fail



On our live site we are using OpenCart 1.5X Vivawallet, that one is working
on LIVE
http://dutchnaturalhealing.com/


Regards
Vidal

**Comment by matthewrgourd** [comment] 2020-12-11 12:58
Hi @mediageni, site has to be live to test. Please let me know if you want to enable dutchnaturalhealing.theshopbuilders.com for me to check what the issue is.

**Comment by mediageni** [comment] 2020-12-11 13:01
I thought dutchnaturalhealing.theshopbuilders.com was already live on your
side?

We will also remove the password protection from staging site.

Regards
Vidal

**Comment by matthewrgourd** [comment] 2020-12-11 13:25
@mediageni the payment source, yes, but you mentioned that you had done a test and got an error (issue1). Please can you let me know how to recreate that error. If the error relates to a test payment you made via dutchnaturalhealing.theshopbuilders.com then you need to make that website live briefly and give me a test product to purchase.

**Comment by mediageni** [comment] 2020-12-11 14:33
Hi Matthew,

Ok I removed the maintenance mode from the test-environment
https://dutchnaturalhealing.theshopbuilders.com/

Just do a guest order and use any product.
[image: image.png]

I used this
[image: image.png]
and will fail here....
https://dutchnaturalhealing.theshopbuilders.com/index.php?route=extension/payment/vivawallet/callback&fail



Kind regards
Vidal

**Comment by matthewrgourd** [comment] 2020-12-11 14:47
hi @mediageni, thanks for sharing all that info. I've made a test purchase (with a card with no funds) and can confirm that our checkout is working fine. My card was rejected because it has no funds and I got the same error as you. If I had used a working card, I would have got the success message. The card you used was the test card which is only meant for use when working with a demo Viva Wallet account. Hope this helps!

**Comment by mediageni** [comment] 2020-12-11 14:56
Hi Matthew,

Ahhhhhh I see. The test card is only for demo accounts.

So for instance If we want to go live to www.dutchnaturalhealing.com . I
only have to change the
[image: image.png]
Domain Name to www.dutchnaturalhealing.com ?



Kind regards
Vidal

**Comment by matthewrgourd** [comment] 2020-12-11 15:10
Hi @mediageni, I believe so but I couldn't see your screenshot. By the way, the other issue with Greek language being displayed by mistake should be fixed now.

**Comment by mediageni** [comment] 2020-12-11 15:15
Ok thanks, here is the screenshot. The place where you add the domain
name of the site.
[image: Untitled 4.png]

**Comment by matthewrgourd** [comment] 2020-12-11 15:26
I still can't see the screenshot I'm afraid!

**Comment by mediageni** [comment] 2020-12-11 15:47
So when we go live I click the property 1899 in

Websites/Apps > and I change the Domain Name to the live domain
www.dutchnaturalhealing.com

For the current live site we use 4774 but that has a different success and
fail url. So therefore we created the above 1899 for dev purposes...

**Closed** 2020-12-14 14:01 UTC
Labels: redirect checkout
