### ISSUE TITLE
Simple checkout 3DS doesn't work 

### ISSUE THREAD

**Issue by IleaBrussels** [VivaPayments/API#1978] opened 2020-11-08 17:18 UTC
Hello,

In the demo Simple checkout the 3DS popup window doesn't open anymore since few days. Could you please check?

**Comment by matthewrgourd** [comment] 2020-11-09 08:48
Hi @IleaBrussels, we disabled it temporarily while we look into an issue. I'll let you know once there's an update.

**Comment by matthewrgourd** [comment] 2020-11-10 10:18
@IleaBrussels, FYI, I'm told that any tests on demo will give the outcome of "authenticated" by default currently. The fact that we're temporarily disabled the 3DS simulator shouldn't affect anything that you're attempting, but obviously let me know if any further issues...

**Comment by IleaBrussels** [comment] 2020-11-10 18:33
Hi,It is not clear how to test negative scenarios and reaction of my website on them, e.g. when 3DS check fails or the balance is insufficient. It is not clear what Viva wallet will do in such the cases.
Other payment systems, e.g. Ogone in Belgium provide clear specifications for negative cases as well as a separate card number to test them.
It looks like to have a clear understanding I have to connect to the production environment and test with my own cards providing wrong 3DS data or making an order with an amount bigger than I have on my account. I can do that but I can't ask my developer test with his own cards when he works on the  website, nor I want to give him my card details.Can you suggest a better workaround?

Отправлено из Yahoo Почты для Android 
 
  вт, 10 нояб. 2020 в 11:18 matthewrgourd<notifications@github.com> написал(-а):   


@IleaBrussels, FYI, I'm told that any tests on demo will give the outcome of "authenticated" by default currently. The fact that we're temporarily disabled the 3DS simulator shouldn't affect anything that you're attempting, but obviously let me know if any further issues...

**Comment by matthewrgourd** [comment] 2020-11-11 10:17
Hi @IleaBrussels, unfortunately, at the moment you cannot check negative scenarios because of the fact that we're working on fixing the 3DS emulator on demo. I'm sorry for any inconvenience caused. If your developer also has access to your Viva Wallet account then making a real payment with his card could be a workaround as he can then immediately cancel the payment from within the banking app:

![cancel-payment](https://user-images.githubusercontent.com/44943019/98799496-19bb2c00-2407-11eb-8c65-039c7c29e4e1.png)

However, I know this isn't ideal, so I will ask when the fix in demo is due and update you as soon as possible. Thanks!

**Comment by matthewrgourd** [comment] 2020-11-24 09:05
Duplicate of #1961

**Closed by matthewrgourd** 2020-11-24 09:05 UTC
Labels: Simple Checkout
