### ISSUE TITLE
mastercard e visa

### ISSUE THREAD

**Issue by justmary123** [VivaPayments/API#1514] opened 2020-03-27 16:50 UTC
hi, we are experiencing major payment problems with Mastercard and Visa, please check. not being able to receive payments on Shopify

**Comment by unclemuzy** [comment] 2020-03-27 22:13
we're experiencing the same problem on our site - see https://github.com/VivaPayments/API/issues/1506 for reference in case any future comments are of assistance.

**Comment by matthewrgourd** [comment] 2020-03-30 14:39
Duplicate of #1511

**Closed by matthewrgourd** 2020-03-30 14:39 UTC
Labels: shopify
