### ISSUE TITLE
500 error in demo.vivapayments.com/web/checkout/getpaymenttoken

### ISSUE THREAD

**Issue by bilaridis** [VivaPayments/API#2084] opened 2021-01-01 19:40 UTC
What did I do wrong ?
I follow all step but everytime I took this error !!!!!

![image](https://user-images.githubusercontent.com/11517376/103445233-49a1e580-4c7a-11eb-94be-0d21b5385823.png)

**Comment by matthewrgourd** [comment] 2021-01-04 09:00
Hi @bilaridis, I must apologise. There is an issue with the current demo card which I will need to investigate with our development team. I'll update you as soon as I know more. 
Duplicate of #2080

**Comment by matthewrgourd** [comment] 2021-01-08 13:20
Hi @bilaridis, I have an update for you: the 3DS simulator is provided by Modirum, a third-party company we use. The problem is on their side and unfortunately I currently don't have an ETA for a fix. In the meantime you can use the below cards to simulate successful / unsuccessful outcomes. These bypass the popup and are therefore the equivalent of frictionless transactions:

Long card number | Issuer | CVC | Expiry date | 3DS outcome
-- | -- | -- | -- | --
5188340000000011 | Mastercard | Any 3 digits | Any future date | Success
4016360000000010 | Visa | Any 3 digits | Any future date | Success
5188340000000029 | Mastercard | Any 3 digits | Any future date | Not authenticated
4016360000000028 | Visa | Any 3 digits | Any future date | Not authenticated

Hope this helps!

**Closed** 2021-01-08 15:02 UTC
Labels: demo environment, developer
