### ISSUE TITLE
Native Checkout v2 Demo problems

### ISSUE THREAD

**Issue by spsof** [VivaPayments/API#1340] opened 2020-01-29 17:32 UTC
Hi. I'm following every guide step-by-step and still I can't get a valid transaction.
First problem is that even if I have included the demo JS script and specifically set the baseUrl to 'https://demo-api.vivapayments.com/' in my VivaPayments.cards.setup block, the requested Url to /chargetokens is towards the production server.

![image](https://user-images.githubusercontent.com/45595648/73379894-c2126080-42cb-11ea-9de3-b6f470a455df.png)

I have to manually edit the request url to demo-api.vivapayments.com and resend in order to get the charge token.

![image](https://user-images.githubusercontent.com/45595648/73380032-fe45c100-42cb-11ea-9980-02eee6ff4a92.png)

After I, again, manually set the charge token I can proceed to the next steps.
When I finally try to POST to https://demo-api.vivapayments.com/nativecheckout/v2/transactions in order to make the actual charge, I keep getting error 400: Bad Request with the following message:
"{\"status\":400,\"message\":\"PaymentsCardHolderAuthenticationInvalidStatus\",\"eventId\":\"2061\"}"

I have to also say that I am attempting the charge using the 4016000000040000012/111 info, you proposed in https://github.com/VivaPayments/API/issues/1311#issuecomment-579708540 but no 3DS popup is ever being displayed.

**Comment by matthewrgourd** [comment] 2020-01-30 12:19
Hi @spsof , sorry to hear you're experiencing issues. Thanks for pointing out that the demo JS had the wrong baseURL reference. I've added a note in the documentation that this needs to be amended when testing in the demo environment.

Regarding the error message, this is expected behaviour as no 3DS authentication has been completed at the issuer end. To mimic a successful outcome, do the following:

1. Cut and paste the below into a text editor and save as an HTML file:

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Native 3DS test</title>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://demo.vivapayments.com/web/checkout/v2/js"></script>
</head>

<body>

    <form action="" method="POST" id="payment-form">
        <div class="form-row">
            <label>
                <span>Cardholder Name</span>
                <input type="text" size="20" name="txtCardHolder" autocomplete="off" data-vp="cardholder"
                    value="Joe Blogs" />
            </label>
        </div>

        <div class="form-row">
            <label>
                <span>Card Number</span>
                <input type="text" size="20" name="txtCardNumber" autocomplete="off" data-vp="cardnumber"
                    value="4016000000040000012" />
            </label>
        </div>

        <div class="form-row">
            <label>
                <span>CVV</span>
                <input type="text" name="txtCVV" size="4" autocomplete="off" data-vp="cvv" value="111" />
            </label>
        </div>

        <div class="form-row">
            <label>
                <span>Expiration (MM/YYYY)</span>
                <input type="text" size="2" name="txtMonth" autocomplete="off" data-vp="month" value="1" />
            </label>
            <span> / </span>
            <input type="text" size="4" name="txtYear" autocomplete="off" data-vp="year" value="2020" />
        </div>


        <button type="button" id="submit" (click)="submit($event)">Submit Payment</button>
    </form>

    <div id="threed-pane" style="height: 450px;width:500px">

    </div>



    <script type="text/javascript">
        $(document).ready(function () {

            const baseUrl = 'https://demo-api.vivapayments.com';

            VivaPayments.cards.setup({
                baseURL: baseUrl,
                authToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6IkpXVCIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCJ9.eyJuYmYiOjE1ODAzODU5MTIsImV4cCI6MTU4MDM4OTUxMiwiaXNzIjoiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJhdWQiOlsiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIiwiY29yZV9hcGkiXSwiY2xpZW50X2lkIjoiODl1bzFiZHR4dWI2OGRjbDkwYm5mZGJyMDFjOWZndW11cWF4NTAxbTlpODM1LmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiJGQkYxRTA5MC02NURFLTRDNzUtQjU4MC1EOUQ5QkM0OTRBRDIiLCJzY29wZSI6WyJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmciLCJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmc6Y2FyZHM6dG9rZW5zIiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6bmF0aXZlY2hlY2tvdXR2MiJdfQ.oCfxPgm3b43RR_4SHQwDMqOLa8HSvFZbiJkTxc0niYyOFYlZG9awKYkx1gYO2WleEmMN-ftavHizwzebIQSKg6F9m4TZlmDHEnP-hvj0X8zLVYWRWNzqYbG5t9GrbutAN-JNVuGybc_zJGUk8iwfKkXWHvh6ZRAE1c7zZUPXkWH1xjf5wOjZ1ve90iYzhMqzUVM3pXpXw4Bn9AJ8VNe7pJGQluhXG9eLqp8crRbdavWpSFujLu65KzPYHbK7r7oYIZVgssXWADYxLhjUvCSsQbwoTtAj1eimqC9v1K0SvATXyZM3nhLRiUe_N0vrvyyHTMEZ3XKUTOaPgIVoYsvMHw',
                cardHolderAuthOptions: {
                    cardHolderAuthPlaceholderId: 'threed-pane',
                    cardHolderAuthInitiated: function () {
                        $('#threed-pane').show();
                    },
                    cardHolderAuthFinished: function () {
                        $('#threed-pane').hide();
                    }
                },
                installmentsHandler: function (response) {
                    if (!response.Error) {
                        if (response.MaxInstallments == 0)
                            return;
                        $('#drpInstallments').show();
                        for (i = 1; i <= response.MaxInstallments; i++) {
                            $('#drpInstallments').append($("<option>").val(i).text(i));
                        }
                    }
                    else {
                        alert(response.Error);
                    }
                }
            });

            $('#submit').on('click', function (evt) {
                evt.preventDefault();
                VivaPayments.cards.requestToken({
                    amount: 3600
                }).done(function (data) {
                    console.log(data);
                    alert(data.chargeToken);
                });
            });

        });
    </script>
</body>

</html>
```
2. Open the file in a browser to display the following output:

![Screenshot 2020-01-30 at 12 08 27](https://user-images.githubusercontent.com/44943019/73448669-465ef500-4359-11ea-9a16-45e7be9b055a.png)

3. Click on the **Submit Payment** button to display a simulation of a 3DS authentication window:

![Screenshot 2020-01-30 at 12 09 41](https://user-images.githubusercontent.com/44943019/73448818-a3f34180-4359-11ea-8d00-3e7c411d3386.png)

4. Ensure **Success** is selected from the dropdown and click on the **Confirm payment** button.

5. A popup is displayed with a one-time charge token.

6. Use the charge token to make the actual charge on demo, for example:
```
curl -X POST \
  https://demo-api.vivapayments.com/nativecheckout/v2/transactions \
  -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6IkpXVCIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCJ9.eyJuYmYiOjE1ODAzODU5MTIsImV4cCI6MTU4MDM4OTUxMiwiaXNzIjoiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJhdWQiOlsiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIiwiY29yZV9hcGkiXSwiY2xpZW50X2lkIjoiODl1bzFiZHR4dWI2OGRjbDkwYm5mZGJyMDFjOWZndW11cWF4NTAxbTlpODM1LmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiJGQkYxRTA5MC02NURFLTRDNzUtQjU4MC1EOUQ5QkM0OTRBRDIiLCJzY29wZSI6WyJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmciLCJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmc6Y2FyZHM6dG9rZW5zIiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6bmF0aXZlY2hlY2tvdXR2MiJdfQ.oCfxPgm3b43RR_4SHQwDMqOLa8HSvFZbiJkTxc0niYyOFYlZG9awKYkx1gYO2WleEmMN-ftavHizwzebIQSKg6F9m4TZlmDHEnP-hvj0X8zLVYWRWNzqYbG5t9GrbutAN-JNVuGybc_zJGUk8iwfKkXWHvh6ZRAE1c7zZUPXkWH1xjf5wOjZ1ve90iYzhMqzUVM3pXpXw4Bn9AJ8VNe7pJGQluhXG9eLqp8crRbdavWpSFujLu65KzPYHbK7r7oYIZVgssXWADYxLhjUvCSsQbwoTtAj1eimqC9v1K0SvATXyZM3nhLRiUe_N0vrvyyHTMEZ3XKUTOaPgIVoYsvMHw' \
  -d '{
  "amount": 100,
  "preauth": false,
  "sourceCode": "9158",
  "chargeToken": "ctok_FTJ2uZuidJ12MzECufOJhtQMMLk",
  "Installments": 1,
  "merchantTrns": "Merchant transaction reference",
  "customerTrns": "Description that the customer sees",
  "currencyCode": 826,
  "customer": {
	  "email": "native@vivawallet.com",
	  "phone": "442037347770",
	  "fullname": "John Smith",
	  "requestLang": "en",
	  "countryCode": "GB"
   }
}'
```

You should now get a 200 response with a transaction code.

>Note that the code sample above includes a time-limited access token which expires after one hour. You should replace with your own if it stops working.

**Comment by spsof** [comment] 2020-01-30 17:22
Thank you @matthewrgourd for your example. I did quite a few attempts, but sadly I have never received a successful transaction.

Specifically, with the provided example, following your steps exactly, I got:
`{"status":502,"message":"Transaction failed","eventId":"10051"}`
Is there a reference of those event IDs?

Afterwards, I set the authenticateCardholder option to false (and used initially the card number from your example, as well as the 4111111111111111 one) and I got again every time:
`{"status":400,"message":"PaymentsCardHolderAuthenticationInvalidStatus","eventId":"2061"}`
Shouldn't the authenticateCardholder option when set to false, bypass the "Invalid Authentication" error?

**Comment by teokal** [comment] 2020-01-31 02:35
Thank you @matthewrgourd. Your example really did help me getting this to close to fully work.

**Current State:**
Test Env: Works but does not trigger 3DS.
Staging Env: Triggers 3DS, so it doesn't work. 

**Test Env**
The only test card that seems to work is `CardNo: 4111111111111111 / CVV: 111`, though it will never trigger the 3DS window, as call from requestToken will always return `redirectToACSForm: null`.

Setting `authenticateCardholder: false` will result to the following error:
![image](https://user-images.githubusercontent.com/11727192/73507002-1c9ce100-43e0-11ea-86c1-8871498347d2.png)
and thus the transaction will not get initialized.

Trying other test cards on demo environment will result to:
`{"status"=>502, "message"=>"Transaction failed", "eventId"=>"10051"}`.

**Staging Env**
On our staging environment, we tried some of our cards. They triggered the 3DS (there is html page on `redirectToACSForm`), but the window (`#threed-pane`) did not show up and got this error:
![image](https://user-images.githubusercontent.com/11727192/73507664-55d65080-43e2-11ea-83d6-75f17c066636.png)

It is literally as in your example:
```html
    <div id="threed-pane" style="height: 450px;width:500px">
    </div>
```
```js
                cardHolderAuthOptions: {
                    cardHolderAuthPlaceholderId: 'threed-pane',
                    cardHolderAuthInitiated: function () {
                        $('#threed-pane').show();
                    },
                    cardHolderAuthFinished: function () {
                        $('#threed-pane').hide();
                    }
                },
```

Do we have to append the `redirectToACSForm` content on `#threed-pane` or it should be automatically triggered/shown?

**Comment by matthewrgourd** [comment] 2020-01-31 10:44
Hi @spsof and @teokal, thanks for the updates. For answers, I'm going to need to consult with our dev team and get back to you. Will let you know as soon as!

**Comment by matthewrgourd** [comment] 2020-02-04 13:47
Hi @teokal, I've received a reply from our dev team. I hope this will help:

`redirectToACSForm` will be shown automatically if you're using our JavaScript file.

Http calls to `chargetokens:skipauth` will always result in 403 forbidden so only set `authenticateCardholder` to true.

And finally, the below error identifies that threed-pane is not rendered when `requestToken` is called. It depends on your implementation.

https://user-images.githubusercontent.com/11727192/73507664-55d65080-43e2-11ea-83d6-75f17c066636.png

**Comment by spsof** [comment] 2020-02-04 16:57
@teokal I'm not sure why you thought it is a good idea to hijack issues like that.
@matthewrgourd The funny thing is that you decided to answer to the hijacker instead of the one who opened the issue. Would you be so kind @matthewrgourd and answer my question https://github.com/VivaPayments/API/issues/1340#issuecomment-580362422 ? Thanks.

**Comment by matthewrgourd** [comment] 2020-02-05 11:31
Hi @spsof `authenticateCardholder` should always be set to true as all merchants are obliged to carry out 3DS authentication of their customers due to the PSD2 legislation. The reason you're receiving `{"status":400,"message":"PaymentsCardHolderAuthenticationInvalidStatus","eventId":"2061"}` as a response is because there is no authentication being carried out. This is correct behaviour. If you want to mimic a successful authentication I've given you the code for this in https://github.com/VivaPayments/API/issues/1340#issuecomment-580227152

**Comment by matthewrgourd** [comment] 2020-02-06 09:25
@spsof @teokal I've got some new information for you. To simulate a successful payment on the demo environment, use the 19-digit test card number **4016000000040000012** with any valid date in the future and **111** for the CVV2. I'm sorry I didn't give you this earlier but I've only just found out from our dev team!

**Comment by matthewrgourd** [comment] 2020-02-14 10:22
Closing this issue now as not had any further updates.

**Comment by spsof** [comment] 2020-02-24 20:10
I still can't get a complete transaction going using the demo environment since the /chargetokens request is still happening towards the api.vivapayments.com instead of the demo-api.vivapayments.com, even if I have the demo js loaded and the baseUrl pointing to the demo one.
That way, I can't get the 3DS popup to open, so any attempt later to POST to the /transactions endpoint gets the same result (502: Transaction failed).
Any chance we could also set the baseUrl to the VivaPayments.cards.requestToken() block?

**Comment by spsof** [comment] 2020-02-26 17:28
@matthewrgourd This is literally the snippet of source code I'm using:
```
const vivaUrl = 'https://demo-api.vivapayments.com/';

VivaPayments.cards.setup({
	authToken: 'my_auth_token',
	baseUrl: vivaUrl,
	cardHolderAuthOptions: {
		cardHolderAuthPlaceholderId: 'threed-pane',
		cardHolderAuthInitiated: function () {
			$('#threed-pane').show();
		},
		cardHolderAuthFinished: function () {
			$('#threed-pane').hide();
		}
	}
});

submitButton.on('click', function (e) {
	e.preventDefault();
	VivaPayments.cards.requestToken({
		amount: 1000
	}).done((response) => {
		//console.log("Charge token: " + response.chargeToken);
		submitButton.click();
	});
});
```

As I already mentioned multiple times (sorry for that), the first block performs the request against the demo-api server correctly, while the second one, when I click the submit button, fails towards the production server.
I'm not sure what I'm missing here, but there is definitely no progress on this.

**Comment by matthewrgourd** [comment] 2020-02-27 10:09
Hi @spsof I think this may be because https://demo.vivapayments.com/web/checkout/v2/js contains the wrong base URL. I raised with our dev team but it looks like they've not changed it. You'll need to host / call this file locally after replacing the text `f={baseURL:"https://api.vivapayments.com"` with `f={baseURL:"https://demo-api.vivapayments.com"`

**Comment by spsof** [comment] 2020-02-27 16:17
@matthewrgourd Thank you! I can't believe it was declared inside the JS all this time...
Indeed, that solved my issue with the demo-api server.
Just a small feedback on the latest test card you provided: I kept getting a "Bad Gateway" as a return status code, after POSTing to "/nativecheckout/v2/transactions", with that 19-digit card, but when I tried the 4111111111111111 one, it worked right away! With the 3DS popup and all. Maybe it will help someone who faces the same issue.

**Comment by teokal** [comment] 2020-02-27 16:42
To add some more info on @spsof reply:
On our demo environment:
- 4016000000040000012 - won't work at all getting `{"status"=>502, "message"=>"Transaction failed", "eventId"=>"10051"}`
- 4111111111111111 - will work, not triggering 3DS though.

On our production environment, things are running smoothly.

**Comment by matthewrgourd** [comment] 2020-02-28 09:33
Hi @spsof glad it's working now. Thanks for the feedback, will look into that!

**Comment by matthewrgourd** [comment] 2020-02-28 09:33
Hi @teokal thanks for the feedback which I will take on board in the docs!

**Closed** 2020-02-28 16:14 UTC
Labels: native checkout v2
