### ISSUE TITLE
Several Issues with of Viva Wallet to my business website

### ISSUE THREAD

**Issue by lakelandcbd** [VivaPayments/API#683] opened 2019-01-04 13:33 UTC
We have recently installed Viva Payments and have several issues. 

1. After making payment - customers are not redirected to our thank you page or main website page.
2. The receipt they receive is in Greek with no option to change to english.
3. WooCommerce is not being updated to show an order processing when the order is complete. If we do not manually change the order within a certain time limit the order then cancels itself.

Can someone please contact me about this immediately. Viva have no clue how to help and this is severely affecting my business

**Comment by VivaWalletSupport** [comment] 2019-01-04 13:51
Hello, could you post a link to what plugin is used for your store?

**Comment by lakelandcbd** [comment] 2019-01-04 13:53
https://www.enartia.com/

**Comment by VivaWalletSupport** [comment] 2019-01-04 14:02
In that case I would suggest to contact the developer for support, otherwise you might have to wait a long time before someone who knows this plugin can provide you with an answer. Another option is to use the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress

**Comment by lakelandcbd** [comment] 2019-01-07 11:23
My developer has tried to use the supported plug in, but there is no zip file to download as stated in the instructions.... 

I would also point out, that Wetransact & Viva Payments are advertising this service as a payment gateway to companies. most of us that are having issues aren't technical, and the links and instructions you are giving out aren't helpful as we don't know what to do with the information.

We still have the same original problems that we had, and they are getting worse. 

Who's responsibility is it to ensure that the payment integration is seamless? Viva's or yours?

**Comment by VivaWalletSupport** [comment] 2019-01-07 14:05
Hello, I would recommend your developer to get familiair with Github and how to extract / update files from that platform. 

Also read the instructions carefully as it does not mention that a zipped file can be downloaded, but for your convenience you can take it from here: 
[vivawallet-for-woocommerce.zip](https://github.com/VivaPayments/API/files/2732964/vivawallet-for-woocommerce.zip)

I would appreciate it in case you can inform me what specific instructions and links that I gave are not clear, it might be helpfull for the future.

My specific task is providing support for the payment plugins that are available on this platform.

**Comment by lakelandcbd** [comment] 2019-01-07 14:31
Thank you for the link, it's very much appreciated!

What I am trying to explain is that we are a small company, we don't have a developer, I have very basic skills and have a very basic website. I am not a coder nor do I understand Github and how it works. 

This however is not your fault, BUT Viva Payments/WeTransact are directing us to you for support with integration with plugins and code etc. with the understanding that you can help fix the basic problems

The instructions you are giving out are instructions someone with knowledge of github and coding they probably are clear but for someone who doesn't understand code they aren't helping me fix any problems. 

Does that make sense?

Nic

**Comment by kostGX** [comment] 2019-01-07 14:43
@lakelandcbd this is the zip file that contains all code examples and plug ins: 
https://github.com/VivaPayments/API/archive/master.zip 

The most updated version will always live in this link which is accessible from here: https://github.com/VivaPayments/API (via Clone or Download button)

Regarding the receipts being in Greek, you need to confirm that your Preferred language setting is set to English as in the image below:

![preferred language](https://user-images.githubusercontent.com/3908736/50774099-4fd37600-129b-11e9-8956-7c889a42c0de.jpg)

**Comment by VivaWalletSupport** [comment] 2019-01-07 14:46
No problem Nic, in your previous post you mentioned that your developer had a problem with getting the supported plugin, so I assumed some knowledge should be there. Besides using Git you can also download the whole project as a zipped package from the projects main page (clone or download button) and remove everything that is not needed from the zipped package, or copy the code from each file to a local file and zip it as a package according the readme.txt

Let me know in case you have any issues with the supported plugin or in case it is not clear in the readme file on how to properly connect your store with the viva wallet payment source.

**Comment by lakelandcbd** [comment] 2019-01-07 16:47
Guys thank you so much for your patience and help, it really is appreciated.

So I have tried to install the plug in and it seems to be working, however there a couple of glitches....

1. When a customer places an order its is showing up in wordpress but then after 2 hours it is automatically showing as "cancelled" and sending an email to the customer stating this even though payment has been made. 

2. Two payments made through the website have no yet shown up on our Viva Dashboard 

3. On the payment portal there is a phone number showing asking for customers to ring to pay over the phone?

Any help with this would be appreciated

Nic

**Comment by lakelandcbd** [comment] 2019-01-07 16:48
oh sorry... Also...

When the payment has been completed the customer is redirected to a page on our website with the error 404 - but a thank you page has been created and info input into settings to redirect to this page

![image](https://user-images.githubusercontent.com/46029054/50780918-10f1f000-129c-11e9-8a93-a81ad532148e.png)

**Comment by lakelandcbd** [comment] 2019-01-07 16:50
Have fixed one issue

![image](https://user-images.githubusercontent.com/46029054/50781052-63331100-129c-11e9-9fe8-0719553eb5da.png)

**Comment by VivaWalletSupport** [comment] 2019-01-07 17:17
1. You fixed this issue with setting the correct return URLs in your payment source according the readme.txt?
2. Did you check if these transactions failed or if the customer aborted the transaction?
3. Use attached package to disable the pay by phone option 
[vivawallet-for-woocommerce.zip](https://github.com/VivaPayments/API/files/2733597/vivawallet-for-woocommerce.zip) or keep the orginal in case you want to accept these payments and manually make the transaction yourself through your viva backoffice (some customers prefer not to enter cc data on websites).

**Comment by VivaWalletSupport** [comment] 2019-01-09 06:06
Hello Nic, have all problems been resolved or can I assist you with anything else?

**Comment by lakelandcbd** [comment] 2019-01-09 09:46
Hi!

Things seem to be running ok now, I did all of the above that you said... and got a bit of help to do it. But I think we're there.

I do have one query but I'm not sure if it would word.

When our customers place an order, the status on wordpress is processing immediately after the order is made. However the payment might not clear into the Viva Wallet for anything from 2 hours up to 48 hours, which means we constantly have to check for payments going into our Viva Wallet.

Is there a way for the initial order status to be "pending payment" and then once the payment clears properly in Viva it then changes to "processing" 

Kind Regards

Nic

**Comment by VivaWalletSupport** [comment] 2019-01-09 10:08
Great to hear so, I would suggest to change the Order Status in the plugin from "Processing" to "On hold" as when stock inventory functionality is used, WooCommerce will cancel pending orders automatically after a set amount of time. In case you have any other question please let me know, otherwise you might close this issue.

**Comment by platawellness** [comment] 2019-01-23 09:46
Hi All,

Did you manage to sort out the issue regarding payment confirmation email from Viva Wallet being sent in Greek?

I have re saved the preferred language to "English (UK)" as per the instructions above however, the payment confirmation still is in Greek as per the attachment.

<img width="773" alt="screenshot 2019-01-23 at 09 44 23" src="https://user-images.githubusercontent.com/46958111/51597699-c4412280-1ef3-11e9-8052-87349752064a.png">

Please advise.

Regards,

Jon

**Comment by VivaWalletSupport** [comment] 2019-01-23 09:59
@platawellness Hello Jon, as this topic involves the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce could you please confirm you have this issue with this plugin?

**Comment by platawellness** [comment] 2019-01-23 10:02
@VivaWalletSupport Hi Tom, thanks for coming back to me so quickly. We actually use Shopify and it is all working very well apart from the issue mentioned above.

**Comment by platawellness** [comment] 2019-01-23 10:16
@VivaWalletSupport Just to confirm, I am not talking about the confirmation from Viva which the merchant receives, that is being received in English. We are referring to the payment confirmation that the customer receives from Viva.

**Comment by platawellness** [comment] 2019-01-23 10:34
@VivaWalletSupport This is not a Shopify issue. This is a payment confirmation generated by Viva Wallet and sent to the customer. It has nothing to do with Shopify.

**Comment by VivaWalletSupport** [comment] 2019-01-23 10:44
In case it also has nothing to do with the supported WooCommerce plugin I would suggest to post a new issue for this problem.

**Comment by platawellness** [comment] 2019-01-23 10:54
@lakelandcbd did you sort the issue with the customers payment confirmation being in Greek not English? If so, how did you do it?

Jon

**Comment by lakelandcbd** [comment] 2019-01-23 11:56
> @lakelandcbd did you sort the issue with the customers payment confirmation being in Greek not English? If so, how did you do it?
> 
> Jon

Let me check and get back to you! Nic

**Comment by GBDesignStudio** [comment] 2019-05-09 13:05
> Have fixed one issue
> 
> ![image](https://user-images.githubusercontent.com/46029054/50781052-63331100-129c-11e9-9fe8-0719553eb5da.png)

Hi, what URL did you use to redirect your customer back to the order details on your website please? 

I've used the vivawallet success URL supplied in the instructions as below:

https://mydomain.com/index.php?wc-api=wc_vivawallet&vivawallet=success

Is this correct please or is their a specific default woocommerce success URL? 

Thanks in advance 
Gary

**Comment by stmn2018** [comment] 2019-05-16 00:40
@lakelandcbd when you sorted the issue with the customers payment confirmation how did you do it? I have spent all day trying to get the page to redirect to my website after payment i just get a white screen with -1 in corner. Thank you in advance!

**Comment by jasonhubbard** [comment] 2019-05-21 12:31
> @lakelandcbd when you sorted the issue with the customers payment confirmation how did you do it? I have spent all day trying to get the page to redirect to my website after payment i just get a white screen with -1 in corner. Thank you in advance!

Hi, just had the same issue as you. The problem is there are 2 plugins! I used the one from the WordPress repository which gave the same -1 error, but if you use the folder from here https://github.com/VivaPayments/API/tree/master/Plugins/wordpress the return URL worked.

**Closed** 2019-07-15 15:45 UTC
