### ISSUE TITLE
Chrome login problem reoccurred

### ISSUE THREAD

**Issue by Giacomo120** [VivaPayments/API#1974] opened 2020-11-06 20:06 UTC
Hi, we are again encountering a problem already reported and addressed about a month ago.
When a customer tries to log in to their account to complete the order, the cart empties and a loop is created that makes it impossible for the customer to make the payment.

At the same time, we can't figure out if there is a problem with the final payment screen.

We urgently ask you to take action first of all for the Chrome problem which has already been addressed and it is absurd that it will occur again.
We are very disappointed with the vivawallet service.

**Comment by Giacomo120** [comment] 2020-11-06 20:39
![Screenshot_20201106_213833_com android chrome](https://user-images.githubusercontent.com/74073970/98412629-92715f80-2078-11eb-9717-350a983c7ae5.jpg)

**Comment by matthewrgourd** [comment] 2020-11-07 08:36
Hi @Giacomo120, sorry to hear this. I've checked and our Magento plugin seems to be working fine at www.hemport.it. I don't know what you mean by "Chrome issues" as I just tested in Chrome and was able to checkout correctly using a card with no funds. Also, according to our CRM, you has plenty of successful transactions recorded against your account. Did the problem occur on Chrome for mobile or the desktop version?

**Comment by Giacomo120** [comment] 2020-11-07 09:16
Hi Matthew, the problem was by mobile

**Comment by Giacomo120** [comment] 2020-11-07 09:19
I tried again just now and it is still there

**Comment by matthewrgourd** [comment] 2020-11-07 10:13
Hi there, I can’t see any issues on mobile using Chrome either. If you could send me a screenshot of the actual issue after it happens I’ll check further. In the meantime, after several tests, I can confirm that our plugin is working as expected. You have many many successful transactions recorded against your account using our plugin. This is a possible edge case but certainly not a fundamental problem with our checkout. Thank you!

**Comment by Giacomo120** [comment] 2020-11-07 10:15
I cannot take a screenshot of the problem. It's the same as a month ago. If I make a screen I only see the login screen, because when I enter the data the page updates without accessing

**Comment by Giacomo120** [comment] 2020-11-07 10:16
No, it is a serious problem! I lose customers if they can't navigate safely because of your gateway! Let's not joke

**Comment by Giacomo120** [comment] 2020-11-07 10:17
![Uploading Screenshot_20201107_111657_com.android.chrome.jpg…]()

**Comment by Giacomo120** [comment] 2020-11-07 10:18
![Uploading Screenshot_20201107_111657_com.android.chrome.jpg…]()

**Comment by Giacomo120** [comment] 2020-11-07 10:18
![Uploading Screenshot_20201107_111705_com.android.chrome.jpg…]()

**Comment by Giacomo120** [comment] 2020-11-07 10:20
As you can see when you try to login the page refreshes without logging in.
The same from checkout, in that case also empty the cart

**Comment by Giacomo120** [comment] 2020-11-07 10:25
Ok, now it seems to work.
It is already the third or fourth time, however, that this problem arises. It is not acceptable.
Your job is to provide a gateway, mine is to sell online: if such problems persist, I lose customers and I lose sales.
So please take action seriously and solve the problem once and for all, since it often risks presenting itself at times when no one can intervene.
Thanks

**Comment by matthewrgourd** [comment] 2020-11-07 10:40
Hi @Giacomo120 of course I'm taking this seriously. I will investigate but the screenshots didn't come through. Can I check if you're using Chrome on an iPhone or Chrome on an Android phone.

**Comment by Giacomo120** [comment] 2020-11-07 10:46
Yes, i was using Chrome from an android

**Comment by matthewrgourd** [comment] 2020-11-09 08:34
Please can you re-attach the screenshots as I'm unable to view them?

**Comment by Giacomo120** [comment] 2020-11-11 15:09
Hello sorry i forgot to reply

**Comment by Giacomo120** [comment] 2020-11-11 15:09
The problem is still there!

**Comment by Giacomo120** [comment] 2020-11-11 15:11
I don't know how much help the screenshot can be, because the only thing you will see is the login page, because once you put the data it reloads without logging in, while logging in from the check out empties the cart.
We do not understand if it is due to us or you, or if it is a problem present only on some devices because on some android mobile devices the problem is not there on others yes

**Comment by matthewrgourd** [comment] 2020-11-11 16:20
Hi @Giacomo120 I understand that the screenshot will not necessarily help. I need to get our dev team to have a look at this issue which seems to be limited to Chrome on Android phones. However, it may be linked to the particular theme you're using or something else related to Magento which we wouldn't be able to help with. In the meantime, can you get anyone experiencing problems to check out via their desktop / laptop computer instead?

**Comment by Giacomo120** [comment] 2020-11-11 16:22
I think it is difficult. At the moment, however, no one has reported this problem from the computer and we have not encountered it either.

**Comment by matthewrgourd** [comment] 2020-11-24 08:44
Hi @Giacomo120, as discussed at some length (in issue #2003), I believe this is a problem with your theme not our plugin. I fully tested your checkout before I came to this conclusion. I'm closing this issue now.

**Closed by matthewrgourd** 2020-11-24 08:44 UTC
Labels: e-commerce plugin
