### ISSUE TITLE
Magento 2.3 Installed Plugin But Payment Method Not Added

### ISSUE THREAD

**Issue by jimkar** [VivaPayments/API#1352] opened 2020-02-03 10:51 UTC
hi 

we installed your extension for Magento 2.3, we created the online payment app on viva wallet account, filled up all the necessary information on configuration such as API user/pass and app id.
But the viva wallet payment method does not shows up on front.

**Comment by matthewrgourd** [comment] 2020-02-05 12:16
Have you followed our [Magento 2.3](https://developer.vivawallet.com/e-commerce-plugins/magento2.3/) installation guide accurately? Are you using the latest version of Magento released in January? If you are it might be worth trying to revert back to a previous version.

**Comment by jimkar** [comment] 2020-02-05 13:32
We are not using the latest version. Our version is 2.3.1. And yes we followed the installation guide.

**Comment by matthewrgourd** [comment] 2020-02-06 10:30
Hi @jimkar, sorry for the delayed reply. One of our devs is looking at the issue. I'll update you soon.

**Comment by matthewrgourd** [comment] 2020-02-11 15:32
In order for us to investigate further could you send through the following screenshots:

- Payment module settings (mask the API Key).
- Viva Wallet payment source settings (include the browser's URL in the screenshot).
- Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
- API Access page (mask API Key, include the browser's URL in the screenshot).

Thanks

**Comment by jimkar** [comment] 2020-02-12 09:01
![viva_api](https://user-images.githubusercontent.com/8845568/74319040-f9cadf00-4d86-11ea-8272-f1c967214a5b.png)
![viva_payment_source](https://user-images.githubusercontent.com/8845568/74319047-fb94a280-4d86-11ea-9053-c03bff065bf0.png)
![viva_web_apps](https://user-images.githubusercontent.com/8845568/74319051-fd5e6600-4d86-11ea-9e79-c30864a42e9a.png)
![viva_modules](https://user-images.githubusercontent.com/8845568/74319052-fe8f9300-4d86-11ea-94b3-8f0aefeb1a13.png)

**Comment by jimkar** [comment] 2020-02-12 09:03
We have masked all the client's information

**Comment by matthewrgourd** [comment] 2020-02-12 11:27
Hi @jimkar in the last screenshot I take it you've deliberately removed the API key?

**Comment by jimkar** [comment] 2020-02-12 11:34
Yes we have masked the api key

**Comment by matthewrgourd** [comment] 2020-02-13 10:37
@jimkar your settings look fine. For the moment I'm unable to ascertain what the problem is, but I will keep checking...

**Comment by matthewrgourd** [comment] 2020-02-25 09:41
Hi @jimkar, I'm raising with our development team. I'll get back to you once they've investigated the issue.

**Comment by jimkar** [comment] 2020-02-27 08:22
@matthewrgourd do you have any estimated time?

**Comment by matthewrgourd** [comment] 2020-02-27 10:01
Hi @jimkar I'm sorry for the delay. If the extension has been excluded for specific countries or the store currency differs from the configured currency the payment method would not be available. I would suggest to test on a vanilla version of Magento to exclude any problem with other 3rd party extensions / themes.

**Closed** 2020-03-09 11:58 UTC
Labels: developer, e-commerce plugin
