### ISSUE TITLE
VivaWallet demo payments is not working

### ISSUE THREAD

**Issue by cvrak** [VivaPayments/API#1859] opened 2020-09-16 09:41 UTC
Hi,
I've set a VivaWallet demo account but when I try to make a test purchase I get the attached picture popup, select "sucess'" but then the failure URL is desplayed.
But when i check at Joomla admin, the purchase is made, pending status.
I use Redirection/Native Checkout v2 

Merchant ID: b9fd180e-a460-4414-8e11-8248050d704f
API Key: 5_r]Bm

How this can be fixed?

![viva_wallet_screen1](https://user-images.githubusercontent.com/62111630/93319585-b81c7e00-f818-11ea-9ba8-90c7c89b111b.jpg)

Thanks in advance
Chris

**Comment by matthewrgourd** [comment] 2020-09-16 11:41
Hi Chris, I can see no transaction recorded against your Viva Wallet account. As a consequence, I believe the Joomla order will automatically change status to "Cancelled" within 24 hours.

Are you attempting to implement our redirect checkout solution? I'm not sure why demo isn't working correctly. Can you try again and let me know, if, after clicking on **Confirm payment** (Success outcome chosen), the URL in your browser updates to include information similar to the following?
```
...result?t=05782261-e7c6-455d-ae0e-57b036cf52e9&s=1786359012548017&lang=en-US&eventId=0&eci=1
```
Can you let me know the "t=" value? so I can investigation further? Also, could you share with me the body parameters of the POST request you previously made to `https://demo.vivapayments.com/api/orders`?

Thanks!

**Comment by cvrak** [comment] 2020-09-16 15:17
The URL after the "Confirm payment" with success outcome is
https://www.anagnosi.gr/index.php/el/order-failure?s=9712526358872608&lang=el-GR&eventId=0

Is this helpful?
Thanks

**Comment by matthewrgourd** [comment] 2020-09-17 06:27
Hi @cvrak, I need to look into this further. Which version of Virtuemart are you using?

**Comment by cvrak** [comment] 2020-09-17 06:55
Hi
VM 3.8.4
Joomla 3.9,21
php 7.3.22

**Comment by matthewrgourd** [comment] 2020-09-17 09:47
Hi @cvrak, thanks for providing that info. So have you installed the latest version of our plugin for VM 3 from the below location and followed the accompanying instructions?

https://developer.vivawallet.com/e-commerce-plugins/virtuemart3/

**Comment by cvrak** [comment] 2020-09-17 12:31
Hi @matthewrgourd,
Yes, I've installed the latest version.
For success/failure URL I had /thank-you-for-your-order and /order-failure (joomla menu items -->articles)
I changed URLs as per the instructions, I see the "thank you for your order" message, but "your payment is not accepted, order cancelled" message as well.
In Joomla admin, the order is cancelled.

Any ideas?

**Comment by cvrak** [comment] 2020-09-18 11:21
Hi @matthewrgourd,

I've changed the URLs, according the instructions. The problem remains. 
You can see what I mean at the attached images.
When I complete the payment, I get the anagnosi_screen_04.jpg and the order in Joomla admin has status "cancelled"


![anagnosi_screen_06](https://user-images.githubusercontent.com/62111630/93591997-0fa61f80-f9ba-11ea-9fc6-206349b742d4.jpg)
![anagnosi_screen_01](https://user-images.githubusercontent.com/62111630/93592001-116fe300-f9ba-11ea-8c42-cb1503b5723c.jpg)
![anagnosi_screen_02](https://user-images.githubusercontent.com/62111630/93592005-12a11000-f9ba-11ea-8275-f1218a61f8fa.jpg)
![anagnosi_screen_03](https://user-images.githubusercontent.com/62111630/93592006-13d23d00-f9ba-11ea-80f9-c56965c3209a.jpg)
![anagnosi_screen_04](https://user-images.githubusercontent.com/62111630/93592010-146ad380-f9ba-11ea-8918-7e95d58eaf94.jpg)
![anagnosi_screen_05](https://user-images.githubusercontent.com/62111630/93592017-159c0080-f9ba-11ea-8354-2baeb7572aa9.jpg)

**Comment by matthewrgourd** [comment] 2020-09-18 12:28
Hi @cvrak I'm not immediately sure what the issue is. Everything looks fine from the point of view of your settings. This is just an idea, but can you try disabling VivaWallet test mode from the following dialog box and see if that makes any difference?

<img src="https://user-images.githubusercontent.com/62111630/93591997-0fa61f80-f9ba-11ea-9fc6-206349b742d4.jpg"/>

**Comment by matthewrgourd** [comment] 2020-09-18 12:37
Another thing to try is the test card number you entered had too many digits for both card number and CVV. Please use:

Name: Any
Card number: 4111 1111 1111 1111
CVV: 111
Expiration: Any in the future

**Comment by cvrak** [comment] 2020-09-18 17:10
Hi @matthewrgourd,
I've uninstalled and reinstalled the plugin. The problem remains the same.
I get the attached picture and the order is cancelled (Joomla admin)

I tried your suggestion to turn test mode "No". After inserting credit card data, a page is displayed instantly and then the https://www.vivapayments.com/web/newtransaction.aspx?Ref= 
page is displayed, saying that the order is not found (it seems normal to me, since its a real vivapayments page).
In Joomla admin, the order is "Pending"

![anagnosi_screen_04](https://user-images.githubusercontent.com/62111630/93625583-df2aa980-f9ea-11ea-81b6-e5f3754b643b.jpg)

**Comment by matthewrgourd** [comment] 2020-09-21 09:54
Hi @cvrak, I believe we had an issue with our demo environment which is now fixed. Can you try again a test transaction? With "test mode" disabled? If that doesn't work, please try setting up in the production environment, then testing with a very small payment amount, e.g. 30 cents but using a real card. You should then cancel the order from within Viva Wallet selfcare.

**Comment by cvrak** [comment] 2020-09-21 15:31
Hi @matthewrgourd,
I tested once more, It is working ok. For your information, test mode is "On".
Within the next dayes I'll test it in production and let you know

**Comment by matthewrgourd** [comment] 2020-09-22 08:35
Hi @cvrak, good to know. Thanks for the update. I'll keep this issue open until you've tested on production.

**Comment by cvrak** [comment] 2020-09-23 17:06
Hi @matthewrgourd,
I've tested in production environment and everything is ok.
Thanks
Chris

**Comment by matthewrgourd** [comment] 2020-09-24 08:18
@cvrak great, I'll close the issue now...

**Closed by matthewrgourd** 2020-09-24 08:18 UTC
Labels: e-commerce plugin

**Comment by cvrak** [comment] 2020-09-30 16:41
Hi @matthewrgourd,

I face the same hard situation with another customer of mine. I've installed the latest version of the plugin, Joomla and php is up to date, but the same problem occurs.
My customer's data is
Merchant ID  3e5261ba-1a37-4c35-a929-eba3f3e787b1
API Key   L31etpWf1j34teN169fR90zWOuq9yV
Code 5240

Pls advise
Chris
