### ISSUE TITLE
Viva payments don't work on my Shopify Store even though i have the Store Token and Merchand id connected

### ISSUE THREAD

**Issue by subir1910** [VivaPayments/API#1929] opened 2020-10-22 18:49 UTC
Hello, even though i have completed all the steps to integrate Viva Wallet on my store, when a customer tries to pay, Viva Wallet then redirects him to Viva's website to complete his purchase. What happens next is that the webpage doesn't work correct and it writes “Could not create order. Generic error.”

I am attaching a screenshot of what the redirect webpage looks like.

![Error-ShopifyPlug](https://user-images.githubusercontent.com/19603115/96916515-45f92200-14c5-11eb-8dce-d81f1d7e712b.png)

Please help me as soon as possible because i am losing time and therefore money.

Kind Regards

**Comment by Steevo0206** [comment] 2020-10-22 22:58
Hi I have exactly the same issue. If anyone can helps please.
Thank you

**Comment by matthewrgourd** [comment] 2020-10-23 07:14
Hi @subir1910, so that I can investigate further, please let me have your Merchant ID. Thanks!

**Comment by subir1910** [comment] 2020-10-23 07:35
Hi @matthewrgourd, Thank you so much for your reply

Yes! I put my merchant ID and Store token with Shopify payment provider, I follow the this doc https://developer.vivawallet.com/e-commerce-plugins/shopify/ and checked multiple times all is correct but is never fixed. I am losing my money. Can you please guide me. Thanks!

**Comment by matthewrgourd** [comment] 2020-10-23 07:36
Hi @subir1910, I need your merchant ID or trading name please? Otherwise I won't be able to check your account...

**Comment by matthewrgourd** [comment] 2020-10-23 07:38
Hi @Steevo0206, in order to check your account, I need your merchant ID and / or trading name, please?

**Comment by subir1910** [comment] 2020-10-23 07:38
Yes! my merchant ID is 3b8264cd-d5fe-40d6-86f8-a73e97610d85

**Comment by subir1910** [comment] 2020-10-23 08:04
@matthewrgourd, did you found the issue ?

**Comment by matthewrgourd** [comment] 2020-10-23 08:14
@subir1910 I'm checking for you. Please bear with me.

**Comment by matthewrgourd** [comment] 2020-10-23 08:38
Hi @subir1910 the problem is fixed and I just made a test with a card with no funds. You will see a failed payment but please ignore.

**Comment by matthewrgourd** [comment] 2020-10-23 08:48
@subir1910, if this has resolved your issue, please close this ticket. Thanks!

**Comment by Steevo0206** [comment] 2020-10-23 09:18
@matthewrgourd thank you! you are a star! At the moment I am leaving the website to checkout is it possible to use the native option and not redirection?
Thank you so much!

**Comment by subir1910** [comment] 2020-10-23 09:28
@matthewrgourd Thanks! Issue is solved, but can you tell me what eas the issue ?

**Comment by matthewrgourd** [comment] 2020-10-23 09:31
Hi @Steevo0206 I'm afraid we don't currently offer a native version of our plugin for Shopify.

@subir1910, the issue related to regeneration of your API key in the Viva Wallet banking app (**Settings > API Access**). Please do not do this at any point in your settings otherwise the plugin will stop working. Thanks!

**Comment by subir1910** [comment] 2020-10-23 09:35
@matthewrgourd thankyou so much. you are a genius..... THANKS

**Closed** 2020-10-23 09:35 UTC
Labels: shopify
