### ISSUE TITLE
PROBLEM WITH INSTALLMENTS

### ISSUE THREAD

**Issue by asmartgr** [VivaPayments/API#1377] opened 2020-02-14 10:20 UTC
Hello again,

the platform works at last, but we tried to make a purchase with installments and when we are redirected to the viva page and we put the full info of the credit card, there is not an option to choose the number of installments. At the plugin's options we have put the above:

100:12

![viva](https://user-images.githubusercontent.com/61015027/74522198-70044880-4f23-11ea-9201-f70ca73e89e9.png)

**Comment by matthewrgourd** [comment] 2020-02-14 12:12
Hi @asmartgr this is a duplicate of #1376. I've just replied to your query there. Please do not open multiple issues with the same query.

**Closed by matthewrgourd** 2020-02-14 12:12 UTC
