### ISSUE TITLE
Checkout Translation issue

### ISSUE THREAD

**Issue by Paolobigga** [VivaPayments/API#1456] opened 2020-03-12 15:09 UTC
Hi everyone,

I'll try again to ask since I couldn't solve issue yet.

I have trouble translating in the checkout on the front-end (attached you'll find an image)

I've tried to translate it from the admin area but it doesn't work.

I read in other posts to edit the language files located in the modules folder and rename every _vivawalletlatest_ wording to _vivawallet_, but it doesn't work either.

 How can I proceed?

Thank you!

Paolo

![Schermata-2020-02-26-alle-18 37 02](https://user-images.githubusercontent.com/61514653/76535795-bd6cca80-647b-11ea-88ff-8f0dcbb16842.jpg)

**Comment by matthewrgourd** [comment] 2020-03-13 11:08
Hi @Paolobigga I'll need to look into this. Let me get back to you.

**Comment by matthewrgourd** [comment] 2020-03-13 13:35
Could be a duplicate of #1022 or 1132#. Please check these first. Beyond that I'll need to investigate further...

**Comment by Paolobigga** [comment] 2020-03-13 13:56
I've already tried those solutions. They don't work

**Comment by matthewrgourd** [comment] 2020-03-13 14:01
Ok, I will raise with our tech team...sorry for the delay.

**Comment by Paolobigga** [comment] 2020-03-18 15:28
Hi @matthewrgourd 

Do you have any news?

**Comment by matthewrgourd** [comment] 2020-03-20 10:12
Hi @Paolobigga can you remind me which of our [e-commerce plugins](https://developer.vivawallet.com/e-commerce-plugins/) you've installed?

**Comment by Paolobigga** [comment] 2020-03-20 10:46
Prestashop

**Comment by matthewrgourd** [comment] 2020-03-20 10:54
Hi @Paolobigga I'm afraid I have no further information on how to do this apart from what I've already shared here which is almost an exact duplicate of your question: https://github.com/VivaPayments/API/issues/1132. Unfortunately, our third-party plugin developer is no longer working for us and we're going through a transition period. I can't therefore investigate any further at this time. If anything else comes up I'll be sure to let you know as soon as possible.

**Comment by matthewrgourd** [comment] 2020-04-08 09:36
Hi @Paolobigga I'm going to raise this with a developer as I gather from our customer service team you're still trying to find out the answer to this query. However, you previously said you already edited the language files that are located in the modules folder and renamed every "vivawalletlatest" wording to "vivawallet". Is that 100% correct? You have already tried that? Because that solution worked before for the person who raised it via issue #1132 when our third-party plugin developer suggested it.

**Comment by Paolobigga** [comment] 2020-04-08 10:08
Yes I am sure, I've tried many times...

**Comment by matthewrgourd** [comment] 2020-04-17 17:49
Hi @Paolobigga apologies for the extended delay. I've looked into this with our original plugin developer and he's come back with the following. So it is linked to the other issue I put you on to before. There is no other solution, I'm afraid. Thanks!

> First, the translation will have to be made by using PrestaShop's [translation system](https://devdocs.prestashop.com/1.7/modules/creation/module-translation/classic-system/). Afterwards the language file that resides in the modules folder will have to be edited manually. Any occurrence of the word "vivawalletlatest" or "vivawalletold" has to be changed to "vivawallet". Unfortunately this was necessary to have the module compatible with older versions of PrestaShop.

**Closed** 2020-04-20 09:42 UTC
Labels: developer, e-commerce plugin
