### ISSUE TITLE
Demo account

### ISSUE THREAD

**Issue by safwen1** [VivaPayments/API#1230] opened 2019-11-22 08:36 UTC
Hello we need a demo account.
Our production merchant ID = 5fafcd59-4060-4764-bb47-0bf3b15b02b9

Thank you

**Comment by matthewrgourd** [comment] 2019-11-22 10:43
Hi there, you need to sign up for one here: https://demo.vivapayments.com/

**Comment by safwen1** [comment] 2019-11-22 11:43
Hello @matthewrgourd , we have already tried that : 

![Screenshot from 2019-11-22 12-41-09](https://user-images.githubusercontent.com/13918596/69423071-84bab100-0d25-11ea-8282-408f92b14c9c.png)

And here is the result : 

![Screenshot from 2019-11-22 12-41-31](https://user-images.githubusercontent.com/13918596/69423135-a0be5280-0d25-11ea-9e7b-c9e6d76e94fe.png)

**Comment by matthewrgourd** [comment] 2019-11-22 14:26
Hi @safwen1 sorry for this, we are looking into as a potential bug. I'll update you once we have a solution. Unfortunately until then we can't provide you with a demo account.

**Comment by matthewrgourd** [comment] 2019-11-27 16:09
Hi @safwen1, feedback just received from our development team is that the problem is now fixed. Please try again and let me know how you get on!

**Comment by safwen1** [comment] 2019-11-27 17:46
Hello @matthewrgourd , we have successfully created a demo account.
Can you please allow the transactions endpoint for our merchant ID b5ca6922-069b-4008-988e-f7929347637c , like you did for our production account. 
Thank you.

**Comment by matthewrgourd** [comment] 2019-11-28 08:59
@safwen1 Done!

**Closed by matthewrgourd** 2019-11-28 08:59 UTC
Labels: account, developer
