### ISSUE TITLE
Checkout Card Payment screen language

### ISSUE THREAD

**Issue by mvoreadi** [VivaPayments/API#1467] opened 2020-03-17 13:33 UTC
dmihos Hi I use the Shopify plugin of Viva Wallet for my eshop and the default language of the card payment screen is Greek.  Could you please let me know how I can change it to English as people from other countries do not understand and leave the site.

Thanks,
Marilena
![a](https://user-images.githubusercontent.com/32038103/76861004-93911a80-6864-11ea-9236-7c1080d9d473.jpg)

**Comment by matthewrgourd** [comment] 2020-03-19 16:19
Duplicate of #1414

**Comment by matthewrgourd** [comment] 2020-03-19 16:23
Hi @mvoreadi sorry to hear this. The default language is set by the Shopify property 'Store Country'. It is currently based on Store Country only. There are no other settings. Apologies for any inconvenience caused...

**Closed** 2020-03-23 16:11 UTC
Labels: shopify
