### ISSUE TITLE
Woocommerce Integration prodution error and dev mode 404

### ISSUE THREAD

**Issue by weecl** [VivaPayments/API#1599] opened 2020-04-15 12:17 UTC
Hi,
I downloaded the woocomerce plugin from vivawallet. 
I followed the whole guide and everything is ok.
When I want to test it I reach a 404 page with this url:https://demo.vivapayments.com/web/newtransaction.aspx?Ref=
When I try in production mode, everything is ok until I validate my credit card I have a text above my thanks page with an"Error" in red without any number.
Thanks for reading me and sorry for my frenglish!

www.weecl-cbd.com if you want to give a try to see the problem.

**Comment by matthewrgourd** [comment] 2020-04-20 12:04
Hi @weecl if you get the message "An error has occurred, please try again", our plugin is working correctly, but you have a payment failure. We realised recently that the error message isn't very instructive and updated our plugin. You can find a replacement below. Hope this helps!

[vivawallet-for-woocommerce-3.6.0.zip](https://github.com/VivaPayments/API/files/4503309/vivawallet-for-woocommerce-3.6.0.zip)

**Comment by weecl** [comment] 2020-04-22 11:14
Hi, thanks for the answer, I updated the plugin and now it's worst...I have a WP error and no redirection to type my credit card at all. 
![received_663968920830135](https://user-images.githubusercontent.com/63720608/79975371-28f28080-849b-11ea-9638-52fa88edcbdc.png)

**Comment by matthewrgourd** [comment] 2020-04-22 11:45
Hi @weecl just to be clear, you're testing on live with your payment source set to 5363, is that correct? At the moment you've disabled the plugin?

**Comment by matthewrgourd** [comment] 2020-04-22 11:48
Please try the below version of the plugin instead: 

https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip

**Comment by matthewrgourd** [comment] 2020-04-28 08:24
Hi @weecl please close this issue if the problem is resolved. Thanks!

**Comment by weecl** [comment] 2020-04-28 17:38
Hi, 
Yes I solved everything with the new plugin on the wp store but 
I have some customer payment issues how could I be sure that is a 3DS issue? Can I enable a checkout without 3DS? 
Thanks

**Comment by matthewrgourd** [comment] 2020-04-29 08:28
According to the latest PSD2 legislation, 3DS is mandatory now.

**Comment by weecl** [comment] 2020-04-29 08:34
Thanks, but how an I be sure that It's really a 3DS issue and not from viva? I loose half of my orders...

**Comment by weecl** [comment] 2020-04-29 08:37
I'm trying a native pay can you validate again my websites pls:
Merchant ID: 0956412c-9fd7-4ed0-90c9-2ee1b3819c2f

**Comment by matthewrgourd** [comment] 2020-04-29 08:52
Hi @weecl if you're attempting to use our WooCommerce plugin it's redirect only. Please rest assured that you're not losing orders it's simply that those customers have a problem with their cards. Looking at the 28th April, there was one customer who repeatedly tried to make a payment but we received the error "Visa do not honour". They should refer to their card issuer in this instance. I can confirm that our plugin is working correctly on https://www.weecl-cbd.com/ Thanks!

**Comment by weecl** [comment] 2020-04-29 08:56
Thanks for the updates, could we have at least better messages for the customers?
If you don't mind could you reactivate my website which is pending due to my tests.
Thanks again.

**Closed** 2020-04-29 14:31 UTC
Labels: e-commerce plugin
