### ISSUE TITLE
VivaPayments Native v2 in Iframe Refused to connect 

### ISSUE THREAD

**Issue by PyB1l** [VivaPayments/API#2069] opened 2020-12-17 18:50 UTC
I suddenly started getting the following error in development.We use a pop up to display `redirectToACSForm` but today I get
the following error:

Refused to display 'https://demo.vivapayments.com/web/checkout/threedsecureauthentication/e9096f60-a615-403a-a7fe-ee6dbd50c3f2' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Both in Chrome and firefox

**Comment by matthewrgourd** [comment] 2020-12-18 16:19
Hi @PyB1l, we're aware of an intermittent issue. I don't know what the solution is yet. Will update you when I know more. Thanks.

**Comment by PyB1l** [comment] 2020-12-18 17:15
Does this affect production environment also?

**Comment by matthewrgourd** [comment] 2021-01-04 10:28
Hi @PyB1l, no, only the demo environment.

**Comment by matthewrgourd** [comment] 2021-01-05 09:40
Hi @PyB1l, I spoke to our dev team yesterday and apparently something has been switched off while we perform an upgrade to one of our systems. I'm told that by the end of the week this will be back. Sorry for any inconvenience.

**Comment by PyB1l** [comment] 2021-01-05 09:45
Thanks, I will close this issue as soon as it is restored

**Comment by matthewrgourd** [comment] 2021-01-08 13:19
Hi @PyB1l, I have an update for you: the 3DS simulator is provided by Modirum, a third-party company we use. The problem is on their side and unfortunately I currently don't have an ETA for a fix. In the meantime you can use the below cards to simulate successful / unsuccessful outcomes. These bypass the popup and are therefore the equivalent of frictionless transactions:

Long card number | Issuer | CVC | Expiry date | 3DS outcome
-- | -- | -- | -- | --
5188340000000011 | Mastercard | Any 3 digits | Any future date | Success
4016360000000010 | Visa | Any 3 digits | Any future date | Success
5188340000000029 | Mastercard | Any 3 digits | Any future date | Not authenticated
4016360000000028 | Visa | Any 3 digits | Any future date | Not authenticated

Hope this helps!

**Comment by matthewrgourd** [comment] 2021-01-15 13:05
Hi @PyB1l, apoligies, we're still awaiting a fix from our 3DS provider, Modirum, for test card number 5511070000000020. Another couple of cards you can use in the meantime (frictionless, no 3DS challenge) are listed below:

- 4006090000000007 (Visa, success outcome)
- 4929131949828217 (Visa, failure outcome)

**Comment by matthewrgourd** [comment] 2021-01-21 15:47
Hi @PyB1l, FYI, the issue was fixed by Modirum on Tuesday but since then there have been intermittent issues. As a result, we're currently looking into changing 3DS provider for our demo environment. Until then, please try with the below test card numbers:

- 5188340000000011
- 5511070000000020

**Closed by matthewrgourd** 2021-01-21 15:47 UTC
Labels: demo environment, developer
