### ISSUE TITLE
Possible merchant

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1991] opened 2020-11-16 11:54 UTC
@matthewrgourd I have a possible merchant interested to work with us but he has several questions about woocommerce, the ones are:

I would like to know if the integration with woocomerce works in such a way that the order is placed after payment or before payment is made. (There are payment gateways where the order form is first generated as pending payment, and then payment is made. On the contrary, there are other gateways in which the order is generated only if the payment has been made)

**Comment by matthewrgourd** [comment] 2020-11-16 12:52
Order in WooCommerce is always generated. If payment was successful, status of order will be "Processing" or "Completed" depending on merchant's [advanced settings](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#step-3-specify-advanced-settings-optional) (**Order status after successful payment** option). If payment was unsuccessful, status of order will be "Pending payment" which will later change to "Cancelled" automatically.

**Comment by Alvaroalconada** [comment] 2020-11-23 13:57
Hi @matthewrgourd This merchant just open a demo account and told me the next problems:

Could you check it?
![Configuracion plugin](https://user-images.githubusercontent.com/56823712/99970480-2f800800-2d9c-11eb-95fc-1a8d697b57c7.png)
![Fallo tarjeta](https://user-images.githubusercontent.com/56823712/99970510-3870d980-2d9c-11eb-8b9c-e52492d21c02.png)

**Comment by matthewrgourd** [comment] 2020-11-23 15:53
Hi @Alvaroalconada, we're not immediately sure what the problem is. In order to investigate further, please can you ask the merchant to send through the log file from the day when he made the test? Instructions on how to do this below:

1. Go to **WooCommerce > Status > Logs** tab:

![log1](https://user-images.githubusercontent.com/44943019/99075879-2039d700-25b2-11eb-806d-f45cc6441d68.png)

2. Select relevant date from the dropdown:

![log2](https://user-images.githubusercontent.com/44943019/99075893-262fb800-25b2-11eb-844d-bbf073524f3f.png)

3. Click on the **View** button.

4. Copy the contents into a text file and save it with an appropriate name. 

5. Attach to this issue in .txt format.

**Comment by Alvaroalconada** [comment] 2020-11-23 17:34
@matthewrgourd 

Attached are two logs:
- That of November 20th, that one test failed me and another one worked well.
- Today's log 23 Nov in which all the tests I have done have failed.
[log 20 nov.txt](https://github.com/VivaPayments/API/files/5584740/log.20.nov.txt)
[log 23 nov.txt](https://github.com/VivaPayments/API/files/5584741/log.23.nov.txt)

**Comment by matthewrgourd** [comment] 2020-11-24 09:52
Hi @Alvaroalconada, very strange what's happening there. If they have a production account, could I have the live Merchant ID for this customer, please?

**Comment by matthewrgourd** [comment] 2020-11-24 10:06
Hi @Alvaroalconada, our demo environment is being worked on at the moment. The problem could be linked to that. Best thing to do is try in production with a small transaction which merchant can immediately refund. Also, I will update this ticket once we have a fix on demo.

**Comment by matthewrgourd** [comment] 2020-12-02 14:28
Hi @Alvaroalconada, the demo environment has a fix. Merchants can now use our [test card](https://developer.vivawallet.com/getting-started/#test-card) number to simulate 3DS. If the issue is now resolved, please close it. Thanks!

**Closed** 2020-12-08 07:56 UTC
Labels: e-commerce plugin
