### ISSUE TITLE
 is their any option is available to save customer card details ?  while implementing, simple chechout or redirect checkout 

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1437] opened 2020-03-06 07:00 UTC
hi,
if we save card details so that, customer no need to enter card details again & again. is their any option is avaible in case of simple checkout 0r redirect checkout

**Comment by matthewrgourd** [comment] 2020-03-06 11:53
Duplicate of #1220. Hope that answers your question!

**Closed** 2020-03-06 14:34 UTC
Labels: redirect checkout
