### ISSUE TITLE
Test Cards with 3DS support

### ISSUE THREAD

**Issue by jkatsiotis** [VivaPayments/API#1073] opened 2019-09-15 08:54 UTC
Cards 4111 1111 1111 1111 / 4016 0000 0004 0000 012  / 4016 0000 000 02 are not working if 3DS is enabled (native checkout).

Can you provide with valid test card numbers with 3DS support that work in native checkout in the demo api?

**Comment by Sotiris-k** [comment] 2019-09-16 08:23
I'm having more or less the same problem.

I have tried all three of the above card with all combinations of "AuthenticateCardholder" true and false but I haven't managed to complete a transaction without getting either a 502 - Transaction failed error or some other card authentication error or another error concerning the charge token not being found after I just issued it.

Honestly is there anyone who has managed to get a completed successful transaction in the demo environment? This is getting really frustrating.

**Comment by odysseas12** [comment] 2019-09-16 08:43
Im not having any issue completing transactions, after I changed the payment source to redirect.

My issue is the cardHolderAuthInitiated function is not getting triggered and I dont know if that is expected behavior in the demo enviroment or not.

**Comment by jkatsiotis** [comment] 2019-09-16 08:45
Payment source is already "redirect". The whole point is to initiate the cardHolder Authentication. Is this is disabled cards work. So the only way to test this is to switch to production credentials.

Same code, switching to live with real cards work. In demo environment with test cards is not working

**Comment by Sotiris-k** [comment] 2019-09-16 08:48
My experience so far is that Transactions with chargeTokens obtained through 
`https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens`
Do not get completed.

However, transactions with chargeTokens obtained through
`https://demo-api.vivapayments.com/acquiring/v1/cards/chargetokens`
Do get completed.

Go figure.

**Comment by jkatsiotis** [comment] 2019-09-16 08:50
Yes, I assume they haven't implemented 3DS in the test cards they provide. Let's hope this will be fixed soon.

**Comment by odysseas12** [comment] 2019-09-16 09:49
Dont know guys I must be missing something. 
Did either of you send a request to 
https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens
in the demo environment and got back "redirectToACSForm" anything other than null ?

**Comment by Sotiris-k** [comment] 2019-09-16 10:11
You get an HTML page with the 4111 1111 1111 1111 CC number. All the others cards send back null.

That HTML page self submits and closes automatically, supposedly simulating a 3DS checkout experience but the transaction with that chargeToken ends up returning
```
{
    "Emv": null,
    "Amount": null,
    "StatusId": "E",
    "CurrencyCode": null,
    "TransactionId": null,
    "ReferenceNumber": null,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ThreeDSecureStatusId": null,
    "ErrorCode": 403,
    "ErrorText": "PaymentsCardHolderAuthenticationFailed",
    "TimeStamp": "2019-09-16T12:56:13.7460193+03:00",
    "CorrelationId": null,
    "EventId": 2062,
    "Success": false
}
```

**Comment by odysseas12** [comment] 2019-09-16 10:15
Even 4111111111111111 returns null for me.

**Comment by odysseas12** [comment] 2019-09-16 10:17
This is the request I send
{
    "Cvc": "111",
    "Amount": 1000,
    "Number": "4111111111111111",
    "Holdername": "John Doe",
    "ExpirationYear": 2030,
    "ExpirationMonth": 10,
    "AuthenticateCardholder": true,
    "SessionRedirectUrl": ""
}

I get back 

{
    "chargeToken": "ctok_kGPRS6X-n3a0MRmijP0Bgi7yf18",
    "redirectToACSForm": null
}

**Comment by jkatsiotis** [comment] 2019-09-16 10:17
If you are developing on iOS make sure all the properties you are sending are being sent as Strings. E.g. the amount is being sent as "Amount": "1000". If it's sent as "Amount":1000 is might result in null

**Comment by Sotiris-k** [comment] 2019-09-16 10:17
Are you using https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens with Bearer token?

**Comment by odysseas12** [comment] 2019-09-16 10:18
Im send with postman to https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens

**Comment by Sotiris-k** [comment] 2019-09-16 10:20
I've no idea why you're not getting a redirectACSForm.

This is my response
```
{
    "chargeToken": "ctok_fcjxbcupCbg3UsDKLEQKBQk-P34",
    "redirectToACSForm": "<!DOCTYPE html SYSTEM \"about:legacy-compat\">\n<html class=\"no-js\" lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n<meta charset=\"utf-8\"/>\n<title>3D Secure Processing</title>\n<link href=\"https://vposprocessor2.modirum.com/mdpaympi/static/mpi.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>\n<body>\n<div id=\"main\">\n<div id=\"content\">\n<div id=\"order\">\n<h2>3D Secure Processing</h2>\n<img src=\"https://vposprocessor2.modirum.com/mdpaympi/static/preloader.gif\" alt=\"Please wait..\"/>\n<img src=\"https://vposprocessor2.modirum.com/mdpaympi/static/verifiedbyvisa.png\" alt=\"Verified by VISA\"/>\n<div id=\"formdiv\">\n<script type=\"text/javascript\">\nfunction hideAndSubmitTimed(formid)\n{\nvar timer=setTimeout(\"hideAndSubmit('\"+formid+\"');\",100);\n}\n\nfunction hideAndSubmit(formid)\n{\nvar formx=document.getElementById(formid);\n\tif (formx!=null)\n\t{\n\tformx.style.visibility=\"hidden\";\n\tformx.submit();\n\t}\n}\n</script>\n<div>\n<form id=\"webform0\" name=\"red2ACSv1\" method=\"POST\" action=\"https://3ds-acs.test.modirum.com/mdpayacs/pareq\" accept_charset=\"UTF-8\">\n<input type=\"hidden\" name=\"_charset_\" value=\"UTF-8\"/>\n<input type=\"hidden\" name=\"PaReq\" value=\"eJxVUV1vgjAU/SvGH0BbYALm2oSpy3xwcWwz8bEpN0oiH5YCul+/FmFufek59/ueC58nhbj6QNko5LDFuhZHnGTpYrpL3j2P+oxOOeziBC8cWlR1VhacOdRxgYzUpCl5EoXmIOTlefPG/f4BGSjkqDYrzlzPf5oBuTMoRI58v9nHQHoIsmwKrW7coxTISKBRZ37SuqrnhHRd57RZKzpxPqN2ZJkDsX4gjxF2jUW1qXfNUr6tuyb0M7amyzg5VC/fh+OqTGe6bcIFEBsBqdDIXcoiGrHZhNE5i+bUrNfbQeR2EL7+SiZB5NjJBgtUtlF8J0FkPX8tYBRVWMgbj4LQrDMywGtVFmgiTItfDCnW0qwxfI8dlq9WVKmNYAENQhq5zMraG2ypzEjkMkb7WpYAsSlkuBgZLmrQv0v/AEdIpic=\"/>\n<input type=\"hidden\" name=\"MD\" value=\"3a98b0db-1f42-4c66-b9b8-193a10da9328\"/>\n<input type=\"hidden\" name=\"TermUrl\" value=\"https://demo.vivapayments.com/web/checkout/threedsecurevalidation\"/>\n<input type=\"submit\" name=\"submitBtn\" value=\"Please click here to continue\"/>\n</form>\n</div>\n</div>\n<script type=\"text/javascript\">\n\t\t\thideAndSubmitTimed('webform0');\n\t\t</script>\n<noscript>\n<div align=\"center\">\n<b>Javascript is turned off or not supported!</b>\n<br/>\n</div>\n</noscript>\n</div>\n<div id=\"content-footer\">\n<br/>\n<img height=\"20\" src=\"https://vposprocessor2.modirum.com/mdpaympi/static/powered-by-modirum.svg\" alt=\"Powered by Modirum\"/>\n</div>\n</div>\n</div>\n</body>\n</html>\n"
})
```

**Comment by odysseas12** [comment] 2019-09-16 10:32
Lovely.

**Comment by Sotiris-k** [comment] 2019-09-17 06:21
@matthewrgourd some kind of an answer to these problems mentioned here would be appreciated. We can't let the days go by without a functioning implementation.

**Comment by jkatsiotis** [comment] 2019-09-17 06:22
Currently we are testing with live cards. Not optimal at all.

**Comment by Sotiris-k** [comment] 2019-09-17 06:30
At this point I'd even settle for a tested working code sample but I guess that's wishful thinking. 

Testing with live cards should really not be an option at all...

**Comment by beisnikosspi** [comment] 2019-09-17 06:32
Hello, any updates about this? Do the dummy cards still not working?

**Comment by jkatsiotis** [comment] 2019-09-17 06:43
No. Dummy cards still not working

**Comment by Sotiris-k** [comment] 2019-09-17 06:50
@jkatsiotis Do you get an html page inside the "redirectToACSForm" field as I do? What happens once you display it and move on with the transaction after?

**Comment by Sotiris-k** [comment] 2019-09-17 06:55
demo

**Comment by jkatsiotis** [comment] 2019-09-17 07:03
3DS seems like it's being completed (dialog open / closes). Then, I send the charge token back to my server. I create a payment order and try to complete a transaction with this charge token but I get a "Transaction Failed" message.

FYI the same thing happens in live if for some reason the customer rejects the authentication. You still get the charge token but once you try to charge it you see a transaction failed message. So I assume their 3DS provider is not configured with test cards and rejects all 3DS authentication requests

**Comment by Sotiris-k** [comment] 2019-09-17 07:16
I'm getting a PaymentsCardHolderAuthenticationFailed error with the 4111 1111 1111 1111 card and it's the only card that returns something in the "redirectToACSForm" field.

With the others card I get Transaction Failed but they also return an empty "redirectToACSForm" field.

Thank you for testing this on production for all of us who can't :)

**Comment by nlabiris** [comment] 2019-09-17 12:21
Same issue here regarding the test cards. There is an issue with the Viva's OTP provider, as far as I know, that's why the test cards are not working. Production should be OK. A few tests with all the demo cards I have

```
{
    "Cvc": "111",
    "Amount": 100,
    "Number": "4111111111111111",
    "Holdername": "John Doe",
    "ExpirationYear": 2030,
    "ExpirationMonth": 10,
    "AuthenticateCardholder": true,
    "SessionRedirectUrl": "{{endpoint}}"
}

{
    "Emv": null,
    "Amount": null,
    "StatusId": "E",
    "CurrencyCode": null,
    "TransactionId": null,
    "ReferenceNumber": null,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ThreeDSecureStatusId": null,
    "ErrorCode": 403,
    "ErrorText": "PaymentsCardHolderAuthenticationFailed",
    "TimeStamp": "2019-09-17T13:12:51.7424638+03:00",
    "CorrelationId": null,
    "EventId": 2062,
    "Success": false
}

=== === === === === === === === === === ===

{
    "Cvc": "111",
    "Amount": 100,
    "Number": "4016000000040000012",
    "Holdername": "John Doe",
    "ExpirationYear": 2030,
    "ExpirationMonth": 10,
    "AuthenticateCardholder": true,
    "SessionRedirectUrl": "{{endpoint}}"
}

{
    "Emv": null,
    "Amount": 1,
    "StatusId": "E",
    "CurrencyCode": "978",
    "TransactionId": "1b9cf64c-699c-4cee-a46e-f1ee7d2b813a",
    "ReferenceNumber": 103759,
    "AuthorizationId": "612132",
    "RetrievalReferenceNumber": "000001021001",
    "ThreeDSecureStatusId": 2,
    "ErrorCode": 502,
    "ErrorText": "Transaction failed",
    "TimeStamp": "2019-09-17T14:09:55.0161636+03:00",
    "CorrelationId": null,
    "EventId": 10051,
    "Success": false
}

=== === === === === === === === === === === === === === === === ===

{
    "Cvc": "111",
    "Amount": 100,
    "Number": "4016000000002",
    "Holdername": "John Doe",
    "ExpirationYear": 2030,
    "ExpirationMonth": 10,
    "AuthenticateCardholder": true,
    "SessionRedirectUrl": "{{endpoint}}"
}

{
    "Emv": null,
    "Amount": 1,
    "StatusId": "E",
    "CurrencyCode": "978",
    "TransactionId": "fe01e5d1-93e2-47c6-b5f8-a283c7d4f299",
    "ReferenceNumber": 103761,
    "AuthorizationId": "612132",
    "RetrievalReferenceNumber": "000001021001",
    "ThreeDSecureStatusId": 2,
    "ErrorCode": 502,
    "ErrorText": "Transaction failed",
    "TimeStamp": "2019-09-17T14:12:47.9509828+03:00",
    "CorrelationId": null,
    "EventId": 10051,
    "Success": false
}


=== === === === === === === === === === === === ===


{
    "Cvc": "111",
    "Amount": 100,
    "Number": "6007930123456780",
    "Holdername": "John Doe",
    "ExpirationYear": 2030,
    "ExpirationMonth": 10,
    "AuthenticateCardholder": true,
    "SessionRedirectUrl": "{{endpoint}}"
}


{
    "Emv": null,
    "Amount": null,
    "StatusId": "E",
    "CurrencyCode": null,
    "TransactionId": null,
    "ReferenceNumber": null,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ThreeDSecureStatusId": null,
    "ErrorCode": 422,
    "ErrorText": "PaymentsNoBinRouteFound",
    "TimeStamp": "2019-09-17T14:14:44.7922086+03:00",
    "CorrelationId": null,
    "EventId": 2054,
    "Success": false
}
```

**Comment by dpnevmatikos** [comment] 2019-09-17 14:21
Hello everyone, 
I'll try to address as many inquiries as I can :) 

1) **Card numbers**:
Unfortunately, currently, **there are no card numbers that trigger the 3DS window and are able to
successfully complete a payment** . This is due to the fact that these are just dummy card numbers and can't be
validated correctly within our system. I understand that this can be quite confusing (and it is) to most people trying to integrate with Native Checkout v2. We are currently working towards implementing a
dummy issuer's/3DS window to allow better control to API/Native Checkout v2 consumers over cardholder authentication process during the integration phase, but it might be a while till this reaches demo environment.
A suggested workaround is to use the 4111 card along with the `authenticateCardholder` param set to `false`, as shown [here](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-4-request-a-charge-token). This will essentially skip 3DS authentication and complete the payment. If you've already handled the authentication window in your JS code then you are fine to follow this approach. 

2) **Regarding `cardHolderAuthInitiated` event:** 
This is not always triggered. It depends on whether the card is 3DS enrolled or not. If it is, then it should fire, as expected. 

3) **Sources configuration:** 
Please remember that when creating a source to use with Native v2, then the option "Integration method" should be set to `Redirect` and not `Native Checkout` as it applies only to v1 integrations.

4) **Acquiring endpoints** (https://demo-api.vivapayments.com/acquiring/v1/cards/chargetokens): 
@Sotiris-k  this is a different API set with no 3DS support, so basically it's the same as using Native Checkout v2 endpoint with `authenticateCardholder` set to false as I mentioned earlier. That's why
your payment is completed successfully.

5) **Amounts** are most of the times set in the currency's minor unit of measurement (e.g. cents in Euro etc)

Please let me know if there's anything else I can help clarify. 
I'd also like to thank you all, for providing such meaningful feedback, which will be taken
as input to improving our developer docs. :)

**Comment by stevestavropoulos** [comment] 2019-09-20 15:07
The authenticateCardholder option doesn't exist for the Redirect option. What's the solution for testing there?

**Comment by dpnevmatikos** [comment] 2019-09-20 15:18
@stevestavropoulos  Redirect, as well as Simple Checkout have cardholder auth integrated so there's no need for a separate implementation from your side.

**Comment by stevestavropoulos** [comment] 2019-09-20 16:02
@dpnevmatikos please see issues https://github.com/VivaPayments/API/issues/1056 and https://github.com/VivaPayments/API/issues/1040
Because of the 3DS failure in the demo environment, no payment can be made when using Redirect checkout. An option to disable 3DS would be a possible workaround, but it doesn't exist...

**Comment by jkatsiotis** [comment] 2019-09-23 10:58
Is the issue fixed? Cards work now ?

**Comment by matthewrgourd** [comment] 2019-09-23 11:10
@jkatsiotis Not in demo yet. Apologies, I will reopen :-)

**Comment by kevinfarrugia** [comment] 2019-10-21 06:44
@matthewrgroud is it possible to include a reference to this issue in the documentation as it would have saved us some time during testing.

**Comment by matthewrgourd** [comment] 2019-11-01 10:57
Hi @jkatsiotis our dev team has made some changes behind the scenes meaning that an emulation of 3DS is now available in the demo environment. Please see #1056 (comment) for further info. Hope that solves the issue!

**Comment by jkatsiotis** [comment] 2020-08-17 10:02
Hi, coming back to this we are trying to use the test card 4111 1111 1111 1111 with cvv 111 and 01/21 as exp date and after the 3DS popup shows and we select "Success" as the outcome we get the following error:
"Η συναλλαγή σας απέτυχε."

See more in this vid: https://www.loom.com/share/40eddbf3fd934a3eaeb28186fb5f877b

**Comment by matthewrgourd** [comment] 2020-08-17 10:30
Hi @jkatsiotis, sorry to hear this. In order for me to investigate further, can you let me have the Merchant ID assigned to your Viva Wallet demo account.

**Comment by jkatsiotis** [comment] 2020-08-17 10:34
Thanks for the swift response. Sure, here it is: 

adc4b0fe-31d9-4162-9f3a-2265b6887282

**Comment by matthewrgourd** [comment] 2020-08-17 10:44
Hi @jkatsiotis thanks. There is nothing recorded against the account so I believe there may be an error in your request. Could you share with me the exact contents of the request body?

**Comment by jkatsiotis** [comment] 2020-08-17 10:47
I created a payment order from the demo website. Here is the Payment Order Id 2637601330172607

**Comment by jkatsiotis** [comment] 2020-08-17 10:48
Here is the link: https://demo.vivapayments.com/web/checkout?ref=2637601330172607&lang=el-GR

**Comment by jkatsiotis** [comment] 2020-08-17 10:48
The page where I created the payment order:

![image](https://user-images.githubusercontent.com/751955/90388362-5a1d3f00-e090-11ea-9cf9-14623f57deb6.png)

**Comment by matthewrgourd** [comment] 2020-08-17 10:52
Very strange, I just got it to work and I used exactly the same details for each field. Will get someone in the development team to look into this.

**Closed** 2020-08-17 12:14 UTC
Labels: native checkout v2

**Comment by kwstoikonomou** [comment] 2021-01-07 12:50
Any updates on this? 

Can we use test cards for the 3ds flow? 

> 3DS seems like it's being completed (dialog open / closes). Then, I send the charge token back to my server. I create a payment order and try to complete a transaction with this charge token but I get a "Transaction Failed" message.

I am using the 4111 1111 1111 1111 card and this is exactly what happens to me. 

response:
```
{"status":400,"message":"PaymentsCardHolderAuthenticationInvalidStatus","eventId":"2061"}
```

**Comment by matthewrgourd** [comment] 2021-01-07 13:19
Hi @kwstoikonomou, the new [test card](https://developer.vivawallet.com/getting-started/#test-card) to use is 5511070000000020. However, unfortunately there is a problem we're looking into currently meaning it may not work predictably at the moment. We should get this sorted by tomorrow at the latest. Apologies for any inconvenience caused.

**Comment by kwstoikonomou** [comment] 2021-01-08 13:11
Any updates on this? ETA?

**Comment by matthewrgourd** [comment] 2021-01-08 13:17
Hi @kwstoikonomou, I have an update: the 3DS simulator is provided by Modirum, a third-party company we use. The problem is on their side and unfortunately I currently don't have an ETA for a fix. In the meantime you can use the below cards to simulate successful / unsuccessful outcomes. These bypass the popup and are therefore the equivalent of frictionless transactions:

Long card number | Issuer | CVC | Expiry date | 3DS outcome
-- | -- | -- | -- | --
5188340000000011 | Mastercard | Any 3 digits | Any future date | Success
4016360000000010 | Visa | Any 3 digits | Any future date | Success
5188340000000029 | Mastercard | Any 3 digits | Any future date | Not authenticated
4016360000000028 | Visa | Any 3 digits | Any future date | Not authenticated

Hope this helps!

**Comment by kwstoikonomou** [comment] 2021-01-08 13:25
I get an error with those as well. 

`Client error: `GET https://demo-api.vivapayments.com/acquiring/v1/cards/tokens?chargeToken=ctok_yoBHPaTiIZJo_lOVuYdk5A9qA5A` resulted in a `404 Not Found` response:\n{\"status\":404,\"message\":\"Could not get 'token:charge:ctok_xxxxxxxxxxxxxxxxx', key does not exist\",\"eventId\":\"2 (truncated...))"}`

**Comment by matthewrgourd** [comment] 2021-01-08 13:28
@kwstoikonomou, oh, that's something different, you need to generate another card token before attempting again...

**Comment by kwstoikonomou** [comment] 2021-01-08 13:45
Sorry, wrong message. This is what i get when i use card **5188340000000011**

Client error: `GET https://demo-api.vivapayments.com/acquiring/v1/cards/tokens?chargeToken=ctok_xxxxxxxxxx` resulted in a `400 Bad Request` response:
{"status":400,"message":"PaymentsCardHolderAuthenticationInvalidStatus","eventId":"2061"}

**Comment by matthewrgourd** [comment] 2021-01-08 14:55
Hi @kwstoikonomou, sorry to hear that, apparently there is still an outstanding issue with our demo 3DS provider. The new demo cards work fine with our [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) solution but currently not [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/). There should be a resolution soon...
