### ISSUE TITLE
API Call failed!

### ISSUE THREAD

**Issue by Karroum83** [VivaPayments/API#947] opened 2019-07-17 10:13 UTC
Hello,
I'm trying to create order with viva payment (php) so I used the sample on Api-Master but, I always have the same problem
API call failed with both:
$request =  'https://demo.vivapayments.com/api/orders';	// demo environment URL
$request =  'https://www.vivapayments.com/api/orders'
I tryed with http, so it displayed "Moved permanently" and with https I have no answer like the URL doesn't exist.
Any one have an idea?
Regards

**Comment by matthewrgourd** [comment] 2019-07-17 10:34
Hi there, in the case of the demo account you need to authenticate using your demo merchant ID and API key. In the case of production, replace your demo merchant ID and API key with the equivalent from your production account. For more information, see [basic authentication](https://developer.vivawallet.com/authentication-methods/#basic-authentication) and [Find your merchant ID and API key](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/). Hope this helps! If your problem is resolved, please close this issue.

**Comment by matthewrgourd** [comment] 2019-07-17 10:35
Apologies, closed in error.

**Comment by Karroum83** [comment] 2019-07-17 10:42
of course that's what I did but it doesn't work for both

**Comment by Karroum83** [comment] 2019-07-17 10:57
![image](https://user-images.githubusercontent.com/52999672/61370307-66820780-a892-11e9-878f-9945d48f2e53.png)

**Comment by matthewrgourd** [comment] 2019-07-17 11:13
Hi there, I've checked and our Payment API is working correctly so I'm not sure immediately what the problem is unless there's a mistake in our PHP sample code. Will check with one of our developers and get back to you. You're definitely using the merchant ID and API key from your demo account? Is there more than one source set up in which case change 'default to the code for the source.

**Comment by Karroum83** [comment] 2019-07-17 11:20
I'm trying both
live account and demo account, for each page I use API Merchant Id , Api Key and source code I have on my business page (source default for demo)

it looks like these pages: 'https://demo.vivapayments.com/api/orders' and https://www.vivapayments.com/api/orders';    do not answer

**Comment by matthewrgourd** [comment] 2019-07-17 12:25
Hi there, looks like there's a general issue with the demo server which we're looking into. I'll get back to you as soon as I can.

**Comment by matthewrgourd** [comment] 2019-07-17 13:24
Hi there, the demo server is back up and running. Please try again and let me know how you get on!

**Comment by Karroum83** [comment] 2019-07-17 14:06
still not working, bugs here
				throw new Exception("API Call failed! The error was: ".trim($match[1]));

**Comment by matthewrgourd** [comment] 2019-07-17 15:10
Hi there, the demo server is definitely working now. Please send through your request body so we can troubleshoot the issue...

**Comment by Karroum83** [comment] 2019-07-17 15:24
I'm using this code to create order for both demo and live api/create_order
https://raw.githubusercontent.com/VivaPayments/API/master/CreateOrder/PHP/create_order.php
and I have the same message:
"API Call failed! "
so I have no object (resultObj ) created :/
I tried this on local and on distant servers

**Comment by matthewrgourd** [comment] 2019-07-17 15:48
Please send through some screenshots of what you are trying to achieve. Thanks.

**Comment by Karroum83** [comment] 2019-07-17 16:02
![image](https://user-images.githubusercontent.com/52999672/61391463-094f7b80-a8bd-11e9-8bac-1fc0a9985285.png)

**Comment by matthewrgourd** [comment] 2019-07-18 09:33
Hi there, I've checked and there is no problem at our end. I'm afraid we can't provide generic PHP support, so I'm closing this issue. Thanks.

**Closed by matthewrgourd** 2019-07-18 09:33 UTC

**Comment by Karroum83** [comment] 2019-07-18 12:31
But it s abnormal that we can not have an answer with api key and ID!!!

**Comment by Karroum83** [comment] 2019-07-18 13:56
You may provide any php code to get answer from the Api

**Comment by matthewrgourd** [comment] 2019-07-18 14:47
Hi there, I'm sorry we can't help you with the PHP. However this screenshot from Postman may help! You can see an order code has been successfully created. The username and password should be your merchant ID and API key from https://demo.vivapayments.com/en/signin (see [Find your merchant ID and API key](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key) further info). Thanks!

**Comment by Karroum83** [comment] 2019-07-18 18:53
Ok I fixed that code.
So the problem wasn't with api gateway it was the php sample done on github

**Comment by matthewrgourd** [comment] 2019-07-19 07:21
Sorry for that, we will look into updating the code. Do you have a working version you can share? Unfortunately we're lacking a php developer currently. Thanks!

**Comment by Karroum83** [comment] 2019-07-19 09:00
<?php


$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://www.vivapayments.com/api/orders",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "{\r\n  \"Tags\": [\r\n    \"sample string 1\",\r\n    \"sample string 2\",\r\n    \"sample string 3\"\r\n  ],\r\n  \"Email\": \"customer@domain.com\",\r\n  \"Phone\": \"2117604000\",\r\n  \"FullName\": \"Customer Name\",\r\n  \"PaymentTimeOut\": 86400,\r\n  \"RequestLang\": \"en-US\",\r\n  \"MaxInstallments\": 12,\r\n  \"AllowRecurring\": true,\r\n  \"IsPreAuth\": true,\r\n  \"Amount\": 1000,\r\n  \"MerchantTrns\": \"1818\",\r\n  \"CustomerTrns\": \"Description that the customer sees\"\r\n}",
  CURLOPT_HTTPHEADER => array(
    "authorization: Basic 'Create a basic auth here'",
    "cache-control: no-cache",
    "content-type: application/json"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response[1];
}
	try {
	if(is_object(json_decode($response))){
	  	$resultObj=json_decode($response);
	}else{
		preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader, $match);
				throw new Exception("API Call failed! The error was: ".trim($match[1]));
	}
} catch( Exception $e ) {
	echo $e->getMessage();
}
if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
	$orderId = $resultObj->OrderCode;
	//echo 'Your Order Code is: <b>'. $orderId.'</b>';
	echo '<br/><br/>';
header( "refresh:3;url= http://www.vivapayments.com/web/newtransaction.aspx?ref=".$orderId );
//	echo '</br/><a href="http://www.vivapayments.com/web/newtransaction.aspx?ref='.$orderId.'" >Make Payment</a>';
}
	
else{
	echo 'The following error occured: ' . $resultObj->ErrorText;
}
}

?>
