### ISSUE TITLE
Simple Checkout: emulating successful payments

### ISSUE THREAD

**Issue by GriALAte** [VivaPayments/API#2080] opened 2020-12-28 09:51 UTC
Hello,
We are trying to test a Simple Checkout integration with a demo account, however, using the test card from the documentation (5511070000000020, 12 / 21, 111) and submitting 'correct' in 3DS authentication form always results in Error 502 - Transaction Failed:
{
  "Emv": null,
  "Amount": 156.51,
  "StatusId": "E",
  "RedirectUrl": null,
  "CurrencyCode": "978",
  "TransactionId": "6104f185-2714-4783-a966-9e974e060b17",
  "ReferenceNumber": 819993,
  "AuthorizationId": null,
  "RetrievalReferenceNumber": null,
  "Loyalty": null,
  "ThreeDSecureStatusId": 2,
  "ErrorCode": 502,
  "ErrorText": "Transaction failed",
  "TimeStamp": "2020-12-28T11:32:08.3225387+02:00",
  "CorrelationId": null,
  "EventId": 4707,
  "Success": false
}
Merchant ID: 36f8e5ca-48a1-40e1-8dbc-83472e6d7353
Payment source: 6769
How could we emulate successful authentication? Is there any other test card for successful transactions?

**Comment by JoshBour** [comment] 2020-12-28 11:59
I'm facing the same issue using the redirect checkout. By submitting "correct" a transaction gets created but I get redirected to the "fail" page instead of the "success" page.

**Comment by matthewrgourd** [comment] 2021-01-04 10:40
Hi @GriALAte / @JoshBour, I've raised this issue again today and will update you as soon as there's a fix. Should be soon.

**Comment by codepixel** [comment] 2021-01-04 16:29
Same issue here.
Trying the "redirect checkout" with the "correct" keyword on 3ds validation but always get redirected to the "fail" page. :(

docs: https://developer.vivawallet.com/online-checkouts/redirect-checkout/

**Comment by knikolou** [comment] 2021-01-04 20:51
Same issue demo accounts not working anymore redirects error

**Comment by LoggiaNG** [comment] 2021-01-05 05:31
I don't know if it's related (probably is), but here is the result of a tokenization payment with the demo card.
I don't see the EventId 4707 or error PayShieldCommandExecutionFailed mentioned anywhere...

![Screenshot 2021-01-04 at 3 34 13 PM](https://user-images.githubusercontent.com/53644001/103610039-dd4c0e00-4f27-11eb-8a89-85630a21313b.png)

**Comment by matthewrgourd** [comment] 2021-01-05 09:28
Hi @GriALAte, @JoshBour, @codepixel, @knikolou, @LoggiaNG, I spoke with our dev team yesterday. This issue is known about and will be fixed by the end of the week if not before. We are performing a security upgrade that unfortunately means the test card number is unable to be used at present, at least not in a particularly meaningful way.

**Comment by codepixel** [comment] 2021-01-07 23:23
@matthewrgourd Any update on this?

**Comment by matthewrgourd** [comment] 2021-01-08 08:42
@codepixel chasing. Will provide an update later today.

**Comment by matthewrgourd** [comment] 2021-01-08 13:20
Hi @GriALAte, @JoshBour, @codepixel, @knikolou, @LoggiaNG, I have an update for you: the 3DS simulator is provided by Modirum, a third-party company we use. The problem is on their side and unfortunately I currently don't have an ETA for a fix. In the meantime you can use the below cards to simulate successful / unsuccessful outcomes. These bypass the popup and are therefore the equivalent of frictionless transactions:

Long card number | Issuer | CVC | Expiry date | 3DS outcome
-- | -- | -- | -- | --
5188340000000011 | Mastercard | Any 3 digits | Any future date | Success
4016360000000010 | Visa | Any 3 digits | Any future date | Success
5188340000000029 | Mastercard | Any 3 digits | Any future date | Not authenticated
4016360000000028 | Visa | Any 3 digits | Any future date | Not authenticated

Hope this helps!

**Comment by codepixel** [comment] 2021-01-08 14:21
Hello @matthewrgourd 
i can confirm that i get  correctly redirect using
4016360000000010 | Visa | Any 3 digits | Any future date | Success
5188340000000029 | Mastercard | Any 3 digits | Any future date | Not authenticated

Tks

**Comment by matthewrgourd** [comment] 2021-01-08 14:31
Hi @codepixel, awesome, that's good to know!

**Comment by knikolou** [comment] 2021-01-08 14:54
> Same issue demo accounts not working anymore redirects error

@matthewrgourd  Thanks its working now all my demo accounts with new cards!!

**Closed** 2021-01-08 16:38 UTC
Labels: demo environment, developer
