### ISSUE TITLE
Issue with odoo and viva connector

### ISSUE THREAD

**Issue by Stavrosmylonas** [VivaPayments/API#2032] opened 2020-12-01 07:00 UTC
Hello

In the last 7 days was an issue with the connector of VIVA and odoo.  After you receive the digipass code and accepts it, stacks
![issue with viva connector](https://user-images.githubusercontent.com/75297978/100707610-96f91180-33b3-11eb-8f0d-ed4685e74fd9.JPG)

**Comment by matthewrgourd** [comment] 2020-12-01 10:36
Hi @Stavrosmylonas, sorry to hear that. I've checked your account and I can see no transactions for the last 7 days. I also notice you have PayPal enabled. Were you in demo mode or live mode when you the above error was shown? By the way, that means your card was rejected not necessarily that the checkout isn't working. So that I can be sure what the problem is, please share with me the code you're using for the integration, replacing your Merchant ID / API key with placeholders? Thanks!

**Comment by Stavrosmylonas** [comment] 2020-12-01 11:37
any feedback?

**Comment by matthewrgourd** [comment] 2020-12-01 12:19
Hi @Stavrosmylonas, I need to investigate further. Please share the code you're using for your Simple Checkout integration. If you're unhappy about posting it here, please email me (mgourd@vivawallet.com) instead. Thanks.

**Comment by matthewrgourd** [comment] 2020-12-02 15:01
Hi @Stavrosmylonas, I've just tested buying something at https://www.grandliquidation.com/ with a card with no funds and I can confirm the 500 error is correct for a payment failure due to customer card issue. With a card with funds, and 3DS authenticated, I guarantee you the result will be a successful payment.

**Comment by matthewrgourd** [comment] 2020-12-08 07:53
Hi @Stavrosmylonas, please ignore my previous reply. There seems to be a problem with Simple Checkout on production currently. Our dev team is looking into it. I'll update you as soon as I can!

**Comment by matthewrgourd** [comment] 2020-12-08 11:49
Hi @Stavrosmylonas, FYI the dev team discovered an issue on production which has now been fixed. Let me know if any further queries, otherwise please close the issue if you feel it has been resolved. Thanks!

**Closed** 2020-12-11 16:41 UTC
Labels: Simple Checkout
