### ISSUE TITLE
Credit card and Debit pre-authorization

### ISSUE THREAD

**Issue by bonucci** [VivaPayments/API#1657] opened 2020-05-04 17:21 UTC
Hi guys, i have a situation that i wonder if there is a solution for it. Basically in my store i need to make a request for a payment order, but after make a pre-authorization for the  product insurance (rental).
The problem is that if the cart is debit, the value will be captive/hold between 1-5 days, but in the store we only can make the order of the payment (in case of damage) like after 10 days depending of the timeframe of the rental.

Does anybody have a idea a solution for it. 

regards

**Comment by matthewrgourd** [comment] 2020-05-05 12:59
Hi @bonucci, I'm not sure, I will need to get one of my colleagues in the development team to look into this. Are you already using one of our payment solutions (e.g. [e-commerce plugin](https://developer.vivawallet.com/e-commerce-plugins/ or [online checkout](https://developer.vivawallet.com/online-checkouts/))). If so, please describe what you have implemented.

**Comment by bonucci** [comment] 2020-05-05 13:14
Thanks @matthewrgourd , im using online checkout . I need to have a way in blocking payments from debit cards because the products (rental) have a insurance associated. The idea is to let the user to pay in whatever card (debit/credit)  in case of sell products because the payment is already made, but in case of rental products i need to have a 30 days extension period to be captivated wich only credit cards are able to do that.

**Comment by matthewrgourd** [comment] 2020-05-05 13:30
Hi there, I don't think that's possible but I'll check with a developer and get back to you...

**Comment by matthewrgourd** [comment] 2020-05-18 09:53
Hi @bonucci I believe that this is a duplicate of #1674. If not, please can you edit #1674 to include any additional queries.

**Closed by matthewrgourd** 2020-05-18 09:53 UTC
Labels: developer
