### ISSUE TITLE
Magento 2.2.7 Order Status does not change after Success Payment

### ISSUE THREAD

**Issue by jimkar** [VivaPayments/API#1696] opened 2020-05-22 13:25 UTC
Hi after successfully payment the order status does not change to Complete but remains Pending Payment.

**Comment by matthewrgourd** [comment] 2020-05-22 14:10
Please may I have your website address and trading name. In order for me to check can you give me the date and approximate time of the pending transaction.

**Comment by jimkar** [comment] 2020-05-22 15:06
Hi the website is https://www.skroutz.com.cy/.
The trading name is "P. TH. UPKEEP & NET SERVICES LTD"

We do not have problem with only one payment, all the payments are remaining Pending.
 
You can check for example the payment that took place on May 22, 2020, 2:34:19 PM

**Comment by matthewrgourd** [comment] 2020-05-22 16:14
Hi @jimkar, I can see four successful e-commerce payments on your account today. There seem to be no failed transactions. If you're confident about making code changes, you could try decreasing the value of `PaymentTimeOut` to 300  (5 minutes) within the following plugin file: `Ced/VivaPayments/Model/PaymentMethod.php`
For more information on this parameter, see [Create payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post) in our API reference.

**Comment by jimkar** [comment] 2020-05-26 06:57
Hi @matthewrgourd  we just change the value you mentioned. The default value was on 24 hours. We will check if the problem is fixed and we will let you know.

**Comment by jimkar** [comment] 2020-05-26 13:41
Hi we are getting this error now

https://drive.google.com/file/d/1oT04p-zVxJ7p1qRlFgcWT2MZjB00bk2Y/view

Can you please check this out?

**Comment by jimkar** [comment] 2020-05-27 08:13
Dear @matthewrgourd  please check this out, the orders still remains on pending payment and in some cases after the redirect to viva payment checkout and the order confirmation we get the 400 error. We can not use the viva plugin we theses errors. We need some serious support, definitely more than some answers on github. The order status remains pending payment (we did change the timeout to 300) and after the order confirmation we get 400 error (probably on the redirect on our site). Can you help us?

**Comment by matthewrgourd** [comment] 2020-05-27 10:22
Hi @jimkar this is the official technical support for Viva Wallet plugins. There is no other option available, I'm afraid. You can raise with customer services but they will probably ask me so easier to communicate here. I can definitely investigate further but I will need some screenshots:

- Magento payment module settings (hide your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by jimkar** [comment] 2020-05-27 12:10
Hi @matthewrgourd  the screenshots are bellow : please reply as soon as possible

![viva2](https://user-images.githubusercontent.com/8845568/83017368-323bb380-a02c-11ea-84ae-9586aae504c2.png)
![viva4](https://user-images.githubusercontent.com/8845568/83017371-32d44a00-a02c-11ea-8e12-a18984ea7abd.png)
![viva3](https://user-images.githubusercontent.com/8845568/83017373-336ce080-a02c-11ea-8370-4faad15e0d76.png)
![viva1](https://user-images.githubusercontent.com/8845568/83017374-34057700-a02c-11ea-8619-359b0002cf47.png)

**Comment by matthewrgourd** [comment] 2020-05-27 12:31
Hi @jimkar, thanks for sending through those screenshots. The settings all look fine with the exception of Transaction URL in your module settings. Can you change this to `https://www.vivapayments.com/api/transactions` (without the forward-slash at the end). It shouldn't make any difference but just in case...

Regarding the payment time-out we discussed before in 
`Ced/VivaPayments/Model/PaymentMethod.php` can you return it to the previous setting, i.e. `$poststring['PaymentTimeOut'] = 86400;`

In our CRM there are 5 successful payments showing for 27/05/2020. Can you tell me what if there are 5 corresponding completed orders showing in Magento?

Do you have any other Magento plugins installed? What version of php are you using?

**Comment by jimkar** [comment] 2020-05-27 13:09
hi @matthewrgourd  all the orders remains on Pending Payment status.
we made the change on extension settings (remove the forward-slash at the end).
The PHP version is 7.1.24

**Comment by matthewrgourd** [comment] 2020-05-27 14:12
Hi @jimkar, ok, thanks for the info. I'm checking with the original developer to find out why the issue is occurring.

In the meantime, if practical, you could try temporarily disabling the other extensions and re-testing a purchase with our plugin.

**Comment by jimkar** [comment] 2020-05-27 14:15
hi @matthewrgourd  after the final changes it seems to work at least on failed transactions, we will check the success transactions and we will inform you back

**Comment by matthewrgourd** [comment] 2020-05-27 14:26
Ok, no problem, @jimkar. Developer has replied that it shouldn't be a problem with the Viva Wallet plugin but it might be useful to check your logs at the same time as viewing this info about 400 errors: https://airbrake.io/blog/http-errors/400-bad-request

**Comment by matthewrgourd** [comment] 2020-06-01 08:00
Hi @jimkar please close this ticket if the issue is now solved. Thanks!

**Closed** 2020-06-08 15:12 UTC
Labels: e-commerce plugin
