### ISSUE TITLE
Server Error in '/web' Application.

### ISSUE THREAD

**Issue by o-germanos** [VivaPayments/API#1447] opened 2020-03-10 10:53 UTC
Clients cant buy from my eshop using the credict card any more. Can you help me?
![viva](https://user-images.githubusercontent.com/18189726/76305331-a4beb200-62cd-11ea-87d8-ebe5425afd4d.jpg)

**Comment by matthewrgourd** [comment] 2020-03-10 16:00
Sorry to hear that. Please let me have the web address of your e-shop so I can investigate. Also, if you could email me (mgourd@vivawallet.com) your Merchant ID quoting this issue (#1447). Thanks!

**Comment by matthewrgourd** [comment] 2020-03-11 09:31
Hi there, are you using our plugin for the e-commerce platform osCommerce? Please check our [documentation](https://developer.vivawallet.com/e-commerce-plugins/oscommerce/). The correct success/fail URLs for your payment source are:

- Success URL – checkout_process.php?act=vivawallet&status=success
- Failure URL – checkout_process.php?act=vivawallet&status=fail

**Comment by o-germanos** [comment] 2020-03-20 09:50
Hi,
The URL's are ok. Also we didn't make any changes. Can you please tell me what else can it be?

**Comment by matthewrgourd** [comment] 2020-03-20 10:05
Which payment source ID have you specified in the plugin settings? I notice you have two set up at the Viva Wallet account end.

**Comment by o-germanos** [comment] 2020-03-20 10:20
The second one was made after this issue but i can't delete it. The source code is 4057 if you mean this? Thank you!!!

**Comment by matthewrgourd** [comment] 2020-03-20 10:41
The settings for 4057 are wrong. Please try 2038 instead (settings are correct).

**Comment by o-germanos** [comment] 2020-03-20 13:00
Ok i change it to 2038 but there is the same error coming:

Server Error

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable. Should i sent you an image of my settings?

**Comment by o-germanos** [comment] 2020-03-20 13:01
https://www.vivapayments.com/web/newtransaction.aspx?Ref=
Is this the correct url coming out after confirming?

**Comment by matthewrgourd** [comment] 2020-03-20 13:35
Hi @o-germanos, yes, please, but please blank out any confidential information.

**Comment by o-germanos** [comment] 2020-03-20 16:53
![viva11](https://user-images.githubusercontent.com/18189726/77186782-196acb00-6adc-11ea-998e-2ee38f982aa1.jpg)

**Comment by o-germanos** [comment] 2020-03-20 16:53
![viva22](https://user-images.githubusercontent.com/18189726/77186804-21c30600-6adc-11ea-9f19-83093750d313.jpg)

**Comment by matthewrgourd** [comment] 2020-03-20 17:04
Hi @o-germanos I think the problem is you can't have `catalog/` as part of the success/failure URLs. Can you try removing?

**Comment by o-germanos** [comment] 2020-03-20 17:46
It was also like this before the issue but anyway i tried also without catalog/ and i have exactly the same error. /catalog/ is a part of my websites url and it is always at the end that's why.

**Comment by o-germanos** [comment] 2020-03-20 17:48
https://www.mysite/catalog/checkout_confirmation.php

**Comment by o-germanos** [comment] 2020-03-20 17:56
IS THIS OK?

**Comment by o-germanos** [comment] 2020-03-20 17:56
![viva-3](https://user-images.githubusercontent.com/18189726/77192262-f1339a00-6ae4-11ea-9e75-5322c36421d7.jpg)

**Comment by matthewrgourd** [comment] 2020-03-26 13:47
Hi @o-germanos I've checked again and you definitely can't have "catalog" in the success failure URLs. What is your acutual live web address and I'll check further for you?

**Comment by o-germanos** [comment] 2020-03-27 08:37
Hi! www.germanos.parts

**Comment by matthewrgourd** [comment] 2020-03-27 08:48
Hi @o-germanos, thanks for all the info. I'm going to pass on to our development team as a possible problem with our plugin. I'll update you as soon as I can. Apologies for any inconvenience caused.

**Comment by o-germanos** [comment] 2020-04-07 07:42
Hi, hope you are well. Do you have any news?

**Comment by matthewrgourd** [comment] 2020-04-08 13:28
Hi @o-germanos one of our developers has suggested you remove "www" from the Success URL.

URL:
> Error: https://www.vivapayments.com/web
> Success: https://vivapayments.com/web

Does this help at all?

**Comment by o-germanos** [comment] 2020-04-10 11:34
Sorry also not working. My developer told me now that viva changed the version into a newer one and he has to make some changes?

**Comment by matthewrgourd** [comment] 2020-04-20 10:03
Hi @o-germanos, in order to investigate further, can you send me a further screenshot, this time of your osCommerce settings page, with your merchant ID / API key blurred out? Thanks!

**Comment by o-germanos** [comment] 2020-04-21 06:46
![viva](https://user-images.githubusercontent.com/18189726/79833973-f4a49480-83b4-11ea-8121-75c5f3f1bf3b.jpg)

**Comment by matthewrgourd** [comment] 2020-04-21 08:02
Hi @o-germanos, thanks for that. Looks fine. However, I went back to your source setup in your Viva Wallet account and noticed that for **Domain Name** you had germanos.parts instead of www.germanos.parts. I've changed that now. Please try again. If no change, then I'm afraid you will definitely have to remove `catalog/` from the Success / Failure URLs as it doesn't match what we specify in our developer portal for [osCommerce](https://developer.vivawallet.com/e-commerce-plugins/oscommerce/). Thanks!

**Comment by o-germanos** [comment] 2020-04-21 11:59
Hi! Thank's a lot! I made some tests but the same error is showing up. The problem is that it was working before like it is with catalog/. The only thing is that before my code was 4057 instead 2038 after i made a new account and deactivated 4057. Is this oκ or should i delete 2038 and activate 4057 again;

**Comment by o-germanos** [comment] 2020-04-21 12:07
Also my last payment with code 4057 was 27/01 and we didnt made changes after that at all. Is it possible that Viva made an uptade after 27/01 or something like this and we have to make some "other" changes?

**Comment by matthewrgourd** [comment] 2020-04-21 12:48
2038 is set up correctly as a payment source now if you say the previous source worked with catalog/ before. So all I can think now is that you maybe mistyped your Merchant ID or API key in the osCommerce settings. Can you please double-check both of these?

**Comment by o-germanos** [comment] 2020-04-23 11:28
Everything is fine. Merchant ID or API key are correct. I tried again without catalog but it doesn't working neither.

**Comment by matthewrgourd** [comment] 2020-05-29 15:13
Hi @o-germanos are you still experiencing issues with our plugin?

**Comment by matthewrgourd** [comment] 2020-06-01 08:04
Closing issue as no reply...

**Comment by o-germanos** [comment] 2020-06-01 08:35
???

**Comment by matthewrgourd** [comment] 2020-06-01 08:46
@o-germanos are you still experiencing issues with our plugin? It should work with `catalog/` inserted before the documented success / failure URLs. If not, please let me know and I'll let our original plugin developer know today so he can test.

**Comment by o-germanos** [comment] 2020-06-01 12:28
ok

**Comment by o-germanos** [comment] 2020-06-01 12:39
With or without catalog the same error "404 - File or directory not found". Sorry!

**Comment by matthewrgourd** [comment] 2020-06-01 14:27
Hi @o-germanos I've raised this with the original plugin developer who may be able to shed more light. He's asking for the latest screenshots. Sorry to trouble you for these again, but can you send through the current Viva Wallet payment source settings for your domain as well as one of the OSCommerce configuration with your merchant ID / API key blurred out?

**Comment by o-germanos** [comment] 2020-06-02 07:28
![VIVA_1](https://user-images.githubusercontent.com/18189726/83492324-cb028100-a4bb-11ea-84eb-4fb7ef654202.JPG)
![VIVA_2](https://user-images.githubusercontent.com/18189726/83492336-ce960800-a4bb-11ea-95cc-99929551b873.jpg)

**Comment by matthewrgourd** [comment] 2020-06-02 09:05
Hi @o-germanos our dev advises that your server may not be running the PHP cURL extension needed by the plugin. Usually this extension is activated by default on webservers, but in some cases it might not be. Can you check, please?

**Comment by o-germanos** [comment] 2020-06-02 09:09
Ok I will let you know as soon as possible. Thanks!

**Comment by o-germanos** [comment] 2020-06-03 09:52
Hi again, 
No this is also ok but i still have version 1, Is it possible that this is why it is not working any more?

**Comment by matthewrgourd** [comment] 2020-06-03 12:42
Version 1 of php cURL do you mean? Shouldn't matter. Can you try to double-check that the API key (where you need to enter it in the settings) is 100% correct without trailing spaces etc. You could generate a new API key to be sure. If still not working, I'm afraid our plugin developer is asking for some additional screenshots:

- Payment plugin settings (partially mask the API Key).
- Viva Wallet payment source settings (include the browser's URL in the screenshot).
- Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
- API Access page (partially mask API Key, include the browser's URL in the screenshot).

Sorry this is taking such a long time to resolve!

**Comment by matthewrgourd** [comment] 2020-06-08 09:00
Closing as no reply...

**Closed by matthewrgourd** 2020-06-08 09:00 UTC
Labels: awaiting client reply, e-commerce plugin
