### ISSUE TITLE
Urgent Help Needed Please

### ISSUE THREAD

**Issue by ellebee80** [VivaPayments/API#1484] opened 2020-03-23 14:25 UTC
Hello,
I am having an issue with Viva Payments, I am using them on my site www.cbdbodycare.co.uk and over the weekend including today some orders are successful, go to processing and the payment is showing on my wallet however some orders are not successful, they are not taking the customer to the declined payment page, they are being taken back to the checkout with the message 'error occurred please try again', which as you can guess is confusing if they again try and place the order. when the orders are not successful they are still generating in woocommerce and showing on my order system as an order paid by viva with an order number but the status is pending payment, obviously due to this the customer is not getting an order email and I am now having to put the orders on hold manually so that they get an email as for some reason I cannot find a pending payment email to set up, i have spoken to Viva and they have said I need to raise the issue. I am using the correct integration as I had a different problem a few weeks ago where it just stopped working for no apparent reason and I spoke to you and re installed the plug in, re integrated following your instructions so it should all be working well. My customers have advised there is not a problem with their card so i need to urgently understand what is happening as I am going to lose customers over this and end up refunding etc when they are trying to place the order multiple times due to not getting a declined message or the payment not going through. Please can someone assist urgently. I am considering going elsewhere as i seem to run fine for a few months then keep getting issues like this. Thanks

**Comment by ellebee80** [comment] 2020-03-23 15:04
Ok so I’ve just reinstalled and placed a test order, the successful test order went through fine but the failed one (I place a stupidly high priced order and cleared the account first so it failed due to insufficient funds) dropped onto the page that I mentioned that says an error occurred, see photo, surely this isn’t your failed landing page? This isn’t clear to the customer why the error occurred, it needs to specify they the payment has been declined as this looks like there is an issue with the website and not the payment details, please advise, thanks (also I find it hard to believe that I’ve had 4 customers this weekend all of whom have had their payments declined due to their or their banks errors and not ours so please address that issue also) thanks

**Comment by ellebee80** [comment] 2020-03-23 15:06
![FB3A4A76-36B6-4B4B-884A-1BD8999CB761](https://user-images.githubusercontent.com/61050248/77330864-d6953700-6d17-11ea-9d10-a4d01c7e3980.jpeg)

#

**Comment by matthewrgourd** [comment] 2020-03-23 15:23
Hi @ellebee80 sorry to hear this. I see what you mean about the failure message. I just tried myself to buy something with a card (with no funds) and got the same error. 

In order for me to investigate further what your issue might be, please send through the following screenshots:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Also, if you could email me your Merchant ID referencing this issue number (#1484) I can check your account. Thanks!

**Comment by ellebee80** [comment] 2020-03-23 16:28
![9B189501-4B70-4CA6-B37D-B6CB3C632870](https://user-images.githubusercontent.com/61050248/77339121-3f35e100-6d23-11ea-83d3-5cf08f858f5d.png)
![0ACB5F2B-F353-4262-B5D8-4EC7EA5D337F](https://user-images.githubusercontent.com/61050248/77339131-4230d180-6d23-11ea-9196-15bf8b1181b1.png)
![BCE068D3-11ED-4729-9408-D4EBA45B11E7](https://user-images.githubusercontent.com/61050248/77339134-4361fe80-6d23-11ea-91d7-c51b79800eab.png)
![2A19AA5C-840E-452A-A1BD-264E04D88334](https://user-images.githubusercontent.com/61050248/77339143-43fa9500-6d23-11ea-83b4-a0975941c975.png)
![AC01CE3A-1005-47D6-9283-0BA47F89C13C](https://user-images.githubusercontent.com/61050248/77339144-44932b80-6d23-11ea-966c-44801036e777.jpeg)
![A02E4C3E-F1FB-4322-8929-2289A84467F4](https://user-images.githubusercontent.com/61050248/77339150-44932b80-6d23-11ea-8d20-2015781a43c4.jpeg)
![Uploading 27A015DE-166E-4FF2-B5B7-58EA54E96064.png…]()




![D0C18C7F-AB86-410C-99B9-9D2B2EE6D641](https://user-images.githubusercontent.com/61050248/77339139-4361fe80-6d23-11ea-878f-f68a6a1a7d79.png)

**Comment by ellebee80** [comment] 2020-03-23 16:29
Hi thanks for replying there should be 8 pictures there and I hope they are what you've asked for? Could I have your email please for the merchant ID? Thanks

**Comment by matthewrgourd** [comment] 2020-03-23 16:57
Thanks very much for those, @ellebee80. My email is mgourd@vivawallet.com

**Comment by ellebee80** [comment] 2020-03-23 19:19
Thanks so much I’ve emailed them over I hope you can sort this for me

**Comment by matthewrgourd** [comment] 2020-03-24 11:07
Hi @ellebee80, just need to check, did you download our official version of the Viva Wallet WooCommerce plugin from the following page?

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by matthewrgourd** [comment] 2020-03-24 11:32
@ellebee80 I tested yesterday and received a generic error message when my card with no funds was declined. Is this the main problem you're referring to? Do you know what happens when a purchase goes through successfully? I've passed on to our development team and will update you as soon as I hear back.

**Comment by ellebee80** [comment] 2020-03-24 11:38
Hi yes I did thanks 

Thanks 
Lena

**Comment by ellebee80** [comment] 2020-03-24 14:15
Hi Matt Just letting you know that your 2 orders are showing on woocommerce and are showing as pending payment. Yes I did download from there.  ThanksLena From: matthewrgourdSent: 24 March 2020 11:07To: VivaPayments/APICc: ellebee80; MentionSubject: Re: [VivaPayments/API] Urgent Help Needed Please (#1484) Hi @ellebee80, just need to check, did you download our official version of the Viva Wallet WooCommerce plugin from the following page?https://developer.vivawallet.com/e-commerce-plugins/woocommerce/—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by matthewrgourd** [comment] 2020-03-24 14:59
@ellebee80 thanks! I'm sorry, no updates as yet but we're working on it...

**Comment by ellebee80** [comment] 2020-03-24 15:01
Thanks Matthew 

Thanks 
Lena

**Comment by ellebee80** [comment] 2020-03-24 16:25
Ok thank you, just to let you know someone has ordered today and her payment was successfully but she tried to order last night and it failed twice, I’ve emailed her to see if there’s a reason her side why it failed to see if that can help


Thanks 
Lena

**Comment by matthewrgourd** [comment] 2020-03-25 10:35
Hi @ellebee80 I've got a successful Visa payment from yesterday shortly after 5pm showing on your account. So looks like transactions are going through but failures are not going to the correct page on your website. I keep prodding our developers to look into it to check if there's a problem at our end but unfortunately today is a national holiday in Greece where they're based. I'll try again tomorrow.

**Comment by ellebee80** [comment] 2020-03-25 10:50
Hi Matthew

Ok great thanks, as long as the failure landing page is clear to the customer and advising declined that will be fine,  is there any way for the failed orders to be sent to on hold rather than payment pending? If not I don’t suppose you know of a way for me to set up an email template in woocommerce to send to customer when it drops to pending? Or if you know of a plug-in to help with this? I already use emails on woocommerce but can’t see one for this

Thanks 
Lena

**Comment by ellebee80** [comment] 2020-03-26 17:15
Hi Matthew

Any news with this please? 

Thanks 
Lena

**Comment by matthewrgourd** [comment] 2020-03-27 09:27
@ellebee80 still chasing...apologies for the delay.

**Comment by matthewrgourd** [comment] 2020-03-27 15:35
Hi @ellebee80, sorry for the delay getting back to you. Our development team just let me know that we had a temporary outage which could have affected payments, hence why you may have experienced a problem. Can you let me know if the original issue is still there?

**Comment by ellebee80** [comment] 2020-03-27 15:42
Hi Matthew

Thanks for replying, the same issue is there 



Thanks 
Lena

**Comment by ellebee80** [comment] 2020-03-28 12:29
Hi Matthew

I am sorry to bother you again but have they giving you a resolution to this yet? It’s not acceptable for customers to not be given a declined page, it’s confusing to them, thanks 

Thanks 
Lena

**Comment by ellebee80** [comment] 2020-03-30 15:12
Hi

Any news please? 

Thanks 
Lena

**Comment by matthewrgourd** [comment] 2020-03-30 15:21
Still waiting for a conclusive answer. Let me chase.

**Comment by ellebee80** [comment] 2020-03-30 15:43
Thank you, I can’t believe they can leave it this long when we are paying for their card processing services 

Thanks 
Lena

**Comment by matthewrgourd** [comment] 2020-03-31 08:09
Hi @ellebee80 sorry for the delay. Apparently we can't find any problems with our plugin currently on a vanilla installation of WooCommerce. However I will chase the development team again today in case there's something special about your case.

**Comment by ellebee80** [comment] 2020-03-31 09:32
Hi Thanks for the reply,  do you have a screenshot of what the failed payment landing page should look like?  I can’t imagine the one I’ve sent is the one it should be

Thanks 
Lena

**Comment by matthewrgourd** [comment] 2020-03-31 09:56
Hi @ellebee80 one of our developers is having a look. Can you remind me what version of WooCommerce you're using?

**Comment by ellebee80** [comment] 2020-03-31 10:10
Hi it’s 4.0.1

Thanks 

Thanks 
Lena

**Comment by matthewrgourd** [comment] 2020-03-31 12:48
Hi @ellebee80, one of our developers has confirmed that the error message is the correct one for a declined card. I'm so sorry it's taken this long to tell you that. He also confirms that our plugin works with v 4.0.1 of WooCommerce. I've double-checked and all your settings are correct at the Viva Wallet account end so feel free to continue using it for your e-commerce site if you still wish to do so! Thanks and best regards.

**Comment by ellebee80** [comment] 2020-03-31 12:55
Hi

Thanks for letting me know, could you pass on some feedback please to them as I personally don’t think it works well,

There needs to be a declined payment screen that makes it clear the error is with the payment card and not the website (I’ve been asked this many times by customers)

Also the failed landing page needs to be failed order and not pending payment as when it’s pending I get no notification and it sits there until I see it, if the payment isn’t going to go through it needs to be sent to failed so I get an email

Thanks for your help 

Thanks 
Lena

**Comment by matthewrgourd** [comment] 2020-03-31 14:42
Hi @ellebee80 , sure, I will pass on your feedback, and apologies again.

Regarding the second bit of your issue, I've been given a bit more info. Apparently when a payment doesn't get through for any reason, the request in the back-end remains 'pending' for a period of one day after which it gets cancelled automatically. A message is then sent via the Viva Wallet banking app notifying you of the cancellation.

**Comment by ellebee80** [comment] 2020-03-31 18:53
Hi

I received the other mail, that’s fine I’ll just cancel them, regarding the pending issue they didn’t change over as you’ve been told they do,  they just sat there for days until I changed them manually 

Thanks

**Comment by matthewrgourd** [comment] 2020-04-01 08:50
Hi @ellebee80 , ok I'm reporting that back to our developers. Please close this issue now if you feel it appropriate.

**Comment by matthewrgourd** [comment] 2020-04-17 16:11
Hi @ellebee80 hope you're well. As a result of your comments, I'm happy to announce we've made some changes to the plugin. The error message is now more helpful for people whose card payments have failed. There will be further, more fundamental, updates coming up. If you want to install it now, feel free. You can download it from https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip I'm closing this issue now. Thanks!

**Closed by matthewrgourd** 2020-04-17 16:11 UTC
Labels: developer, e-commerce plugin
