### ISSUE TITLE
Issue woocommerce

### ISSUE THREAD

**Issue by crilin20** [VivaPayments/API#2035] opened 2020-12-01 14:54 UTC
I have a generic problem when I go to make the purchase.
I entered the api key and merchant ID on woocommerce -> Settings -> payments (taken from the vivawallet account, see attachment ![github](https://user-images.githubusercontent.com/75319278/100753444-0ee22e80-33ea-11eb-8679-82bf9cf668cc.jpg)  ). 
I left blank the "source code vivawallet" field (see also attachment "woocommerce_details).
![woocommerce_details](https://user-images.githubusercontent.com/75319278/100756178-41d9f180-33ed-11eb-8bd9-bd0e71bd01d0.png)

After I activated the "demo mode", I made a purchase and I received the following error:

2020-12-01T13:14:00+00:00 CRITICAL Uncaught Exception: Unable to reach Viva Payments (Not Found) in /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php:310
Stack trace:
#0 /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php(428): WC_VIVAWALLET->generate_form()
#1 /web/htdocs/www.theweedhouse.it/home/wp-includes/class-wp-hook.php(287): WC_VIVAWALLET->receipt_page()
#2 /web/htdocs/www.theweedhouse.it/home/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#3 /web/htdocs/www.theweedhouse.it/home/wp-includes/plugin.php(478): WP_Hook->do_action()
#4 /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/woocommerce/templates/checkout/order-receipt.php(44): do_action()
#5 /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/web/htdocs/www...')
#6 /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(208): wc_ in /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php alla riga 310

2020-12-01T14:10:10+00:00 CRITICAL Uncaught Exception: Unable to reach Viva Payments (Not Found) in /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php:310
Stack trace:
#0 /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php(428): WC_VIVAWALLET->generate_form()
#1 /web/htdocs/www.theweedhouse.it/home/wp-includes/class-wp-hook.php(287): WC_VIVAWALLET->receipt_page()
#2 /web/htdocs/www.theweedhouse.it/home/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#3 /web/htdocs/www.theweedhouse.it/home/wp-includes/plugin.php(478): WP_Hook->do_action()
#4 /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/woocommerce/templates/checkout/order-receipt.php(44): do_action()
#5 /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/web/htdocs/www...')
#6 /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(208): wc_ in /web/htdocs/www.theweedhouse.it/home/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php alla riga 310

**Comment by matthewrgourd** [comment] 2020-12-01 15:35
Hi @crilin20, I'm afraid you're attempting to install an unofficial plugin not supported by Viva Wallet. Please disable, delete and download the correct one from here:

https://woocommerce.com/products/viva-wallet-for-woocommerce/

Installation instructions are at the below location:

https://docs.woocommerce.com/document/viva-wallet-for-woocommerce

**Comment by crilin20** [comment] 2020-12-01 16:53
@matthewrgourd Hi and thanks for the reply.
I installed the correct plugin, enable test mode but I have "an error with credit card". this is the log:

2020-12-01T16:47:27+00:00 DEBUG 
Viva Wallet Version: 1.2.0

--- LOG STARTS HERE: API CREATE TRANSACTION ARGS : {"amount":6050,"preauth":false,"sourceCode":"WC-0002","chargeToken":"ctok_oLN0D_4coLZEgX_50Su9S1AMqDI","installments":"1","merchantTrns":"www.theweedhouse.it - Carta di credito - 2206","customerTrns":"www.theweedhouse.it - Carta di credito - 2206","currencyCode":978,"customer":{"email":"fdsfsd@gmail.com","phone":"5656656","fullname":"psquale di p","requestLang":"it"}}

--- LOG ENDS HERE 

2020-12-01T16:47:27+00:00 DEBUG 
Viva Wallet Version: 1.2.0

--- LOG STARTS HERE: API CREATE TRANSACTION : {"headers":{},"body":"{\"status\":400,\"message\":\"PaymentsCardHolderAuthenticationInvalidStatus\",\"eventId\":\"2061\"}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}

--- LOG ENDS HERE

**Comment by matthewrgourd** [comment] 2020-12-01 17:08
Hi @crilin20, what exactly is the problem now? You're in demo mode? So using our [test card](https://developer.vivawallet.com/getting-started/#test-card)? Which outcome did you choose for the 3DS popup? I believe PaymentCardHolderAuthenticationInvalidStatus means a 3DS failure has been mimicked.

**Comment by matthewrgourd** [comment] 2020-12-01 17:12
I checkout your demo account and I can see a successful test payment for 60.50 against today's date.

**Comment by crilin20** [comment] 2020-12-01 18:53
Yes I am in demo Mode Hand of course I use your test card.
I don t set nothing for3ds popup... but it's Strange because Sometimes I see 3ds popup and sometimes not.
For example I repeat an Order and doesn't appear nothing...

**Comment by matthewrgourd** [comment] 2020-12-02 12:29
Hi @crilin20, looks like you're currently in live mode at www.theweedhouse.it is that correct? I just tested with a real card and can recreate the reported issue. So that I can investigate further, please send me a screenshot of your WooCommerce payment settings with confidential info obscured (**Plugins > Installed Plugins >** [Viva Wallet for WooCommerce] **> Settings**). Thanks.

**Comment by crilin20** [comment] 2020-12-02 15:54
No I'm not...It's strange. This is the screen you request:

![Immagine](https://user-images.githubusercontent.com/75319278/100896189-a87b1000-34be-11eb-8cec-5a3e37ad5312.jpg)

And this is some log:

2020-12-02T08:11:58+00:00 DEBUG 
Viva Wallet Version: 1.2.0

--- LOG STARTS HERE: API CREATE TRANSACTION ARGS : {"amount":100,"preauth":false,"sourceCode":"7200","chargeToken":"ctok_93ce2w6mj_9qqdbih71q70ifpqM","installments":"1","merchantTrns":"www.theweedhouse.it - Carta di credito - 2212","customerTrns":"www.theweedhouse.it - Carta di credito - 2212","currencyCode":978,"customer":{"email":"minconeluca153@gmail.com","phone":"3895936434","fullname":"Luca Mincone","requestLang":"it"}}

--- LOG ENDS HERE 

2020-12-02T08:11:58+00:00 DEBUG 
Viva Wallet Version: 1.2.0

--- LOG STARTS HERE: API CREATE TRANSACTION : {"headers":{},"body":"{\"transactionId\":\"5c3b4678-c8dc-47ca-9249-19e12df19cae\"}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}

--- LOG ENDS HERE 

2020-12-02T08:22:07+00:00 DEBUG 
Viva Wallet Version: 1.2.0

--- LOG STARTS HERE: API CREATE TRANSACTION ARGS : {"amount":100,"preauth":false,"sourceCode":"7200","chargeToken":"ctok_j7j2avDxwX57bYBd3hkL7grs6qI","installments":"1","merchantTrns":"www.theweedhouse.it - Carta di credito - 2216","customerTrns":"www.theweedhouse.it - Carta di credito - 2216","currencyCode":978,"customer":{"email":"minconeluca153@gmail.com","phone":"3895936434","fullname":"Luca Mincone","requestLang":"it"}}

--- LOG ENDS HERE 

2020-12-02T08:22:07+00:00 DEBUG 
Viva Wallet Version: 1.2.0

--- LOG STARTS HERE: API CREATE TRANSACTION : {"headers":{},"body":"{\"transactionId\":\"0daed40f-c7d5-4f46-aa3d-c89e92be1b26\"}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}

--- LOG ENDS HERE 

2020-12-02T12:04:15+00:00 DEBUG 
Viva Wallet Version: 1.2.0

--- LOG STARTS HERE: API CREATE TRANSACTION ARGS : {"amount":1850,"preauth":false,"sourceCode":"7200","chargeToken":"ctok_unVir1G5E3B_y5eb9RMgZauOr1c","installments":"1","merchantTrns":"www.theweedhouse.it - Carta di credito - 2232","customerTrns":"www.theweedhouse.it - Carta di credito - 2232","currencyCode":978,"customer":{"email":"mgourd@vivawallet.com","phone":"07967813180","fullname":"Matthew Smith","requestLang":"it"}}

--- LOG ENDS HERE 

2020-12-02T12:04:15+00:00 DEBUG 
Viva Wallet Version: 1.2.0

--- LOG STARTS HERE: API CREATE TRANSACTION : {"headers":{},"body":"{\"status\":502,\"message\":\"Transaction failed\",\"eventId\":\"10051\"}","response":{"code":502,"message":"Bad Gateway"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}

--- LOG ENDS HERE

**Comment by matthewrgourd** [comment] 2020-12-03 06:32
Hi @crilin20, sorry, can you resend the screenshot with the messages shown at the top after you save the settings. This is important for troubleshooting. BTW, your settings page shows demo mode is deselected. In this case, to test your checkout you would need to make a real purchase with a real card (you can easily refund this). If you want to try first with our demo card 5511070000000020, you need to make sure demo mode is ticked. Thanks.

**Comment by crilin20** [comment] 2020-12-03 07:57
Hi, as show below my live credentials are valid (the same with source code).

![Immagine](https://user-images.githubusercontent.com/75319278/100980439-82e51980-3545-11eb-928a-89d70d73c03f.jpg)

**Comment by matthewrgourd** [comment] 2020-12-03 08:21
Hi @crilin20, thanks for confirming. I just tested buying something on your website again (with a card with no funds) and I can confirm that our plugin is working without any issues. Please close this GitHub ticket if you are happy.

**Closed** 2020-12-04 07:49 UTC
Labels: e-commerce plugin
