### ISSUE TITLE
URGENT VIVA PAYMENTS

### ISSUE THREAD

**Issue by NikVlachos** [VivaPayments/API#1635] opened 2020-04-27 12:23 UTC
![pic5](https://user-images.githubusercontent.com/64415163/80372166-c1be3d00-889b-11ea-80a0-9d524c322f88.jpg)
![pic4](https://user-images.githubusercontent.com/64415163/80372167-c1be3d00-889b-11ea-8430-f36e2bd8584a.jpg)

My website is https://sapon.gr/
I installed the plugin viva payments with version 3.6.0 and I had a problem with the attachment.
Please for your help. Give it a try to buy something with viva option to see the problem.

**Comment by matthewrgourd** [comment] 2020-04-27 13:55
Duplicate of #1636

**Closed by matthewrgourd** 2020-04-27 13:55 UTC
