### ISSUE TITLE
Magento 2 issue

### ISSUE THREAD

**Issue by benjamin-dot** [VivaPayments/API#1345] opened 2020-01-31 14:45 UTC
Hi,

On a Magento to store we are getting the error below when trying to pay for a product:

Notice: Trying to get property of non-object in app\/code\/Ced\/VivaPayments\/Model\/PaymentMethod.php on line 202

**Comment by benjamin-dot** [comment] 2020-02-03 09:18
anybody got any ideas? We've got a client wanting to use VivaPayments and we can't progress without resolving this

**Comment by matthewrgourd** [comment] 2020-02-03 10:01
Hi @benjamin-dot sorry to hear this. Which version of php are you using?

**Comment by benjamin-dot** [comment] 2020-02-03 10:07
we're running 7.1 at the minute

**Comment by matthewrgourd** [comment] 2020-02-03 10:21
Hi @benjamin-dot is this a store that was working fine with Viva Wallet before? Did this start happening recently? Or maybe you're currently trying to set up our plugin. If the latter, which version of Magento is being used?

**Comment by benjamin-dot** [comment] 2020-02-03 10:25
We are trying to set the store up with Viva for the first time. Its Magento 2.3.4 so the latest version.

**Comment by matthewrgourd** [comment] 2020-02-03 13:37
Hi @benjamin-dot, did you follow our [installation guide](https://developer.vivawallet.com/e-commerce-plugins/magento2.3/) closely? Just a suggestion, but is there any way you could try a version of Magento prior to 2.3.4 in case that makes any difference?

**Comment by benjamin-dot** [comment] 2020-02-03 15:59
do you plan to support 2.3.4, is it tested on it?

**Comment by matthewrgourd** [comment] 2020-02-03 16:02
Hi @benjamin-dot not sure yet what the issue is. Let me check with a developer and get back to you. Thanks!

**Comment by benjamin-dot** [comment] 2020-02-04 09:21
I've checked the viva wallets website and the payment source is not active, could this be the issue?

What do I set as the order code url, gateway URL and transaction URL for live payments?

**Comment by benjamin-dot** [comment] 2020-02-04 09:57
hello?

**Comment by matthewrgourd** [comment] 2020-02-04 10:36
Hi @benjamin-dot please can I have your business name so I can check your account?

**Comment by benjamin-dot** [comment] 2020-02-04 10:42
can i email it to you?

**Comment by matthewrgourd** [comment] 2020-02-04 10:47
Yes, sure, and your Merchant ID, too if possible!

**Comment by benjamin-dot** [comment] 2020-02-04 10:54
whats your email address?

**Comment by matthewrgourd** [comment] 2020-02-04 10:55
Oops! Sorry, here you go: mgourd@vivawallet.com

**Comment by matthewrgourd** [comment] 2020-02-04 11:13
Hi, it will be the payment source in pending that's the issue. I'm checking with our accounts team if there's anything we can do to expedite.

**Comment by benjamin-dot** [comment] 2020-02-04 11:15
that is great thanks

**Comment by benjamin-dot** [comment] 2020-02-04 15:17
I've been told the account is now active however I am still getting the same error.

**Comment by matthewrgourd** [comment] 2020-02-04 15:34
Hi @benjamin-dot apologies for the delay, we're looking into this now.

**Comment by benjamin-dot** [comment] 2020-02-04 17:07
Hi Matt,

What exactly needs to go in the terms of use?

**Comment by benjamin-dot** [comment] 2020-02-05 12:56
Hi Matt,

As discussed via email, after getting the viva wallet application approved we are still getting the same error.

I've also tried this on version 2.3.2 of Magento and we get the same error message.

**Comment by benjamin-dot** [comment] 2020-02-06 09:36
any updates?

**Comment by matthewrgourd** [comment] 2020-02-06 10:09
Hi @benjamin-dot sorry for the delayed reply. One of our devs is looking at the issue. I'll update you a bit later.

**Comment by matthewrgourd** [comment] 2020-02-06 11:29
Hi @benjamin-dot we've checked our plugin and it's working correctly. Suggest you double-check the corrrect payment source number is being specified in your Magento settings for the plugin. That is, the payment source that was previously in 'pending' status.

**Comment by benjamin-dot** [comment] 2020-02-06 11:32
The code is correct, what are the live URL's for the below?

OrderCode URL
Gateway URL
Transaction URL

**Comment by matthewrgourd** [comment] 2020-02-06 11:41
What do you have as values for these currently?

**Comment by benjamin-dot** [comment] 2020-02-06 12:14
https://demo.vivapayments.com/api/orders
https://demo.vivapayments.com/web/newtransaction.aspx
https://demo.vivapayments.com/api/transactions/

**Comment by benjamin-dot** [comment] 2020-02-06 14:02
any updates?

**Comment by matthewrgourd** [comment] 2020-02-06 14:23
Hi @benjamin-dot , thanks for those. The live equivalents are:

https://www.vivapayments.com/api/orders
https://www.vivapayments.com/web/newtransaction.aspx
https://www.vivapayments.com/api/transactions/

...but I'm sure you have these already. I'm sorry we still haven't reached a resolution. I need to raise with our development team but I'll get back to you as soon as possible.

**Comment by benjamin-dot** [comment] 2020-02-06 14:46
got it working now, thanks!

**Comment by matthewrgourd** [comment] 2020-02-06 14:57
Hi @benjamin-dot , that's great, I'm pleased to know this! Please close the issue when you're ready.

**Comment by matthewrgourd** [comment] 2020-02-06 15:00
@benjamin-dot for future reference, can you give us an idea of what fixed your issue in the end?

**Closed** 2020-02-07 11:28 UTC
Labels: developer, e-commerce plugin
