### ISSUE TITLE
Brother I Chack my all costumer, didn’t gone throw,

### ISSUE THREAD

**Issue by tassadaq1956** [VivaPayments/API#1784] opened 2020-07-17 01:56 UTC
Brother I Chack my all costumer, didn’t gone throw,
Also I charge my all costumer another Company merchant Payment good to go.
My request pls Chack my Acount and resolved my services.
Thanks

_Originally posted by @tassadaq1956 in https://github.com/VivaPayments/API/issues/1781#issuecomment-659784138_

**Comment by matthewrgourd** [comment] 2020-07-17 14:31
Duplicate of #1781

**Closed by matthewrgourd** 2020-07-17 14:31 UTC
