### ISSUE TITLE
Login endpoint (connect/token) returns invalid_client

### ISSUE THREAD

**Issue by AlexAslan** [VivaPayments/API#832] opened 2019-04-30 10:08 UTC
Curl used (without the auth header)

`curl -X POST \
  https://accounts.vivapayments.com/connect/token \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic ...' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'cache-control: no-cache' \
  -d 'grant_type=client_credentials`

Username & password used are exactly the same as used in our e-commerce website

**Comment by ngoun** [comment] 2019-05-08 08:05
I have the same issue!

**Comment by ngoun** [comment] 2019-05-13 16:51
Can vivawallet verify this issue ? Will be any plans to be fixed?

**Comment by Stratubas** [comment] 2019-05-14 08:58
I have the same issue.

Trying to authenticate as described in [Authentication methods](https://developer.vivawallet.com/authentication-methods/#identity-server-oauth) gets me stuck at step 1.

The "accounts" endpoint returns invalid_client error, the "demo-accounts" returns 502 Bad Gateway.

**Comment by matthewrgourd** [comment] 2019-05-16 13:58
Hi there, sorry for the delayed reply. We've been looking into this and think it's because you are attempting to use OAuth2 without client credentials. You need to request these via our support team. I'm updating the developer portal with the correct instructions which will be roughly as below:

## Identity server (OAuth2)

Some API calls might not support basic authentication, in which case OAuth2 should be implemented.

| Environment | Endpoint                                             |
|-------------|------------------------------------------------------|
| Demo        | `https://demo-accounts.vivapayments.com/connect/token` |
| Production  | `https://accounts.vivapayments.com/connect/token`      |

The identity server is an OpenID Connect Provider. It is used to:

 * authenticate users using a local account store or via an external identity provider
 * provide session management and single sign-on
 * manage and authenticate clients
 * issue identity and access tokens to clients
 * validate tokens.

### Step 1: Request client credentials

The current procedure for requesting client credentials is to email <support@vivawallet.com> with "Client credentials request for API access" in the subject line of the email together with the following details in the main body:

 - business name
 - merchant ID
 - environment requested (demo or production)
 - email address

 We will email back with your Client ID and Client Secret. For the next step, you then need to translate the two client credentials into one Base64 value, for instance using [Base 64 Encoding Tool](https://support.brightcove.com/base-64-encoding-tool) Taking the below credentials as an example:

 Client ID:
 ```
 84skbbm0m2ypkjjf0nxxa50rgsjmgsrp9qk6s0ce3498n.apps.vivapayments.com:DPd(k%l(TtKI$H%YAo3XTg5AtuPWGG
 ```

 Client Secret:
 ```
 DPd(k%l(TtKI$H%YAo3XTg5AtuPWGG
 ```

 These would equate to

```
ODRza2JibTBtMnlwa2pqZjBueHhhNTByZ3NqbWdzcnA5cWs2czBjZTM0OThuLmFwcHMudml2YXBheW1lbnRzLmNvbTpEUGQoayVsKFR0S0kkSCVZQW8zWFRnNUF0dVBXR0c=
```

 in Base64 format.

### Step 2: Obtain a bearer token

Resource access is allowed to clients only with the use of access tokens. Before you can issue any calls to the Viva Payments API you need to obtain an access token by making a POST request using cURL as shown in the example below. For instructions on how to install cURL, refer to the <a href="https://curl.haxx.se/docs/install.html" target="_blank">official installation guide</a> <span style="color:#666"><i class='fas fa-external-link-alt'></i></span>.

#### Example request

```bash
curl -X POST https://demo-accounts.vivapayments.com/connect/token \
   -H "Accept: application/json" \
   -H "Authorization: Basic ODRza2JibTBtMnlwa2pqZjBueHhhNTByZ3NqbWdzcnA5cWs2czBjZTM0OThuLmFwcHMudml2YXBheW1lbnRzLmNvbTpEUGQoayVsKFR0S0kkSCVZQW8zWFRnNUF0dVBXR0c=" \
   -H "Content-Type: application/x-www-form-urlencoded" \
   -H "cache-control: no-cache" \
   -d "grant_type=client_credentials"
```

### Step 2: Accept and store the bearer token
After successful authentication, the identity server will respond by providing the access token requested.

#### Example response

If the Authorization Server authenticates the client and resource owner’s credentials, it will respond back with a JSON payload containing an access token, an expiration time set to one hour and a token type set to bearer.

```
    {
      "access_token":
      "eyJhbGciOiJSUzI1NiIsImtpZCI6IjBEOEZCOEQ2RURFQ0Y1Qzk3RUY1MjdDMDYxNkJCMjMzM0FCNjVGOUYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJEWS00MXUzczljbC05U2ZBWVd1eU16cTJYNTgifQ.eyJuYmYiOjE1NTc5OTg4MjIsImV4cCI6MTU1ODAwMjQyMiwiaXNzIjoiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJhdWQiOlsiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIiwiY29yZV9hcGkiXSwiY2xpZW50X2lkIjoiODRza2JibTBtMnlwa2pqZjBueHhhNTByZ3NqbWdzcnA5cWs2czBjZTM0OThuLmFwcHMudml2YXBheW1lbnRzLmNvbSIsInNjb3BlIjpbInVybjp2aXZhOnBheW1lbnRzOmNvcmU6YXBpOmFjcXVpcmluZyIsInVybjp2aXZhOnBheW1lbnRzOmNvcmU6YXBpOmFjcXVpcmluZzpjYXJkcyIsInVybjp2aXZhOnBheW1lbnRzOmNvcmU6YXBpOmFjcXVpcmluZzpjYXJkczp0b2tlbnMiXX0.KZpFROyMpSttra_Up5yicgQHuz-2pvnvXnDy1ElAncAc0IQtwa4BPfTnO2ihmkxDp2HEcQ58EwLJDt_wgq5ea5cwRpvLK3KPuo4tpBnIKIe0oz-vlFuh1SpMziXfohHmgOX5YWUsK9Ma4gTtcKzSmq_oNiZHQAi-qt0c6jsDRC1kwV3zDcOR4sHv-kT7d_XR3tAQo8LGp2ji-aOCg76ocZEEY99wYizSSIpylmfDfM64qDhQ9Yrck3Ms4rPO16-ijBbjeru4AWn0hZowZBKBWMPAZH77coawgSnTgkkiKngPF829eRRj1Ul_EpR5cjoIQldeXq0T08x5Qt0YjFsCpA",
      "expires_in": 3600,
      "token_type": "Bearer"
    }
```

### Step 3: Make calls to the API

From now on the Client can access API resources with the use of the access token until it expires after which it must be renewed. Each call to the API must include the access token at the authorization header with scheme **Bearer** instead of **Basic**.

**Comment by ngoun** [comment] 2019-05-17 10:24
Is viva support team aware of that because after sending the email they came back with something totally irrelevant!

**Comment by andreasagap** [comment] 2019-06-03 18:37
@matthewrgourd No one replies to support@vivawallet.com

**Comment by matthewrgourd** [comment] 2019-06-04 08:54
Apologies for giving the wrong information, we're still looking into this.

**Comment by matthewrgourd** [comment] 2019-06-04 12:17
Which APIs are you attempting to use? Please give an example.

**Comment by andreasagap** [comment] 2019-06-04 15:53
@matthewgourd Ι refer to Payment API. Creating order  needs Identity Server authentication. So I need the bearer token to proceed. 
In call connect/token what I need to add in Authorization Header after the Basic?  
I have tried Base64(merchantid:api_key) but it didn't work. 
Please tell me if you need more details.

**Comment by dpnevmatikos** [comment] 2019-06-04 16:52
Hello everyone
@andreasagap  @ngoun @Stratubas @AlexAslan unfortunately our documentation pages wrongfully state that you need to use Identity Server authentication.

**Please switch to basic authentication** instead, using your API credentials found at `vivapayments.com/selfcare/en-gb/security/apiaccess` 

![image](https://user-images.githubusercontent.com/1810462/58897763-be5d1880-8701-11e9-9bb4-0a04b283b5a2.png)

Our documentation pages will be updated ASAP to prevent further issues. 

Please accept our sincere apologies for any frustration and inconvenience caused by our mistake.

**Comment by ngoun** [comment] 2019-06-04 19:46
Do you mean @dpnevmatikos that all api calls  can be made with Basic Authentication?
For example: Can the **Retrieve Transactions** be called with Basic Auth?

**Comment by andreasagap** [comment] 2019-06-05 05:10
@dpnevmatikos I used the `/api/orders` call with **Basic authentication** and I had a successful response. 
I think that you can close the issue now.

**Comment by dpnevmatikos** [comment] 2019-06-05 07:04
@ngoun that's right. API calls listed within the [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/) section, except [Card tokenization](https://developer.vivawallet.com/api-reference-guide/payment-api/tokenize-card/), require [basic authentication](https://developer.vivawallet.com/authentication-methods/#basic-authentication) and not Identity Server authentication.

**Closed** 2019-06-05 07:07 UTC

**Comment by thanos-ar** [comment] 2019-06-05 13:46
Hello,

I've been struggling with this issue a while now. I am trying to built an integration that gets the transactions of all company cards / wallets. I've been messing around with Identity Server authentication and today, after reading your comment I was able to at least receive the list of Wallets and their balance using /api/Wallets. 
Any other endpoint I hit returns either Status 302 and a broken body "Object moved to here" or 200 with an empty transactions array (there are transactions matching the criteria). Do I need Identity Server authentication for this and if so, how to I get passed the invalid_client response?

I've tested:
/walletaccounts/v1/wallets/{walletId}/transactions:search  302
/walletaccounts/v1/wallets/{walletId}/transactions:export  302
/api/transactions/                              empty
/api/transactions/wallet_id                empty
/api/transactions/?date=date            empty

Many thanks

**Comment by ngoun** [comment] 2019-06-21 17:24
@thanos-ar  
For me
/api/transactions/?date=2019-06-21
transactions work with Basic Authentication but only for Accounts (primary etc). Not for company cards, employee cards seem to work.
@dpnevmatikos  Account Api What type of authentication needs?

**Comment by matthewrgourd** [comment] 2019-06-26 09:07
Hi @ngoun, API calls listed in the Account API use IdentityServer Authentication.

**Comment by thanos-ar** [comment] 2019-06-26 10:06
Hi @matthewrgourd, is there a way to get the emploee card transactions?

**Comment by matthewrgourd** [comment] 2019-06-26 10:36
@thanos-ar Not sure, can you help @dpnevmatikos ?

**Comment by ngoun** [comment] 2019-06-26 16:06
@matthewrgourd @dpnevmatikos  How does someone gets IdentityServer Authentication credentials?

**Comment by matthewrgourd** [comment] 2019-06-27 11:03
Hi @ngoun sorry for the delayed response. I've checked with out Development Team and unfortunately the Viva Wallet Account API has yet to be implemented. Unfortunately this means that even if you had the right credentials for requesting access tokens, it wouldn't be accessible. Apologies for not giving you this information before. What we support currently is everything described under [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/) in our Developer Portal

**Comment by adrianblynch** [comment] 2019-08-08 13:06
Hi @matthewrgourd, is it still the case that the Account API isn't up and running? I'm about to start looking into it but if it's not ready...

https://developer.vivawallet.com/api-reference-guide/account-api-details/

**Comment by matthewrgourd** [comment] 2019-08-19 10:23
Yes, I'm afraid it is still the case!
