### ISSUE TITLE
Simple CheckOut Refuse to connect Issue Demo(sandbox)

### ISSUE THREAD

**Issue by HarishankarIT** [VivaPayments/API#2075] opened 2020-12-23 10:25 UTC
Hi,

While doing a simple checkOut payment on the click of the Pay button pop-up window is not coming (error Refuse to connect ).
Demo sandbox.
Please let us know asap.
publickey="o74hi+EXG4rPLV6ZRyirmTAoTOWCLVSIz1gLYfNKe8M="

Regards,
HariIT

**Comment by matthewrgourd** [comment] 2021-01-04 09:57
Duplicate of #2085

**Closed** 2021-01-04 09:58 UTC
