### ISSUE TITLE
critical payments issue

### ISSUE THREAD

**Issue by Mpanayi** [VivaPayments/API#919] opened 2019-07-03 19:24 UTC
Hello Technical Vivapayments team. I have a concerning issue where customers payments are processing but eventually cancel. The customer is redirected to a white screen with -1 displayed in the corner. We have configured the plugin correctly (WooCommerce Vivawallet Gateway version3.5.7 by vivawallet) entering merchant id , API and 4 digit code taken from Vivawallet created. After several efforts we decided to try Viva Payment – viva wallet WooCommerce payment Gateway version 1.3.2 this also failed payment but redirects the customer saying incorrect merchant id or failed API. We have checked all settings and as of yet have no sales because we cannot receive payment. We have invested in SEO campaigns so we need to be able to sell. Please get back to us with a solution.

**Comment by VivaWalletSupport** [comment] 2019-07-04 06:37
Please close this issue in case it is a duplicate of issue 917.

**Comment by matthewrgourd** [comment] 2019-07-09 10:43
The previous issue referred to can be located at https://github.com/VivaPayments/API/issues/917

**Closed** 2019-07-15 08:58 UTC
