### ISSUE TITLE
Can't see orders into Opencart 3.0.2.0 dashboard when someone purcahce with vivawallet.

### ISSUE THREAD

**Issue by ChrisVou** [VivaPayments/API#835] opened 2019-05-03 12:41 UTC
Hello,

I am using Opencart Version 3.0.2.0.

My problem: When someone complete a purchase. I get email from vivawallet and when I log in into my vivawallet account I see the order and the money. But in the opencart dashboard, into Sales -> Orders I am not see any order.

**Note:** I test paypall and Cash On Delivery and I can see the orders into Sales -> Orders. So the problem is only with vivawallet extension.

That is big problem, because I can’t see the customer address or what he buy. 

Also I attached 2 pictures, the only think I have different is the Geo Zone on the Opencart extension, and into vivawallet website the Success and Failure URL I have my homepage url **NOT** the 
Success URL – enter index.php?route=extension/payment/vivawallet/callback&success
Failure URL – enter index.php?route=extension/payment/vivawallet/callback&fail

Any suggestion? 
Thank you!

![Vivawallet](https://user-images.githubusercontent.com/46003065/57137830-a5d3a880-6db9-11e9-8e41-03d465d6bcea.png)

![NewPaymentSource](https://user-images.githubusercontent.com/46003065/57137836-a8360280-6db9-11e9-9332-11534ca0eab9.png)

**Comment by VivaWalletSupport** [comment] 2019-05-03 14:39
Configure the payment source as described in point 4 and 5 at https://developer.vivawallet.com/e-commerce-plugins/opencart3/
If the problem persists, post a screenshot of the configured payment source.

**Comment by ChrisVou** [comment] 2019-05-07 15:48
Problem solved!

I changed the Success URL and the Failure URL as described in point 4 and 5 and worked!

Thank you.

**Comment by VivaWalletSupport** [comment] 2019-05-07 17:05
Good to hear so, please close this issue in case the problem is solved.

**Closed** 2019-05-07 18:27 UTC
