### ISSUE TITLE
access to simple checkout

### ISSUE THREAD

**Issue by thodoriskonstantoulias** [VivaPayments/API#1996] opened 2020-11-18 10:21 UTC
Hello 

I am trying to test for demo purposes and i am getting that error (500 threedsecure)
![image](https://user-images.githubusercontent.com/38888509/99517622-41c30600-2998-11eb-8a86-ed0191c1fe20.png)

Is this a problem with the registration? the Merchant id : **e4f51e74-a3b2-4804-94ae-dfc75c539bd1**
and we could register the website : **letsferrynew.dev.atcom.gr**

Thank you

**Comment by matthewrgourd** [comment] 2020-11-18 13:42
Hi @thodoriskonstantoulias, I've added the Simple Checkout API for the above Merchant ID. However, I'm not sure that is necessarily what the problem is. If you continue to have issues, please share your entire code and / or request / response logs so I can troubleshoot.

**Comment by thodoriskonstantoulias** [comment] 2020-11-19 09:55
I am still getting the above error. For further details here is what i use : 
![image](https://user-images.githubusercontent.com/38888509/99650337-f410d100-2a5d-11eb-84aa-da2a94f04317.png)

and the image from first post along with its form data 

![image](https://user-images.githubusercontent.com/38888509/99650498-28848d00-2a5e-11eb-9589-6bf927b161e2.png)

**Comment by matthewrgourd** [comment] 2020-11-19 11:42
HI @thodoriskonstantoulias, I can see what you're saying. I've tried with my demo account public key and it works, but when I use your demo public key I get the same issue as you! Not sure why that is yet. Will get back to you once I've investigated.

**Comment by matthewrgourd** [comment] 2020-12-08 11:50
Hi @thodoriskonstantoulias, FYI the dev team discovered an issue on production which has now been fixed. Let me know if any further queries, otherwise please close the issue if you feel it has been resolved. Thanks!

**Closed** 2020-12-08 11:52 UTC
Labels: Simple Checkout
